#############################################################################
# Makefile for building: GPMonitor
# Generated by qmake (2.01a) (Qt 4.8.4) on: Mon Aug 17 15:06:27 2015
# Project:  GPMonitor.pro
# Template: app
# Command: /opt/qt-4.8.4-arm/bin/qmake -spec /opt/qt-4.8.4-arm/mkspecs/qws/linux-arm-g++ CONFIG+=debug -o Makefile GPMonitor.pro
#############################################################################

####### Compiler, tools and options

CC            = arm-linux-gnueabi-gcc
CXX           = arm-linux-gnueabi-g++
DEFINES       = -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/opt/qt-4.8.4-arm/mkspecs/qws/linux-arm-g++ -I. -I/opt/qt-4.8.4-arm/include/QtCore -I/opt/qt-4.8.4-arm/include/QtNetwork -I/opt/qt-4.8.4-arm/include/QtGui -I/opt/qt-4.8.4-arm/include -I/opt/qt-4.8.4-x11/include/qwt -I/opt/qt-4.8.4-x11/include/QtXml -I. -I.
LINK          = arm-linux-gnueabi-g++
LFLAGS        = -Wl,-rpath,/opt/qt-4.8.4-arm/lib
LIBS          = $(SUBLIBS)  -L/opt/qt-4.8.4-arm/lib -lqwt -lQtXml -L/opt/qt-4.8.4-arm/lib -lQtGui -lQtNetwork -lQtCore -lrt -lpthread 
AR            = arm-linux-gnueabi-ar cqs
RANLIB        = 
QMAKE         = /opt/qt-4.8.4-arm/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = arm-linux-gnueabi-strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		visualchart.cpp \
		monitorform.cpp \
		mainform.cpp \
		waveform.cpp \
		colorchart.cpp \
		settings.cpp \
		qdevicewatcher_linux.cpp \
		qdevicewatcher.cpp \
		qdevicechangeevent.cpp \
		passworddialog.cpp \
		resetdialog.cpp \
		calibratedialog.cpp \
		serialport/linux/qextserialport.cpp \
		serialport/linux/qextserialbase.cpp \
		serialport/linux/posix_qextserialport.cpp \
		serialport/linux/ManageSerialPort.cpp moc_visualchart.cpp \
		moc_monitorform.cpp \
		moc_mainform.cpp \
		moc_waveform.cpp \
		moc_colorchart.cpp \
		moc_settings.cpp \
		moc_qdevicewatcher_p.cpp \
		moc_qdevicewatcher.cpp \
		moc_passworddialog.cpp \
		moc_resetdialog.cpp \
		moc_calibratedialog.cpp \
		moc_ManageSerialPort.cpp \
		qrc_Rsc.cpp
OBJECTS       = main.o \
		visualchart.o \
		monitorform.o \
		mainform.o \
		waveform.o \
		colorchart.o \
		settings.o \
		qdevicewatcher_linux.o \
		qdevicewatcher.o \
		qdevicechangeevent.o \
		passworddialog.o \
		resetdialog.o \
		calibratedialog.o \
		qextserialport.o \
		qextserialbase.o \
		posix_qextserialport.o \
		ManageSerialPort.o \
		moc_visualchart.o \
		moc_monitorform.o \
		moc_mainform.o \
		moc_waveform.o \
		moc_colorchart.o \
		moc_settings.o \
		moc_qdevicewatcher_p.o \
		moc_qdevicewatcher.o \
		moc_passworddialog.o \
		moc_resetdialog.o \
		moc_calibratedialog.o \
		moc_ManageSerialPort.o \
		qrc_Rsc.o
DIST          = /opt/qt-4.8.4-arm/mkspecs/common/unix.conf \
		/opt/qt-4.8.4-arm/mkspecs/common/linux.conf \
		/opt/qt-4.8.4-arm/mkspecs/common/gcc-base.conf \
		/opt/qt-4.8.4-arm/mkspecs/common/gcc-base-unix.conf \
		/opt/qt-4.8.4-arm/mkspecs/common/g++-base.conf \
		/opt/qt-4.8.4-arm/mkspecs/common/g++-unix.conf \
		/opt/qt-4.8.4-arm/mkspecs/common/qws.conf \
		/opt/qt-4.8.4-arm/mkspecs/qconfig.pri \
		/opt/qt-4.8.4-arm/mkspecs/features/qt_functions.prf \
		/opt/qt-4.8.4-arm/mkspecs/features/qt_config.prf \
		/opt/qt-4.8.4-arm/mkspecs/features/exclusive_builds.prf \
		/opt/qt-4.8.4-arm/mkspecs/features/default_pre.prf \
		/opt/qt-4.8.4-arm/mkspecs/features/debug.prf \
		/opt/qt-4.8.4-arm/mkspecs/features/default_post.prf \
		/opt/qt-4.8.4-arm/mkspecs/features/warn_on.prf \
		/opt/qt-4.8.4-arm/mkspecs/features/qt.prf \
		/opt/qt-4.8.4-arm/mkspecs/features/unix/thread.prf \
		/opt/qt-4.8.4-arm/mkspecs/features/moc.prf \
		/opt/qt-4.8.4-arm/mkspecs/features/resources.prf \
		/opt/qt-4.8.4-arm/mkspecs/features/uic.prf \
		/opt/qt-4.8.4-arm/mkspecs/features/yacc.prf \
		/opt/qt-4.8.4-arm/mkspecs/features/lex.prf \
		/opt/qt-4.8.4-arm/mkspecs/features/include_source_dir.prf \
		GPMonitor.pro
QMAKE_TARGET  = GPMonitor
DESTDIR       = 
TARGET        = GPMonitor

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_visualchart.h ui_monitorform.h ui_waveform.h ui_colorchart.h ui_settings.h ui_mainform.h ui_passworddialog.h ui_resetdialog.h ui_calibratedialog.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: GPMonitor.pro  /opt/qt-4.8.4-arm/mkspecs/qws/linux-arm-g++/qmake.conf /opt/qt-4.8.4-arm/mkspecs/common/unix.conf \
		/opt/qt-4.8.4-arm/mkspecs/common/linux.conf \
		/opt/qt-4.8.4-arm/mkspecs/common/gcc-base.conf \
		/opt/qt-4.8.4-arm/mkspecs/common/gcc-base-unix.conf \
		/opt/qt-4.8.4-arm/mkspecs/common/g++-base.conf \
		/opt/qt-4.8.4-arm/mkspecs/common/g++-unix.conf \
		/opt/qt-4.8.4-arm/mkspecs/common/qws.conf \
		/opt/qt-4.8.4-arm/mkspecs/qconfig.pri \
		/opt/qt-4.8.4-arm/mkspecs/features/qt_functions.prf \
		/opt/qt-4.8.4-arm/mkspecs/features/qt_config.prf \
		/opt/qt-4.8.4-arm/mkspecs/features/exclusive_builds.prf \
		/opt/qt-4.8.4-arm/mkspecs/features/default_pre.prf \
		/opt/qt-4.8.4-arm/mkspecs/features/debug.prf \
		/opt/qt-4.8.4-arm/mkspecs/features/default_post.prf \
		/opt/qt-4.8.4-arm/mkspecs/features/warn_on.prf \
		/opt/qt-4.8.4-arm/mkspecs/features/qt.prf \
		/opt/qt-4.8.4-arm/mkspecs/features/unix/thread.prf \
		/opt/qt-4.8.4-arm/mkspecs/features/moc.prf \
		/opt/qt-4.8.4-arm/mkspecs/features/resources.prf \
		/opt/qt-4.8.4-arm/mkspecs/features/uic.prf \
		/opt/qt-4.8.4-arm/mkspecs/features/yacc.prf \
		/opt/qt-4.8.4-arm/mkspecs/features/lex.prf \
		/opt/qt-4.8.4-arm/mkspecs/features/include_source_dir.prf \
		/opt/qt-4.8.4-arm/lib/libQtXml.prl \
		/opt/qt-4.8.4-arm/lib/libQtCore.prl \
		/opt/qt-4.8.4-arm/lib/libQtGui.prl \
		/opt/qt-4.8.4-arm/lib/libQtNetwork.prl
	$(QMAKE) -spec /opt/qt-4.8.4-arm/mkspecs/qws/linux-arm-g++ CONFIG+=debug -o Makefile GPMonitor.pro
/opt/qt-4.8.4-arm/mkspecs/common/unix.conf:
/opt/qt-4.8.4-arm/mkspecs/common/linux.conf:
/opt/qt-4.8.4-arm/mkspecs/common/gcc-base.conf:
/opt/qt-4.8.4-arm/mkspecs/common/gcc-base-unix.conf:
/opt/qt-4.8.4-arm/mkspecs/common/g++-base.conf:
/opt/qt-4.8.4-arm/mkspecs/common/g++-unix.conf:
/opt/qt-4.8.4-arm/mkspecs/common/qws.conf:
/opt/qt-4.8.4-arm/mkspecs/qconfig.pri:
/opt/qt-4.8.4-arm/mkspecs/features/qt_functions.prf:
/opt/qt-4.8.4-arm/mkspecs/features/qt_config.prf:
/opt/qt-4.8.4-arm/mkspecs/features/exclusive_builds.prf:
/opt/qt-4.8.4-arm/mkspecs/features/default_pre.prf:
/opt/qt-4.8.4-arm/mkspecs/features/debug.prf:
/opt/qt-4.8.4-arm/mkspecs/features/default_post.prf:
/opt/qt-4.8.4-arm/mkspecs/features/warn_on.prf:
/opt/qt-4.8.4-arm/mkspecs/features/qt.prf:
/opt/qt-4.8.4-arm/mkspecs/features/unix/thread.prf:
/opt/qt-4.8.4-arm/mkspecs/features/moc.prf:
/opt/qt-4.8.4-arm/mkspecs/features/resources.prf:
/opt/qt-4.8.4-arm/mkspecs/features/uic.prf:
/opt/qt-4.8.4-arm/mkspecs/features/yacc.prf:
/opt/qt-4.8.4-arm/mkspecs/features/lex.prf:
/opt/qt-4.8.4-arm/mkspecs/features/include_source_dir.prf:
/opt/qt-4.8.4-arm/lib/libQtXml.prl:
/opt/qt-4.8.4-arm/lib/libQtCore.prl:
/opt/qt-4.8.4-arm/lib/libQtGui.prl:
/opt/qt-4.8.4-arm/lib/libQtNetwork.prl:
qmake:  FORCE
	@$(QMAKE) -spec /opt/qt-4.8.4-arm/mkspecs/qws/linux-arm-g++ CONFIG+=debug -o Makefile GPMonitor.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/GPMonitor1.0.0 || $(MKDIR) .tmp/GPMonitor1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/GPMonitor1.0.0/ && $(COPY_FILE) --parents visualchart.h monitorform.h mainform.h waveform.h comdefs.h colorchart.h settings.h IRCommand.h qdevicewatcher_p.h qdevicewatcher_global.h qdevicewatcher.h qdevicechangeevent.h passworddialog.h resetdialog.h calibratedialog.h serialport/linux/qextserialport.h serialport/linux/qextserialbase.h serialport/linux/posix_qextserialport.h serialport/linux/ManageSerialPort.h .tmp/GPMonitor1.0.0/ && $(COPY_FILE) --parents Rsc.qrc .tmp/GPMonitor1.0.0/ && $(COPY_FILE) --parents main.cpp visualchart.cpp monitorform.cpp mainform.cpp waveform.cpp colorchart.cpp settings.cpp qdevicewatcher_linux.cpp qdevicewatcher.cpp qdevicechangeevent.cpp passworddialog.cpp resetdialog.cpp calibratedialog.cpp serialport/linux/qextserialport.cpp serialport/linux/qextserialbase.cpp serialport/linux/posix_qextserialport.cpp serialport/linux/ManageSerialPort.cpp .tmp/GPMonitor1.0.0/ && $(COPY_FILE) --parents visualchart.ui monitorform.ui waveform.ui colorchart.ui settings.ui mainform.ui passworddialog.ui resetdialog.ui calibratedialog.ui .tmp/GPMonitor1.0.0/ && (cd `dirname .tmp/GPMonitor1.0.0` && $(TAR) GPMonitor1.0.0.tar GPMonitor1.0.0 && $(COMPRESS) GPMonitor1.0.0.tar) && $(MOVE) `dirname .tmp/GPMonitor1.0.0`/GPMonitor1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/GPMonitor1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_visualchart.cpp moc_monitorform.cpp moc_mainform.cpp moc_waveform.cpp moc_colorchart.cpp moc_settings.cpp moc_qdevicewatcher_p.cpp moc_qdevicewatcher.cpp moc_passworddialog.cpp moc_resetdialog.cpp moc_calibratedialog.cpp moc_ManageSerialPort.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_visualchart.cpp moc_monitorform.cpp moc_mainform.cpp moc_waveform.cpp moc_colorchart.cpp moc_settings.cpp moc_qdevicewatcher_p.cpp moc_qdevicewatcher.cpp moc_passworddialog.cpp moc_resetdialog.cpp moc_calibratedialog.cpp moc_ManageSerialPort.cpp
moc_visualchart.cpp: visualchart.h
	/opt/qt-4.8.4-arm/bin/moc $(DEFINES) $(INCPATH) visualchart.h -o moc_visualchart.cpp

moc_monitorform.cpp: settings.h \
		calibratedialog.h \
		qdevicewatcher.h \
		qdevicewatcher_global.h \
		serialport/win32/win_qextserialport.h \
		serialport/win32/qextserialbase.h \
		serialport/linux/ManageSerialPort.h \
		serialport/linux/qextserialport.h \
		serialport/linux/posix_qextserialport.h \
		monitorform.h
	/opt/qt-4.8.4-arm/bin/moc $(DEFINES) $(INCPATH) monitorform.h -o moc_monitorform.cpp

moc_mainform.cpp: monitorform.h \
		settings.h \
		calibratedialog.h \
		qdevicewatcher.h \
		qdevicewatcher_global.h \
		serialport/win32/win_qextserialport.h \
		serialport/win32/qextserialbase.h \
		serialport/linux/ManageSerialPort.h \
		serialport/linux/qextserialport.h \
		serialport/linux/posix_qextserialport.h \
		waveform.h \
		visualchart.h \
		colorchart.h \
		passworddialog.h \
		resetdialog.h \
		mainform.h
	/opt/qt-4.8.4-arm/bin/moc $(DEFINES) $(INCPATH) mainform.h -o moc_mainform.cpp

moc_waveform.cpp: waveform.h
	/opt/qt-4.8.4-arm/bin/moc $(DEFINES) $(INCPATH) waveform.h -o moc_waveform.cpp

moc_colorchart.cpp: colorchart.h
	/opt/qt-4.8.4-arm/bin/moc $(DEFINES) $(INCPATH) colorchart.h -o moc_colorchart.cpp

moc_settings.cpp: calibratedialog.h \
		settings.h
	/opt/qt-4.8.4-arm/bin/moc $(DEFINES) $(INCPATH) settings.h -o moc_settings.cpp

moc_qdevicewatcher_p.cpp: qdevicewatcher_p.h
	/opt/qt-4.8.4-arm/bin/moc $(DEFINES) $(INCPATH) qdevicewatcher_p.h -o moc_qdevicewatcher_p.cpp

moc_qdevicewatcher.cpp: qdevicewatcher_global.h \
		qdevicewatcher.h
	/opt/qt-4.8.4-arm/bin/moc $(DEFINES) $(INCPATH) qdevicewatcher.h -o moc_qdevicewatcher.cpp

moc_passworddialog.cpp: passworddialog.h
	/opt/qt-4.8.4-arm/bin/moc $(DEFINES) $(INCPATH) passworddialog.h -o moc_passworddialog.cpp

moc_resetdialog.cpp: resetdialog.h
	/opt/qt-4.8.4-arm/bin/moc $(DEFINES) $(INCPATH) resetdialog.h -o moc_resetdialog.cpp

moc_calibratedialog.cpp: calibratedialog.h
	/opt/qt-4.8.4-arm/bin/moc $(DEFINES) $(INCPATH) calibratedialog.h -o moc_calibratedialog.cpp

moc_ManageSerialPort.cpp: serialport/linux/qextserialport.h \
		serialport/linux/posix_qextserialport.h \
		serialport/win32/qextserialbase.h \
		serialport/linux/ManageSerialPort.h
	/opt/qt-4.8.4-arm/bin/moc $(DEFINES) $(INCPATH) serialport/linux/ManageSerialPort.h -o moc_ManageSerialPort.cpp

compiler_rcc_make_all: qrc_Rsc.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_Rsc.cpp
qrc_Rsc.cpp: Rsc.qrc \
		images/color024.jpg \
		images/color018.jpg \
		images/color002.jpg \
		images/exit.png \
		images/color001.jpg \
		images/color032.jpg \
		images/color026.jpg \
		images/color031.jpg \
		images/color025.jpg \
		images/color019.jpg \
		images/color003.jpg \
		images/color010.jpg \
		images/color033.jpg \
		images/color027.jpg \
		images/lock.png \
		images/cal.png \
		images/color012.jpg \
		images/color004.jpg \
		images/color011.jpg \
		images/color034.jpg \
		images/color028.jpg \
		images/logo.png \
		images/color006.jpg \
		images/color013.jpg \
		images/color005.jpg \
		images/color036.jpg \
		images/color035.jpg \
		images/color029.jpg \
		images/color007.jpg \
		images/color020.jpg \
		images/color014.jpg \
		images/color037.jpg \
		images/color022.jpg \
		images/color016.jpg \
		images/color008.jpg \
		images/color021.jpg \
		images/color015.jpg \
		images/color038.jpg \
		images/color023.jpg \
		images/color017.jpg \
		images/color009.jpg \
		images/color000.jpg \
		images/color039.jpg \
		images/color030.jpg
	/opt/qt-4.8.4-arm/bin/rcc -name Rsc Rsc.qrc -o qrc_Rsc.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_visualchart.h ui_monitorform.h ui_waveform.h ui_colorchart.h ui_settings.h ui_mainform.h ui_passworddialog.h ui_resetdialog.h ui_calibratedialog.h
compiler_uic_clean:
	-$(DEL_FILE) ui_visualchart.h ui_monitorform.h ui_waveform.h ui_colorchart.h ui_settings.h ui_mainform.h ui_passworddialog.h ui_resetdialog.h ui_calibratedialog.h
ui_visualchart.h: visualchart.ui
	/opt/qt-4.8.4-arm/bin/uic visualchart.ui -o ui_visualchart.h

ui_monitorform.h: monitorform.ui
	/opt/qt-4.8.4-arm/bin/uic monitorform.ui -o ui_monitorform.h

ui_waveform.h: waveform.ui
	/opt/qt-4.8.4-arm/bin/uic waveform.ui -o ui_waveform.h

ui_colorchart.h: colorchart.ui
	/opt/qt-4.8.4-arm/bin/uic colorchart.ui -o ui_colorchart.h

ui_settings.h: settings.ui
	/opt/qt-4.8.4-arm/bin/uic settings.ui -o ui_settings.h

ui_mainform.h: mainform.ui
	/opt/qt-4.8.4-arm/bin/uic mainform.ui -o ui_mainform.h

ui_passworddialog.h: passworddialog.ui
	/opt/qt-4.8.4-arm/bin/uic passworddialog.ui -o ui_passworddialog.h

ui_resetdialog.h: resetdialog.ui
	/opt/qt-4.8.4-arm/bin/uic resetdialog.ui -o ui_resetdialog.h

ui_calibratedialog.h: calibratedialog.ui
	/opt/qt-4.8.4-arm/bin/uic calibratedialog.ui -o ui_calibratedialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainform.h \
		monitorform.h \
		settings.h \
		calibratedialog.h \
		qdevicewatcher.h \
		qdevicewatcher_global.h \
		serialport/win32/win_qextserialport.h \
		serialport/win32/qextserialbase.h \
		serialport/linux/ManageSerialPort.h \
		serialport/linux/qextserialport.h \
		serialport/linux/posix_qextserialport.h \
		waveform.h \
		visualchart.h \
		colorchart.h \
		passworddialog.h \
		resetdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

visualchart.o: visualchart.cpp visualchart.h \
		ui_visualchart.h \
		IRCommand.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o visualchart.o visualchart.cpp

monitorform.o: monitorform.cpp monitorform.h \
		settings.h \
		calibratedialog.h \
		qdevicewatcher.h \
		qdevicewatcher_global.h \
		serialport/win32/win_qextserialport.h \
		serialport/win32/qextserialbase.h \
		serialport/linux/ManageSerialPort.h \
		serialport/linux/qextserialport.h \
		serialport/linux/posix_qextserialport.h \
		ui_monitorform.h \
		comdefs.h \
		IRCommand.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o monitorform.o monitorform.cpp

mainform.o: mainform.cpp mainform.h \
		monitorform.h \
		settings.h \
		calibratedialog.h \
		qdevicewatcher.h \
		qdevicewatcher_global.h \
		serialport/win32/win_qextserialport.h \
		serialport/win32/qextserialbase.h \
		serialport/linux/ManageSerialPort.h \
		serialport/linux/qextserialport.h \
		serialport/linux/posix_qextserialport.h \
		waveform.h \
		visualchart.h \
		colorchart.h \
		passworddialog.h \
		resetdialog.h \
		ui_mainform.h \
		comdefs.h \
		IRCommand.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainform.o mainform.cpp

waveform.o: waveform.cpp waveform.h \
		ui_waveform.h \
		comdefs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o waveform.o waveform.cpp

colorchart.o: colorchart.cpp colorchart.h \
		ui_colorchart.h \
		IRCommand.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o colorchart.o colorchart.cpp

settings.o: settings.cpp settings.h \
		calibratedialog.h \
		ui_settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o settings.o settings.cpp

qdevicewatcher_linux.o: qdevicewatcher_linux.cpp qdevicewatcher_p.h \
		qdevicechangeevent.h \
		qdevicewatcher_global.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qdevicewatcher_linux.o qdevicewatcher_linux.cpp

qdevicewatcher.o: qdevicewatcher.cpp qdevicewatcher.h \
		qdevicewatcher_global.h \
		qdevicewatcher_p.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qdevicewatcher.o qdevicewatcher.cpp

qdevicechangeevent.o: qdevicechangeevent.cpp qdevicechangeevent.h \
		qdevicewatcher_global.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qdevicechangeevent.o qdevicechangeevent.cpp

passworddialog.o: passworddialog.cpp passworddialog.h \
		ui_passworddialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o passworddialog.o passworddialog.cpp

resetdialog.o: resetdialog.cpp resetdialog.h \
		ui_resetdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o resetdialog.o resetdialog.cpp

calibratedialog.o: calibratedialog.cpp calibratedialog.h \
		ui_calibratedialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o calibratedialog.o calibratedialog.cpp

qextserialport.o: serialport/linux/qextserialport.cpp serialport/linux/qextserialport.h \
		serialport/linux/posix_qextserialport.h \
		serialport/win32/qextserialbase.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qextserialport.o serialport/linux/qextserialport.cpp

qextserialbase.o: serialport/linux/qextserialbase.cpp serialport/win32/qextserialbase.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qextserialbase.o serialport/linux/qextserialbase.cpp

posix_qextserialport.o: serialport/linux/posix_qextserialport.cpp serialport/linux/posix_qextserialport.h \
		serialport/win32/qextserialbase.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o posix_qextserialport.o serialport/linux/posix_qextserialport.cpp

ManageSerialPort.o: serialport/linux/ManageSerialPort.cpp serialport/linux/ManageSerialPort.h \
		serialport/linux/qextserialport.h \
		serialport/linux/posix_qextserialport.h \
		serialport/win32/qextserialbase.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ManageSerialPort.o serialport/linux/ManageSerialPort.cpp

moc_visualchart.o: moc_visualchart.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_visualchart.o moc_visualchart.cpp

moc_monitorform.o: moc_monitorform.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_monitorform.o moc_monitorform.cpp

moc_mainform.o: moc_mainform.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainform.o moc_mainform.cpp

moc_waveform.o: moc_waveform.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_waveform.o moc_waveform.cpp

moc_colorchart.o: moc_colorchart.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_colorchart.o moc_colorchart.cpp

moc_settings.o: moc_settings.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_settings.o moc_settings.cpp

moc_qdevicewatcher_p.o: moc_qdevicewatcher_p.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qdevicewatcher_p.o moc_qdevicewatcher_p.cpp

moc_qdevicewatcher.o: moc_qdevicewatcher.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qdevicewatcher.o moc_qdevicewatcher.cpp

moc_passworddialog.o: moc_passworddialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_passworddialog.o moc_passworddialog.cpp

moc_resetdialog.o: moc_resetdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_resetdialog.o moc_resetdialog.cpp

moc_calibratedialog.o: moc_calibratedialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_calibratedialog.o moc_calibratedialog.cpp

moc_ManageSerialPort.o: moc_ManageSerialPort.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ManageSerialPort.o moc_ManageSerialPort.cpp

qrc_Rsc.o: qrc_Rsc.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_Rsc.o qrc_Rsc.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

