/********************************************************************************
** Form generated from reading UI file 'mainform.ui'
**
** Created by: Qt User Interface Compiler version 5.6.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINFORM_H
#define UI_MAINFORM_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QFrame>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHBoxLayout>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QVBoxLayout>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainForm
{
public:
    QWidget *verticalLayoutWidget;
    QVBoxLayout *belowLayout;
    QHBoxLayout *buttonLayout;
    QPushButton *btnMonitor;
    QPushButton *btnWave;
    QPushButton *btnVisualChart;
    QPushButton *btnColorChart;
    QPushButton *btnSettings;
    QPushButton *btnprint;
    QPushButton *btnreset;
    QWidget *layoutWidget;
    QHBoxLayout *mainLayout;
    QWidget *verticalLayoutWidget_2;
    QVBoxLayout *topLayout;
    QGroupBox *groupBox;
    QLabel *labTime;
    QLabel *labPatientNum;
    QLabel *labPatientNametag;
    QLabel *labPatientName;
    QLabel *labPatientNumtag;
    QLabel *labPatientType;
    QFrame *frame;

    void setupUi(QWidget *MainForm)
    {
        if (MainForm->objectName().isEmpty())
            MainForm->setObjectName(QStringLiteral("MainForm"));
        MainForm->resize(1366, 768);
        QPalette palette;
        QBrush brush(QColor(255, 255, 255, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QBrush brush1(QColor(0, 0, 0, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette.setBrush(QPalette::Active, QPalette::Light, brush1);
        palette.setBrush(QPalette::Active, QPalette::Midlight, brush1);
        palette.setBrush(QPalette::Active, QPalette::Dark, brush1);
        palette.setBrush(QPalette::Active, QPalette::Mid, brush1);
        palette.setBrush(QPalette::Active, QPalette::Text, brush);
        palette.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Active, QPalette::Base, brush1);
        QBrush brush2(QColor(13, 17, 25, 255));
        brush2.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Window, brush2);
        palette.setBrush(QPalette::Active, QPalette::Shadow, brush1);
        palette.setBrush(QPalette::Active, QPalette::AlternateBase, brush1);
        QBrush brush3(QColor(255, 255, 220, 255));
        brush3.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::ToolTipBase, brush3);
        palette.setBrush(QPalette::Active, QPalette::ToolTipText, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Light, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Midlight, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Dark, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Mid, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Window, brush2);
        palette.setBrush(QPalette::Inactive, QPalette::Shadow, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush3);
        palette.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Light, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Midlight, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Dark, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Mid, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Base, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::Window, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::Shadow, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush3);
        palette.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush1);
        MainForm->setPalette(palette);
        verticalLayoutWidget = new QWidget(MainForm);
        verticalLayoutWidget->setObjectName(QStringLiteral("verticalLayoutWidget"));
        verticalLayoutWidget->setGeometry(QRect(0, 690, 1369, 83));
        belowLayout = new QVBoxLayout(verticalLayoutWidget);
        belowLayout->setSpacing(2);
        belowLayout->setObjectName(QStringLiteral("belowLayout"));
        belowLayout->setSizeConstraint(QLayout::SetDefaultConstraint);
        belowLayout->setContentsMargins(0, 0, 0, 0);
        buttonLayout = new QHBoxLayout();
        buttonLayout->setSpacing(0);
        buttonLayout->setObjectName(QStringLiteral("buttonLayout"));
        buttonLayout->setSizeConstraint(QLayout::SetDefaultConstraint);
        btnMonitor = new QPushButton(verticalLayoutWidget);
        btnMonitor->setObjectName(QStringLiteral("btnMonitor"));
        QSizePolicy sizePolicy(QSizePolicy::Fixed, QSizePolicy::Fixed);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(btnMonitor->sizePolicy().hasHeightForWidth());
        btnMonitor->setSizePolicy(sizePolicy);
        btnMonitor->setMinimumSize(QSize(190, 70));
        QPalette palette1;
        palette1.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette1.setBrush(QPalette::Active, QPalette::Button, brush1);
        QBrush brush4(QColor(191, 191, 191, 255));
        brush4.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Light, brush4);
        QBrush brush5(QColor(159, 159, 159, 255));
        brush5.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Midlight, brush5);
        palette1.setBrush(QPalette::Active, QPalette::Dark, brush);
        QBrush brush6(QColor(84, 84, 84, 255));
        brush6.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Mid, brush6);
        palette1.setBrush(QPalette::Active, QPalette::Text, brush);
        palette1.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette1.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette1.setBrush(QPalette::Active, QPalette::Base, brush1);
        QBrush brush7(QColor(127, 127, 127, 255));
        brush7.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Window, brush7);
        palette1.setBrush(QPalette::Active, QPalette::Shadow, brush);
        QBrush brush8(QColor(63, 63, 63, 255));
        brush8.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::AlternateBase, brush8);
        palette1.setBrush(QPalette::Active, QPalette::ToolTipBase, brush3);
        palette1.setBrush(QPalette::Active, QPalette::ToolTipText, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::Light, brush4);
        palette1.setBrush(QPalette::Inactive, QPalette::Midlight, brush5);
        palette1.setBrush(QPalette::Inactive, QPalette::Dark, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Mid, brush6);
        palette1.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::Window, brush7);
        palette1.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush8);
        palette1.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush3);
        palette1.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::WindowText, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::Light, brush4);
        palette1.setBrush(QPalette::Disabled, QPalette::Midlight, brush5);
        palette1.setBrush(QPalette::Disabled, QPalette::Dark, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::Mid, brush6);
        palette1.setBrush(QPalette::Disabled, QPalette::Text, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::ButtonText, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::Base, brush7);
        palette1.setBrush(QPalette::Disabled, QPalette::Window, brush7);
        palette1.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush7);
        palette1.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush3);
        palette1.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush1);
        btnMonitor->setPalette(palette1);
        QFont font;
        font.setFamily(QString::fromUtf8("\346\226\207\346\263\211\351\251\233\347\255\211\345\257\254\345\276\256\347\261\263\351\273\221"));
        font.setPointSize(28);
        font.setBold(false);
        font.setWeight(50);
        btnMonitor->setFont(font);

        buttonLayout->addWidget(btnMonitor);

        btnWave = new QPushButton(verticalLayoutWidget);
        btnWave->setObjectName(QStringLiteral("btnWave"));
        sizePolicy.setHeightForWidth(btnWave->sizePolicy().hasHeightForWidth());
        btnWave->setSizePolicy(sizePolicy);
        btnWave->setMinimumSize(QSize(190, 70));
        QPalette palette2;
        palette2.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette2.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette2.setBrush(QPalette::Active, QPalette::Light, brush4);
        palette2.setBrush(QPalette::Active, QPalette::Midlight, brush5);
        palette2.setBrush(QPalette::Active, QPalette::Dark, brush);
        palette2.setBrush(QPalette::Active, QPalette::Mid, brush6);
        palette2.setBrush(QPalette::Active, QPalette::Text, brush);
        palette2.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette2.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette2.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette2.setBrush(QPalette::Active, QPalette::Window, brush7);
        palette2.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette2.setBrush(QPalette::Active, QPalette::AlternateBase, brush8);
        palette2.setBrush(QPalette::Active, QPalette::ToolTipBase, brush3);
        palette2.setBrush(QPalette::Active, QPalette::ToolTipText, brush1);
        palette2.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette2.setBrush(QPalette::Inactive, QPalette::Light, brush4);
        palette2.setBrush(QPalette::Inactive, QPalette::Midlight, brush5);
        palette2.setBrush(QPalette::Inactive, QPalette::Dark, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Mid, brush6);
        palette2.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette2.setBrush(QPalette::Inactive, QPalette::Window, brush7);
        palette2.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush8);
        palette2.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush3);
        palette2.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush1);
        palette2.setBrush(QPalette::Disabled, QPalette::WindowText, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette2.setBrush(QPalette::Disabled, QPalette::Light, brush4);
        palette2.setBrush(QPalette::Disabled, QPalette::Midlight, brush5);
        palette2.setBrush(QPalette::Disabled, QPalette::Dark, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::Mid, brush6);
        palette2.setBrush(QPalette::Disabled, QPalette::Text, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::ButtonText, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::Base, brush7);
        palette2.setBrush(QPalette::Disabled, QPalette::Window, brush7);
        palette2.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush7);
        palette2.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush3);
        palette2.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush1);
        btnWave->setPalette(palette2);
        QFont font1;
        font1.setFamily(QString::fromUtf8("\346\226\207\346\263\211\351\251\233\347\255\211\345\257\254\345\276\256\347\261\263\351\273\221"));
        font1.setPointSize(28);
        btnWave->setFont(font1);

        buttonLayout->addWidget(btnWave);

        btnVisualChart = new QPushButton(verticalLayoutWidget);
        btnVisualChart->setObjectName(QStringLiteral("btnVisualChart"));
        sizePolicy.setHeightForWidth(btnVisualChart->sizePolicy().hasHeightForWidth());
        btnVisualChart->setSizePolicy(sizePolicy);
        btnVisualChart->setMinimumSize(QSize(190, 70));
        QPalette palette3;
        palette3.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette3.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette3.setBrush(QPalette::Active, QPalette::Light, brush4);
        palette3.setBrush(QPalette::Active, QPalette::Midlight, brush5);
        palette3.setBrush(QPalette::Active, QPalette::Dark, brush8);
        palette3.setBrush(QPalette::Active, QPalette::Mid, brush6);
        palette3.setBrush(QPalette::Active, QPalette::Text, brush);
        palette3.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette3.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette3.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette3.setBrush(QPalette::Active, QPalette::Window, brush7);
        palette3.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette3.setBrush(QPalette::Active, QPalette::AlternateBase, brush8);
        palette3.setBrush(QPalette::Active, QPalette::ToolTipBase, brush3);
        palette3.setBrush(QPalette::Active, QPalette::ToolTipText, brush1);
        palette3.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette3.setBrush(QPalette::Inactive, QPalette::Light, brush4);
        palette3.setBrush(QPalette::Inactive, QPalette::Midlight, brush5);
        palette3.setBrush(QPalette::Inactive, QPalette::Dark, brush8);
        palette3.setBrush(QPalette::Inactive, QPalette::Mid, brush6);
        palette3.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette3.setBrush(QPalette::Inactive, QPalette::Window, brush7);
        palette3.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush8);
        palette3.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush3);
        palette3.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush1);
        palette3.setBrush(QPalette::Disabled, QPalette::WindowText, brush8);
        palette3.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette3.setBrush(QPalette::Disabled, QPalette::Light, brush4);
        palette3.setBrush(QPalette::Disabled, QPalette::Midlight, brush5);
        palette3.setBrush(QPalette::Disabled, QPalette::Dark, brush8);
        palette3.setBrush(QPalette::Disabled, QPalette::Mid, brush6);
        palette3.setBrush(QPalette::Disabled, QPalette::Text, brush8);
        palette3.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::ButtonText, brush8);
        palette3.setBrush(QPalette::Disabled, QPalette::Base, brush7);
        palette3.setBrush(QPalette::Disabled, QPalette::Window, brush7);
        palette3.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush7);
        palette3.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush3);
        palette3.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush1);
        btnVisualChart->setPalette(palette3);
        btnVisualChart->setFont(font);

        buttonLayout->addWidget(btnVisualChart);

        btnColorChart = new QPushButton(verticalLayoutWidget);
        btnColorChart->setObjectName(QStringLiteral("btnColorChart"));
        sizePolicy.setHeightForWidth(btnColorChart->sizePolicy().hasHeightForWidth());
        btnColorChart->setSizePolicy(sizePolicy);
        btnColorChart->setMinimumSize(QSize(190, 70));
        btnColorChart->setBaseSize(QSize(0, 0));
        QPalette palette4;
        palette4.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette4.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette4.setBrush(QPalette::Active, QPalette::Light, brush4);
        palette4.setBrush(QPalette::Active, QPalette::Midlight, brush5);
        palette4.setBrush(QPalette::Active, QPalette::Dark, brush8);
        palette4.setBrush(QPalette::Active, QPalette::Mid, brush6);
        palette4.setBrush(QPalette::Active, QPalette::Text, brush);
        palette4.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette4.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette4.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette4.setBrush(QPalette::Active, QPalette::Window, brush7);
        palette4.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette4.setBrush(QPalette::Active, QPalette::AlternateBase, brush8);
        palette4.setBrush(QPalette::Active, QPalette::ToolTipBase, brush3);
        palette4.setBrush(QPalette::Active, QPalette::ToolTipText, brush1);
        palette4.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette4.setBrush(QPalette::Inactive, QPalette::Light, brush4);
        palette4.setBrush(QPalette::Inactive, QPalette::Midlight, brush5);
        palette4.setBrush(QPalette::Inactive, QPalette::Dark, brush8);
        palette4.setBrush(QPalette::Inactive, QPalette::Mid, brush6);
        palette4.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette4.setBrush(QPalette::Inactive, QPalette::Window, brush7);
        palette4.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush8);
        palette4.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush3);
        palette4.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush1);
        palette4.setBrush(QPalette::Disabled, QPalette::WindowText, brush8);
        palette4.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette4.setBrush(QPalette::Disabled, QPalette::Light, brush4);
        palette4.setBrush(QPalette::Disabled, QPalette::Midlight, brush5);
        palette4.setBrush(QPalette::Disabled, QPalette::Dark, brush8);
        palette4.setBrush(QPalette::Disabled, QPalette::Mid, brush6);
        palette4.setBrush(QPalette::Disabled, QPalette::Text, brush8);
        palette4.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::ButtonText, brush8);
        palette4.setBrush(QPalette::Disabled, QPalette::Base, brush7);
        palette4.setBrush(QPalette::Disabled, QPalette::Window, brush7);
        palette4.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush7);
        palette4.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush3);
        palette4.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush1);
        btnColorChart->setPalette(palette4);
        btnColorChart->setFont(font);

        buttonLayout->addWidget(btnColorChart);

        btnSettings = new QPushButton(verticalLayoutWidget);
        btnSettings->setObjectName(QStringLiteral("btnSettings"));
        sizePolicy.setHeightForWidth(btnSettings->sizePolicy().hasHeightForWidth());
        btnSettings->setSizePolicy(sizePolicy);
        btnSettings->setMinimumSize(QSize(190, 70));
        QPalette palette5;
        palette5.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette5.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette5.setBrush(QPalette::Active, QPalette::Light, brush4);
        palette5.setBrush(QPalette::Active, QPalette::Midlight, brush5);
        palette5.setBrush(QPalette::Active, QPalette::Dark, brush8);
        palette5.setBrush(QPalette::Active, QPalette::Mid, brush6);
        palette5.setBrush(QPalette::Active, QPalette::Text, brush);
        palette5.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette5.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette5.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette5.setBrush(QPalette::Active, QPalette::Window, brush7);
        palette5.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette5.setBrush(QPalette::Active, QPalette::AlternateBase, brush8);
        palette5.setBrush(QPalette::Active, QPalette::ToolTipBase, brush3);
        palette5.setBrush(QPalette::Active, QPalette::ToolTipText, brush1);
        palette5.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette5.setBrush(QPalette::Inactive, QPalette::Light, brush4);
        palette5.setBrush(QPalette::Inactive, QPalette::Midlight, brush5);
        palette5.setBrush(QPalette::Inactive, QPalette::Dark, brush8);
        palette5.setBrush(QPalette::Inactive, QPalette::Mid, brush6);
        palette5.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette5.setBrush(QPalette::Inactive, QPalette::Window, brush7);
        palette5.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush8);
        palette5.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush3);
        palette5.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush1);
        palette5.setBrush(QPalette::Disabled, QPalette::WindowText, brush8);
        palette5.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette5.setBrush(QPalette::Disabled, QPalette::Light, brush4);
        palette5.setBrush(QPalette::Disabled, QPalette::Midlight, brush5);
        palette5.setBrush(QPalette::Disabled, QPalette::Dark, brush8);
        palette5.setBrush(QPalette::Disabled, QPalette::Mid, brush6);
        palette5.setBrush(QPalette::Disabled, QPalette::Text, brush8);
        palette5.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette5.setBrush(QPalette::Disabled, QPalette::ButtonText, brush8);
        palette5.setBrush(QPalette::Disabled, QPalette::Base, brush7);
        palette5.setBrush(QPalette::Disabled, QPalette::Window, brush7);
        palette5.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette5.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush7);
        palette5.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush3);
        palette5.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush1);
        btnSettings->setPalette(palette5);
        btnSettings->setFont(font);

        buttonLayout->addWidget(btnSettings);

        btnprint = new QPushButton(verticalLayoutWidget);
        btnprint->setObjectName(QStringLiteral("btnprint"));
        btnprint->setEnabled(true);
        sizePolicy.setHeightForWidth(btnprint->sizePolicy().hasHeightForWidth());
        btnprint->setSizePolicy(sizePolicy);
        btnprint->setMinimumSize(QSize(190, 70));
        QPalette palette6;
        palette6.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette6.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette6.setBrush(QPalette::Active, QPalette::Light, brush4);
        palette6.setBrush(QPalette::Active, QPalette::Midlight, brush5);
        palette6.setBrush(QPalette::Active, QPalette::Dark, brush8);
        palette6.setBrush(QPalette::Active, QPalette::Mid, brush6);
        palette6.setBrush(QPalette::Active, QPalette::Text, brush);
        palette6.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette6.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette6.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette6.setBrush(QPalette::Active, QPalette::Window, brush7);
        palette6.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette6.setBrush(QPalette::Active, QPalette::AlternateBase, brush8);
        palette6.setBrush(QPalette::Active, QPalette::ToolTipBase, brush3);
        palette6.setBrush(QPalette::Active, QPalette::ToolTipText, brush1);
        palette6.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette6.setBrush(QPalette::Inactive, QPalette::Light, brush4);
        palette6.setBrush(QPalette::Inactive, QPalette::Midlight, brush5);
        palette6.setBrush(QPalette::Inactive, QPalette::Dark, brush8);
        palette6.setBrush(QPalette::Inactive, QPalette::Mid, brush6);
        palette6.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette6.setBrush(QPalette::Inactive, QPalette::Window, brush7);
        palette6.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush8);
        palette6.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush3);
        palette6.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush1);
        palette6.setBrush(QPalette::Disabled, QPalette::WindowText, brush8);
        palette6.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette6.setBrush(QPalette::Disabled, QPalette::Light, brush4);
        palette6.setBrush(QPalette::Disabled, QPalette::Midlight, brush5);
        palette6.setBrush(QPalette::Disabled, QPalette::Dark, brush8);
        palette6.setBrush(QPalette::Disabled, QPalette::Mid, brush6);
        palette6.setBrush(QPalette::Disabled, QPalette::Text, brush8);
        palette6.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette6.setBrush(QPalette::Disabled, QPalette::ButtonText, brush8);
        palette6.setBrush(QPalette::Disabled, QPalette::Base, brush7);
        palette6.setBrush(QPalette::Disabled, QPalette::Window, brush7);
        palette6.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette6.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush7);
        palette6.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush3);
        palette6.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush1);
        btnprint->setPalette(palette6);
        btnprint->setFont(font1);

        buttonLayout->addWidget(btnprint);

        btnreset = new QPushButton(verticalLayoutWidget);
        btnreset->setObjectName(QStringLiteral("btnreset"));
        btnreset->setEnabled(true);
        sizePolicy.setHeightForWidth(btnreset->sizePolicy().hasHeightForWidth());
        btnreset->setSizePolicy(sizePolicy);
        btnreset->setMinimumSize(QSize(190, 70));
        QPalette palette7;
        palette7.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette7.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette7.setBrush(QPalette::Active, QPalette::Light, brush4);
        palette7.setBrush(QPalette::Active, QPalette::Midlight, brush5);
        palette7.setBrush(QPalette::Active, QPalette::Dark, brush8);
        palette7.setBrush(QPalette::Active, QPalette::Mid, brush6);
        palette7.setBrush(QPalette::Active, QPalette::Text, brush);
        palette7.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette7.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette7.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette7.setBrush(QPalette::Active, QPalette::Window, brush7);
        palette7.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette7.setBrush(QPalette::Active, QPalette::AlternateBase, brush8);
        palette7.setBrush(QPalette::Active, QPalette::ToolTipBase, brush3);
        palette7.setBrush(QPalette::Active, QPalette::ToolTipText, brush1);
        palette7.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette7.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette7.setBrush(QPalette::Inactive, QPalette::Light, brush4);
        palette7.setBrush(QPalette::Inactive, QPalette::Midlight, brush5);
        palette7.setBrush(QPalette::Inactive, QPalette::Dark, brush8);
        palette7.setBrush(QPalette::Inactive, QPalette::Mid, brush6);
        palette7.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette7.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette7.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette7.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette7.setBrush(QPalette::Inactive, QPalette::Window, brush7);
        palette7.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette7.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush8);
        palette7.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush3);
        palette7.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush1);
        palette7.setBrush(QPalette::Disabled, QPalette::WindowText, brush8);
        palette7.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette7.setBrush(QPalette::Disabled, QPalette::Light, brush4);
        palette7.setBrush(QPalette::Disabled, QPalette::Midlight, brush5);
        palette7.setBrush(QPalette::Disabled, QPalette::Dark, brush8);
        palette7.setBrush(QPalette::Disabled, QPalette::Mid, brush6);
        palette7.setBrush(QPalette::Disabled, QPalette::Text, brush8);
        palette7.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette7.setBrush(QPalette::Disabled, QPalette::ButtonText, brush8);
        palette7.setBrush(QPalette::Disabled, QPalette::Base, brush7);
        palette7.setBrush(QPalette::Disabled, QPalette::Window, brush7);
        palette7.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette7.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush7);
        palette7.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush3);
        palette7.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush1);
        btnreset->setPalette(palette7);
        btnreset->setFont(font1);

        buttonLayout->addWidget(btnreset);


        belowLayout->addLayout(buttonLayout);

        layoutWidget = new QWidget(MainForm);
        layoutWidget->setObjectName(QStringLiteral("layoutWidget"));
        layoutWidget->setGeometry(QRect(0, 0, 1361, 691));
        mainLayout = new QHBoxLayout(layoutWidget);
        mainLayout->setObjectName(QStringLiteral("mainLayout"));
        mainLayout->setContentsMargins(0, 0, 0, 0);
        verticalLayoutWidget_2 = new QWidget(MainForm);
        verticalLayoutWidget_2->setObjectName(QStringLiteral("verticalLayoutWidget_2"));
        verticalLayoutWidget_2->setGeometry(QRect(0, 0, 1371, 71));
        topLayout = new QVBoxLayout(verticalLayoutWidget_2);
        topLayout->setSpacing(2);
        topLayout->setObjectName(QStringLiteral("topLayout"));
        topLayout->setSizeConstraint(QLayout::SetDefaultConstraint);
        topLayout->setContentsMargins(0, 0, 0, 0);
        groupBox = new QGroupBox(verticalLayoutWidget_2);
        groupBox->setObjectName(QStringLiteral("groupBox"));
        QSizePolicy sizePolicy1(QSizePolicy::Preferred, QSizePolicy::Preferred);
        sizePolicy1.setHorizontalStretch(0);
        sizePolicy1.setVerticalStretch(0);
        sizePolicy1.setHeightForWidth(groupBox->sizePolicy().hasHeightForWidth());
        groupBox->setSizePolicy(sizePolicy1);
        QPalette palette8;
        palette8.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QLinearGradient gradient(0.464, 1, 0.482, 0);
        gradient.setSpread(QGradient::PadSpread);
        gradient.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient.setColorAt(0.286364, QColor(33, 41, 62, 255));
        gradient.setColorAt(0.381818, QColor(80, 82, 106, 255));
        QBrush brush9(gradient);
        palette8.setBrush(QPalette::Active, QPalette::Button, brush9);
        palette8.setBrush(QPalette::Active, QPalette::Light, brush);
        palette8.setBrush(QPalette::Active, QPalette::Midlight, brush);
        palette8.setBrush(QPalette::Active, QPalette::Dark, brush);
        palette8.setBrush(QPalette::Active, QPalette::Mid, brush);
        palette8.setBrush(QPalette::Active, QPalette::Text, brush);
        palette8.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette8.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        QLinearGradient gradient1(0.464, 1, 0.482, 0);
        gradient1.setSpread(QGradient::PadSpread);
        gradient1.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient1.setColorAt(0.286364, QColor(33, 41, 62, 255));
        gradient1.setColorAt(0.381818, QColor(80, 82, 106, 255));
        QBrush brush10(gradient1);
        palette8.setBrush(QPalette::Active, QPalette::Base, brush10);
        QLinearGradient gradient2(0.464, 1, 0.482, 0);
        gradient2.setSpread(QGradient::PadSpread);
        gradient2.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient2.setColorAt(0.286364, QColor(33, 41, 62, 255));
        gradient2.setColorAt(0.381818, QColor(80, 82, 106, 255));
        QBrush brush11(gradient2);
        palette8.setBrush(QPalette::Active, QPalette::Window, brush11);
        palette8.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette8.setBrush(QPalette::Active, QPalette::AlternateBase, brush);
        palette8.setBrush(QPalette::Active, QPalette::ToolTipBase, brush3);
        palette8.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        QLinearGradient gradient3(0.464, 1, 0.482, 0);
        gradient3.setSpread(QGradient::PadSpread);
        gradient3.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient3.setColorAt(0.286364, QColor(33, 41, 62, 255));
        gradient3.setColorAt(0.381818, QColor(80, 82, 106, 255));
        QBrush brush12(gradient3);
        palette8.setBrush(QPalette::Inactive, QPalette::Button, brush12);
        palette8.setBrush(QPalette::Inactive, QPalette::Light, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::Midlight, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::Dark, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::Mid, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        QLinearGradient gradient4(0.464, 1, 0.482, 0);
        gradient4.setSpread(QGradient::PadSpread);
        gradient4.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient4.setColorAt(0.286364, QColor(33, 41, 62, 255));
        gradient4.setColorAt(0.381818, QColor(80, 82, 106, 255));
        QBrush brush13(gradient4);
        palette8.setBrush(QPalette::Inactive, QPalette::Base, brush13);
        QLinearGradient gradient5(0.464, 1, 0.482, 0);
        gradient5.setSpread(QGradient::PadSpread);
        gradient5.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient5.setColorAt(0.286364, QColor(33, 41, 62, 255));
        gradient5.setColorAt(0.381818, QColor(80, 82, 106, 255));
        QBrush brush14(gradient5);
        palette8.setBrush(QPalette::Inactive, QPalette::Window, brush14);
        palette8.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush3);
        palette8.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette8.setBrush(QPalette::Disabled, QPalette::WindowText, brush);
        QLinearGradient gradient6(0.464, 1, 0.482, 0);
        gradient6.setSpread(QGradient::PadSpread);
        gradient6.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient6.setColorAt(0.286364, QColor(33, 41, 62, 255));
        gradient6.setColorAt(0.381818, QColor(80, 82, 106, 255));
        QBrush brush15(gradient6);
        palette8.setBrush(QPalette::Disabled, QPalette::Button, brush15);
        palette8.setBrush(QPalette::Disabled, QPalette::Light, brush);
        palette8.setBrush(QPalette::Disabled, QPalette::Midlight, brush);
        palette8.setBrush(QPalette::Disabled, QPalette::Dark, brush);
        palette8.setBrush(QPalette::Disabled, QPalette::Mid, brush);
        palette8.setBrush(QPalette::Disabled, QPalette::Text, brush);
        palette8.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette8.setBrush(QPalette::Disabled, QPalette::ButtonText, brush);
        QLinearGradient gradient7(0.464, 1, 0.482, 0);
        gradient7.setSpread(QGradient::PadSpread);
        gradient7.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient7.setColorAt(0.286364, QColor(33, 41, 62, 255));
        gradient7.setColorAt(0.381818, QColor(80, 82, 106, 255));
        QBrush brush16(gradient7);
        palette8.setBrush(QPalette::Disabled, QPalette::Base, brush16);
        QLinearGradient gradient8(0.464, 1, 0.482, 0);
        gradient8.setSpread(QGradient::PadSpread);
        gradient8.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient8.setColorAt(0.286364, QColor(33, 41, 62, 255));
        gradient8.setColorAt(0.381818, QColor(80, 82, 106, 255));
        QBrush brush17(gradient8);
        palette8.setBrush(QPalette::Disabled, QPalette::Window, brush17);
        palette8.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette8.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush);
        palette8.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush3);
        palette8.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        groupBox->setPalette(palette8);
        groupBox->setStyleSheet(QStringLiteral("background-color: qlineargradient(spread:pad, x1:0.464, y1:1, x2:0.482, y2:0, stop:0.286364 rgba(33, 41, 62, 255), stop:0.381818 rgba(80, 82, 106, 255));"));
        labTime = new QLabel(groupBox);
        labTime->setObjectName(QStringLiteral("labTime"));
        labTime->setGeometry(QRect(1040, 0, 311, 69));
        sizePolicy1.setHeightForWidth(labTime->sizePolicy().hasHeightForWidth());
        labTime->setSizePolicy(sizePolicy1);
        labTime->setMinimumSize(QSize(240, 69));
        QPalette palette9;
        palette9.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QLinearGradient gradient9(0.464, 1, 0.482, 0);
        gradient9.setSpread(QGradient::PadSpread);
        gradient9.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient9.setColorAt(0.286364, QColor(33, 41, 62, 255));
        gradient9.setColorAt(0.381818, QColor(80, 82, 106, 255));
        QBrush brush18(gradient9);
        palette9.setBrush(QPalette::Active, QPalette::Button, brush18);
        QLinearGradient gradient10(0.464, 1, 0.482, 0);
        gradient10.setSpread(QGradient::PadSpread);
        gradient10.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient10.setColorAt(0.286364, QColor(33, 41, 62, 255));
        gradient10.setColorAt(0.381818, QColor(80, 82, 106, 255));
        QBrush brush19(gradient10);
        palette9.setBrush(QPalette::Active, QPalette::Base, brush19);
        QLinearGradient gradient11(0.464, 1, 0.482, 0);
        gradient11.setSpread(QGradient::PadSpread);
        gradient11.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient11.setColorAt(0.286364, QColor(33, 41, 62, 255));
        gradient11.setColorAt(0.381818, QColor(80, 82, 106, 255));
        QBrush brush20(gradient11);
        palette9.setBrush(QPalette::Active, QPalette::Window, brush20);
        palette9.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        QLinearGradient gradient12(0.464, 1, 0.482, 0);
        gradient12.setSpread(QGradient::PadSpread);
        gradient12.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient12.setColorAt(0.286364, QColor(33, 41, 62, 255));
        gradient12.setColorAt(0.381818, QColor(80, 82, 106, 255));
        QBrush brush21(gradient12);
        palette9.setBrush(QPalette::Inactive, QPalette::Button, brush21);
        QLinearGradient gradient13(0.464, 1, 0.482, 0);
        gradient13.setSpread(QGradient::PadSpread);
        gradient13.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient13.setColorAt(0.286364, QColor(33, 41, 62, 255));
        gradient13.setColorAt(0.381818, QColor(80, 82, 106, 255));
        QBrush brush22(gradient13);
        palette9.setBrush(QPalette::Inactive, QPalette::Base, brush22);
        QLinearGradient gradient14(0.464, 1, 0.482, 0);
        gradient14.setSpread(QGradient::PadSpread);
        gradient14.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient14.setColorAt(0.286364, QColor(33, 41, 62, 255));
        gradient14.setColorAt(0.381818, QColor(80, 82, 106, 255));
        QBrush brush23(gradient14);
        palette9.setBrush(QPalette::Inactive, QPalette::Window, brush23);
        palette9.setBrush(QPalette::Disabled, QPalette::WindowText, brush);
        QLinearGradient gradient15(0.464, 1, 0.482, 0);
        gradient15.setSpread(QGradient::PadSpread);
        gradient15.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient15.setColorAt(0.286364, QColor(33, 41, 62, 255));
        gradient15.setColorAt(0.381818, QColor(80, 82, 106, 255));
        QBrush brush24(gradient15);
        palette9.setBrush(QPalette::Disabled, QPalette::Button, brush24);
        QLinearGradient gradient16(0.464, 1, 0.482, 0);
        gradient16.setSpread(QGradient::PadSpread);
        gradient16.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient16.setColorAt(0.286364, QColor(33, 41, 62, 255));
        gradient16.setColorAt(0.381818, QColor(80, 82, 106, 255));
        QBrush brush25(gradient16);
        palette9.setBrush(QPalette::Disabled, QPalette::Base, brush25);
        QLinearGradient gradient17(0.464, 1, 0.482, 0);
        gradient17.setSpread(QGradient::PadSpread);
        gradient17.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient17.setColorAt(0.286364, QColor(33, 41, 62, 255));
        gradient17.setColorAt(0.381818, QColor(80, 82, 106, 255));
        QBrush brush26(gradient17);
        palette9.setBrush(QPalette::Disabled, QPalette::Window, brush26);
        labTime->setPalette(palette9);
        labTime->setFont(font);
        labPatientNum = new QLabel(groupBox);
        labPatientNum->setObjectName(QStringLiteral("labPatientNum"));
        labPatientNum->setGeometry(QRect(290, 0, 261, 69));
        sizePolicy1.setHeightForWidth(labPatientNum->sizePolicy().hasHeightForWidth());
        labPatientNum->setSizePolicy(sizePolicy1);
        labPatientNum->setMinimumSize(QSize(150, 69));
        QPalette palette10;
        palette10.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QLinearGradient gradient18(0.464, 1, 0.482, 0);
        gradient18.setSpread(QGradient::PadSpread);
        gradient18.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient18.setColorAt(0.286364, QColor(33, 41, 62, 255));
        gradient18.setColorAt(0.381818, QColor(80, 82, 106, 255));
        QBrush brush27(gradient18);
        palette10.setBrush(QPalette::Active, QPalette::Button, brush27);
        QLinearGradient gradient19(0.464, 1, 0.482, 0);
        gradient19.setSpread(QGradient::PadSpread);
        gradient19.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient19.setColorAt(0.286364, QColor(33, 41, 62, 255));
        gradient19.setColorAt(0.381818, QColor(80, 82, 106, 255));
        QBrush brush28(gradient19);
        palette10.setBrush(QPalette::Active, QPalette::Base, brush28);
        QLinearGradient gradient20(0.464, 1, 0.482, 0);
        gradient20.setSpread(QGradient::PadSpread);
        gradient20.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient20.setColorAt(0.286364, QColor(33, 41, 62, 255));
        gradient20.setColorAt(0.381818, QColor(80, 82, 106, 255));
        QBrush brush29(gradient20);
        palette10.setBrush(QPalette::Active, QPalette::Window, brush29);
        palette10.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        QLinearGradient gradient21(0.464, 1, 0.482, 0);
        gradient21.setSpread(QGradient::PadSpread);
        gradient21.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient21.setColorAt(0.286364, QColor(33, 41, 62, 255));
        gradient21.setColorAt(0.381818, QColor(80, 82, 106, 255));
        QBrush brush30(gradient21);
        palette10.setBrush(QPalette::Inactive, QPalette::Button, brush30);
        QLinearGradient gradient22(0.464, 1, 0.482, 0);
        gradient22.setSpread(QGradient::PadSpread);
        gradient22.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient22.setColorAt(0.286364, QColor(33, 41, 62, 255));
        gradient22.setColorAt(0.381818, QColor(80, 82, 106, 255));
        QBrush brush31(gradient22);
        palette10.setBrush(QPalette::Inactive, QPalette::Base, brush31);
        QLinearGradient gradient23(0.464, 1, 0.482, 0);
        gradient23.setSpread(QGradient::PadSpread);
        gradient23.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient23.setColorAt(0.286364, QColor(33, 41, 62, 255));
        gradient23.setColorAt(0.381818, QColor(80, 82, 106, 255));
        QBrush brush32(gradient23);
        palette10.setBrush(QPalette::Inactive, QPalette::Window, brush32);
        palette10.setBrush(QPalette::Disabled, QPalette::WindowText, brush);
        QLinearGradient gradient24(0.464, 1, 0.482, 0);
        gradient24.setSpread(QGradient::PadSpread);
        gradient24.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient24.setColorAt(0.286364, QColor(33, 41, 62, 255));
        gradient24.setColorAt(0.381818, QColor(80, 82, 106, 255));
        QBrush brush33(gradient24);
        palette10.setBrush(QPalette::Disabled, QPalette::Button, brush33);
        QLinearGradient gradient25(0.464, 1, 0.482, 0);
        gradient25.setSpread(QGradient::PadSpread);
        gradient25.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient25.setColorAt(0.286364, QColor(33, 41, 62, 255));
        gradient25.setColorAt(0.381818, QColor(80, 82, 106, 255));
        QBrush brush34(gradient25);
        palette10.setBrush(QPalette::Disabled, QPalette::Base, brush34);
        QLinearGradient gradient26(0.464, 1, 0.482, 0);
        gradient26.setSpread(QGradient::PadSpread);
        gradient26.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient26.setColorAt(0.286364, QColor(33, 41, 62, 255));
        gradient26.setColorAt(0.381818, QColor(80, 82, 106, 255));
        QBrush brush35(gradient26);
        palette10.setBrush(QPalette::Disabled, QPalette::Window, brush35);
        labPatientNum->setPalette(palette10);
        labPatientNum->setFont(font);
        labPatientNametag = new QLabel(groupBox);
        labPatientNametag->setObjectName(QStringLiteral("labPatientNametag"));
        labPatientNametag->setGeometry(QRect(550, 0, 141, 69));
        sizePolicy1.setHeightForWidth(labPatientNametag->sizePolicy().hasHeightForWidth());
        labPatientNametag->setSizePolicy(sizePolicy1);
        labPatientNametag->setMinimumSize(QSize(100, 69));
        QPalette palette11;
        palette11.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QLinearGradient gradient27(0.464, 1, 0.482, 0);
        gradient27.setSpread(QGradient::PadSpread);
        gradient27.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient27.setColorAt(0.286364, QColor(33, 41, 62, 255));
        gradient27.setColorAt(0.381818, QColor(80, 82, 106, 255));
        QBrush brush36(gradient27);
        palette11.setBrush(QPalette::Active, QPalette::Button, brush36);
        QLinearGradient gradient28(0.464, 1, 0.482, 0);
        gradient28.setSpread(QGradient::PadSpread);
        gradient28.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient28.setColorAt(0.286364, QColor(33, 41, 62, 255));
        gradient28.setColorAt(0.381818, QColor(80, 82, 106, 255));
        QBrush brush37(gradient28);
        palette11.setBrush(QPalette::Active, QPalette::Base, brush37);
        QLinearGradient gradient29(0.464, 1, 0.482, 0);
        gradient29.setSpread(QGradient::PadSpread);
        gradient29.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient29.setColorAt(0.286364, QColor(33, 41, 62, 255));
        gradient29.setColorAt(0.381818, QColor(80, 82, 106, 255));
        QBrush brush38(gradient29);
        palette11.setBrush(QPalette::Active, QPalette::Window, brush38);
        palette11.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        QLinearGradient gradient30(0.464, 1, 0.482, 0);
        gradient30.setSpread(QGradient::PadSpread);
        gradient30.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient30.setColorAt(0.286364, QColor(33, 41, 62, 255));
        gradient30.setColorAt(0.381818, QColor(80, 82, 106, 255));
        QBrush brush39(gradient30);
        palette11.setBrush(QPalette::Inactive, QPalette::Button, brush39);
        QLinearGradient gradient31(0.464, 1, 0.482, 0);
        gradient31.setSpread(QGradient::PadSpread);
        gradient31.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient31.setColorAt(0.286364, QColor(33, 41, 62, 255));
        gradient31.setColorAt(0.381818, QColor(80, 82, 106, 255));
        QBrush brush40(gradient31);
        palette11.setBrush(QPalette::Inactive, QPalette::Base, brush40);
        QLinearGradient gradient32(0.464, 1, 0.482, 0);
        gradient32.setSpread(QGradient::PadSpread);
        gradient32.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient32.setColorAt(0.286364, QColor(33, 41, 62, 255));
        gradient32.setColorAt(0.381818, QColor(80, 82, 106, 255));
        QBrush brush41(gradient32);
        palette11.setBrush(QPalette::Inactive, QPalette::Window, brush41);
        palette11.setBrush(QPalette::Disabled, QPalette::WindowText, brush);
        QLinearGradient gradient33(0.464, 1, 0.482, 0);
        gradient33.setSpread(QGradient::PadSpread);
        gradient33.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient33.setColorAt(0.286364, QColor(33, 41, 62, 255));
        gradient33.setColorAt(0.381818, QColor(80, 82, 106, 255));
        QBrush brush42(gradient33);
        palette11.setBrush(QPalette::Disabled, QPalette::Button, brush42);
        QLinearGradient gradient34(0.464, 1, 0.482, 0);
        gradient34.setSpread(QGradient::PadSpread);
        gradient34.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient34.setColorAt(0.286364, QColor(33, 41, 62, 255));
        gradient34.setColorAt(0.381818, QColor(80, 82, 106, 255));
        QBrush brush43(gradient34);
        palette11.setBrush(QPalette::Disabled, QPalette::Base, brush43);
        QLinearGradient gradient35(0.464, 1, 0.482, 0);
        gradient35.setSpread(QGradient::PadSpread);
        gradient35.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient35.setColorAt(0.286364, QColor(33, 41, 62, 255));
        gradient35.setColorAt(0.381818, QColor(80, 82, 106, 255));
        QBrush brush44(gradient35);
        palette11.setBrush(QPalette::Disabled, QPalette::Window, brush44);
        labPatientNametag->setPalette(palette11);
        labPatientNametag->setFont(font);
        labPatientName = new QLabel(groupBox);
        labPatientName->setObjectName(QStringLiteral("labPatientName"));
        labPatientName->setGeometry(QRect(690, 0, 211, 69));
        sizePolicy1.setHeightForWidth(labPatientName->sizePolicy().hasHeightForWidth());
        labPatientName->setSizePolicy(sizePolicy1);
        labPatientName->setMinimumSize(QSize(150, 69));
        QPalette palette12;
        palette12.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QLinearGradient gradient36(0.464, 1, 0.482, 0);
        gradient36.setSpread(QGradient::PadSpread);
        gradient36.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient36.setColorAt(0.286364, QColor(33, 41, 62, 255));
        gradient36.setColorAt(0.381818, QColor(80, 82, 106, 255));
        QBrush brush45(gradient36);
        palette12.setBrush(QPalette::Active, QPalette::Button, brush45);
        QLinearGradient gradient37(0.464, 1, 0.482, 0);
        gradient37.setSpread(QGradient::PadSpread);
        gradient37.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient37.setColorAt(0.286364, QColor(33, 41, 62, 255));
        gradient37.setColorAt(0.381818, QColor(80, 82, 106, 255));
        QBrush brush46(gradient37);
        palette12.setBrush(QPalette::Active, QPalette::Base, brush46);
        QLinearGradient gradient38(0.464, 1, 0.482, 0);
        gradient38.setSpread(QGradient::PadSpread);
        gradient38.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient38.setColorAt(0.286364, QColor(33, 41, 62, 255));
        gradient38.setColorAt(0.381818, QColor(80, 82, 106, 255));
        QBrush brush47(gradient38);
        palette12.setBrush(QPalette::Active, QPalette::Window, brush47);
        palette12.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        QLinearGradient gradient39(0.464, 1, 0.482, 0);
        gradient39.setSpread(QGradient::PadSpread);
        gradient39.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient39.setColorAt(0.286364, QColor(33, 41, 62, 255));
        gradient39.setColorAt(0.381818, QColor(80, 82, 106, 255));
        QBrush brush48(gradient39);
        palette12.setBrush(QPalette::Inactive, QPalette::Button, brush48);
        QLinearGradient gradient40(0.464, 1, 0.482, 0);
        gradient40.setSpread(QGradient::PadSpread);
        gradient40.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient40.setColorAt(0.286364, QColor(33, 41, 62, 255));
        gradient40.setColorAt(0.381818, QColor(80, 82, 106, 255));
        QBrush brush49(gradient40);
        palette12.setBrush(QPalette::Inactive, QPalette::Base, brush49);
        QLinearGradient gradient41(0.464, 1, 0.482, 0);
        gradient41.setSpread(QGradient::PadSpread);
        gradient41.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient41.setColorAt(0.286364, QColor(33, 41, 62, 255));
        gradient41.setColorAt(0.381818, QColor(80, 82, 106, 255));
        QBrush brush50(gradient41);
        palette12.setBrush(QPalette::Inactive, QPalette::Window, brush50);
        palette12.setBrush(QPalette::Disabled, QPalette::WindowText, brush);
        QLinearGradient gradient42(0.464, 1, 0.482, 0);
        gradient42.setSpread(QGradient::PadSpread);
        gradient42.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient42.setColorAt(0.286364, QColor(33, 41, 62, 255));
        gradient42.setColorAt(0.381818, QColor(80, 82, 106, 255));
        QBrush brush51(gradient42);
        palette12.setBrush(QPalette::Disabled, QPalette::Button, brush51);
        QLinearGradient gradient43(0.464, 1, 0.482, 0);
        gradient43.setSpread(QGradient::PadSpread);
        gradient43.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient43.setColorAt(0.286364, QColor(33, 41, 62, 255));
        gradient43.setColorAt(0.381818, QColor(80, 82, 106, 255));
        QBrush brush52(gradient43);
        palette12.setBrush(QPalette::Disabled, QPalette::Base, brush52);
        QLinearGradient gradient44(0.464, 1, 0.482, 0);
        gradient44.setSpread(QGradient::PadSpread);
        gradient44.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient44.setColorAt(0.286364, QColor(33, 41, 62, 255));
        gradient44.setColorAt(0.381818, QColor(80, 82, 106, 255));
        QBrush brush53(gradient44);
        palette12.setBrush(QPalette::Disabled, QPalette::Window, brush53);
        labPatientName->setPalette(palette12);
        labPatientName->setFont(font);
        labPatientName->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        labPatientNumtag = new QLabel(groupBox);
        labPatientNumtag->setObjectName(QStringLiteral("labPatientNumtag"));
        labPatientNumtag->setGeometry(QRect(150, 0, 141, 69));
        sizePolicy1.setHeightForWidth(labPatientNumtag->sizePolicy().hasHeightForWidth());
        labPatientNumtag->setSizePolicy(sizePolicy1);
        labPatientNumtag->setMinimumSize(QSize(100, 69));
        QPalette palette13;
        palette13.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QLinearGradient gradient45(0.464, 1, 0.482, 0);
        gradient45.setSpread(QGradient::PadSpread);
        gradient45.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient45.setColorAt(0.286364, QColor(33, 41, 62, 255));
        gradient45.setColorAt(0.381818, QColor(80, 82, 106, 255));
        QBrush brush54(gradient45);
        palette13.setBrush(QPalette::Active, QPalette::Button, brush54);
        QLinearGradient gradient46(0.464, 1, 0.482, 0);
        gradient46.setSpread(QGradient::PadSpread);
        gradient46.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient46.setColorAt(0.286364, QColor(33, 41, 62, 255));
        gradient46.setColorAt(0.381818, QColor(80, 82, 106, 255));
        QBrush brush55(gradient46);
        palette13.setBrush(QPalette::Active, QPalette::Base, brush55);
        QLinearGradient gradient47(0.464, 1, 0.482, 0);
        gradient47.setSpread(QGradient::PadSpread);
        gradient47.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient47.setColorAt(0.286364, QColor(33, 41, 62, 255));
        gradient47.setColorAt(0.381818, QColor(80, 82, 106, 255));
        QBrush brush56(gradient47);
        palette13.setBrush(QPalette::Active, QPalette::Window, brush56);
        palette13.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        QLinearGradient gradient48(0.464, 1, 0.482, 0);
        gradient48.setSpread(QGradient::PadSpread);
        gradient48.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient48.setColorAt(0.286364, QColor(33, 41, 62, 255));
        gradient48.setColorAt(0.381818, QColor(80, 82, 106, 255));
        QBrush brush57(gradient48);
        palette13.setBrush(QPalette::Inactive, QPalette::Button, brush57);
        QLinearGradient gradient49(0.464, 1, 0.482, 0);
        gradient49.setSpread(QGradient::PadSpread);
        gradient49.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient49.setColorAt(0.286364, QColor(33, 41, 62, 255));
        gradient49.setColorAt(0.381818, QColor(80, 82, 106, 255));
        QBrush brush58(gradient49);
        palette13.setBrush(QPalette::Inactive, QPalette::Base, brush58);
        QLinearGradient gradient50(0.464, 1, 0.482, 0);
        gradient50.setSpread(QGradient::PadSpread);
        gradient50.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient50.setColorAt(0.286364, QColor(33, 41, 62, 255));
        gradient50.setColorAt(0.381818, QColor(80, 82, 106, 255));
        QBrush brush59(gradient50);
        palette13.setBrush(QPalette::Inactive, QPalette::Window, brush59);
        palette13.setBrush(QPalette::Disabled, QPalette::WindowText, brush);
        QLinearGradient gradient51(0.464, 1, 0.482, 0);
        gradient51.setSpread(QGradient::PadSpread);
        gradient51.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient51.setColorAt(0.286364, QColor(33, 41, 62, 255));
        gradient51.setColorAt(0.381818, QColor(80, 82, 106, 255));
        QBrush brush60(gradient51);
        palette13.setBrush(QPalette::Disabled, QPalette::Button, brush60);
        QLinearGradient gradient52(0.464, 1, 0.482, 0);
        gradient52.setSpread(QGradient::PadSpread);
        gradient52.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient52.setColorAt(0.286364, QColor(33, 41, 62, 255));
        gradient52.setColorAt(0.381818, QColor(80, 82, 106, 255));
        QBrush brush61(gradient52);
        palette13.setBrush(QPalette::Disabled, QPalette::Base, brush61);
        QLinearGradient gradient53(0.464, 1, 0.482, 0);
        gradient53.setSpread(QGradient::PadSpread);
        gradient53.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient53.setColorAt(0.286364, QColor(33, 41, 62, 255));
        gradient53.setColorAt(0.381818, QColor(80, 82, 106, 255));
        QBrush brush62(gradient53);
        palette13.setBrush(QPalette::Disabled, QPalette::Window, brush62);
        labPatientNumtag->setPalette(palette13);
        labPatientNumtag->setFont(font);
        labPatientType = new QLabel(groupBox);
        labPatientType->setObjectName(QStringLiteral("labPatientType"));
        labPatientType->setGeometry(QRect(899, 0, 141, 69));
        sizePolicy1.setHeightForWidth(labPatientType->sizePolicy().hasHeightForWidth());
        labPatientType->setSizePolicy(sizePolicy1);
        labPatientType->setMinimumSize(QSize(100, 69));
        QPalette palette14;
        palette14.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QLinearGradient gradient54(0.464, 1, 0.482, 0);
        gradient54.setSpread(QGradient::PadSpread);
        gradient54.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient54.setColorAt(0.286364, QColor(33, 41, 62, 255));
        gradient54.setColorAt(0.381818, QColor(80, 82, 106, 255));
        QBrush brush63(gradient54);
        palette14.setBrush(QPalette::Active, QPalette::Button, brush63);
        QLinearGradient gradient55(0.464, 1, 0.482, 0);
        gradient55.setSpread(QGradient::PadSpread);
        gradient55.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient55.setColorAt(0.286364, QColor(33, 41, 62, 255));
        gradient55.setColorAt(0.381818, QColor(80, 82, 106, 255));
        QBrush brush64(gradient55);
        palette14.setBrush(QPalette::Active, QPalette::Base, brush64);
        QLinearGradient gradient56(0.464, 1, 0.482, 0);
        gradient56.setSpread(QGradient::PadSpread);
        gradient56.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient56.setColorAt(0.286364, QColor(33, 41, 62, 255));
        gradient56.setColorAt(0.381818, QColor(80, 82, 106, 255));
        QBrush brush65(gradient56);
        palette14.setBrush(QPalette::Active, QPalette::Window, brush65);
        palette14.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        QLinearGradient gradient57(0.464, 1, 0.482, 0);
        gradient57.setSpread(QGradient::PadSpread);
        gradient57.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient57.setColorAt(0.286364, QColor(33, 41, 62, 255));
        gradient57.setColorAt(0.381818, QColor(80, 82, 106, 255));
        QBrush brush66(gradient57);
        palette14.setBrush(QPalette::Inactive, QPalette::Button, brush66);
        QLinearGradient gradient58(0.464, 1, 0.482, 0);
        gradient58.setSpread(QGradient::PadSpread);
        gradient58.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient58.setColorAt(0.286364, QColor(33, 41, 62, 255));
        gradient58.setColorAt(0.381818, QColor(80, 82, 106, 255));
        QBrush brush67(gradient58);
        palette14.setBrush(QPalette::Inactive, QPalette::Base, brush67);
        QLinearGradient gradient59(0.464, 1, 0.482, 0);
        gradient59.setSpread(QGradient::PadSpread);
        gradient59.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient59.setColorAt(0.286364, QColor(33, 41, 62, 255));
        gradient59.setColorAt(0.381818, QColor(80, 82, 106, 255));
        QBrush brush68(gradient59);
        palette14.setBrush(QPalette::Inactive, QPalette::Window, brush68);
        palette14.setBrush(QPalette::Disabled, QPalette::WindowText, brush);
        QLinearGradient gradient60(0.464, 1, 0.482, 0);
        gradient60.setSpread(QGradient::PadSpread);
        gradient60.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient60.setColorAt(0.286364, QColor(33, 41, 62, 255));
        gradient60.setColorAt(0.381818, QColor(80, 82, 106, 255));
        QBrush brush69(gradient60);
        palette14.setBrush(QPalette::Disabled, QPalette::Button, brush69);
        QLinearGradient gradient61(0.464, 1, 0.482, 0);
        gradient61.setSpread(QGradient::PadSpread);
        gradient61.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient61.setColorAt(0.286364, QColor(33, 41, 62, 255));
        gradient61.setColorAt(0.381818, QColor(80, 82, 106, 255));
        QBrush brush70(gradient61);
        palette14.setBrush(QPalette::Disabled, QPalette::Base, brush70);
        QLinearGradient gradient62(0.464, 1, 0.482, 0);
        gradient62.setSpread(QGradient::PadSpread);
        gradient62.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient62.setColorAt(0.286364, QColor(33, 41, 62, 255));
        gradient62.setColorAt(0.381818, QColor(80, 82, 106, 255));
        QBrush brush71(gradient62);
        palette14.setBrush(QPalette::Disabled, QPalette::Window, brush71);
        labPatientType->setPalette(palette14);
        labPatientType->setFont(font);
        frame = new QFrame(groupBox);
        frame->setObjectName(QStringLiteral("frame"));
        frame->setGeometry(QRect(10, 10, 112, 50));
        frame->setStyleSheet(QStringLiteral("border-image: url(:/rsc/images/logo.png);"));
        frame->setFrameShape(QFrame::StyledPanel);
        frame->setFrameShadow(QFrame::Raised);

        topLayout->addWidget(groupBox);

        verticalLayoutWidget->raise();
        verticalLayoutWidget_2->raise();
        layoutWidget->raise();

        retranslateUi(MainForm);

        QMetaObject::connectSlotsByName(MainForm);
    } // setupUi

    void retranslateUi(QWidget *MainForm)
    {
        MainForm->setWindowTitle(QApplication::translate("MainForm", "Form", 0));
        btnMonitor->setText(QApplication::translate("MainForm", "\344\270\273\347\225\214\351\235\242", 0));
        btnWave->setText(QApplication::translate("MainForm", "\345\277\203\347\224\265\345\233\276", 0));
        btnVisualChart->setText(QApplication::translate("MainForm", "\350\247\206\345\212\233\350\241\250", 0));
        btnColorChart->setText(QApplication::translate("MainForm", "\350\211\262\350\247\211\345\233\276", 0));
        btnSettings->setText(QApplication::translate("MainForm", "\350\256\276 \347\275\256", 0));
        btnprint->setText(QApplication::translate("MainForm", "\346\211\223 \345\215\260", 0));
        btnreset->setText(QApplication::translate("MainForm", "\351\207\215 \345\220\257", 0));
        groupBox->setTitle(QString());
        labTime->setText(QApplication::translate("MainForm", "2014-09-14 12:00:00", 0));
        labPatientNum->setText(QApplication::translate("MainForm", "--", 0));
        labPatientNametag->setText(QApplication::translate("MainForm", "\346\202\243\350\200\205\345\247\223\345\220\215:", 0));
        labPatientName->setText(QApplication::translate("MainForm", "--", 0));
        labPatientNumtag->setText(QApplication::translate("MainForm", "\346\202\243\350\200\205\347\274\226\345\217\267:", 0));
        labPatientType->setText(QApplication::translate("MainForm", "\346\210\220\344\272\272", 0));
    } // retranslateUi

};

namespace Ui {
    class MainForm: public Ui_MainForm {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINFORM_H
