/********************************************************************************
** Form generated from reading UI file 'monitorform.ui'
**
** Created by: Qt User Interface Compiler version 5.6.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MONITORFORM_H
#define UI_MONITORFORM_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QWidget>
#include "qwt_plot.h"

QT_BEGIN_NAMESPACE

class Ui_MonitorForm
{
public:
    QGroupBox *groupBox_6;
    QLabel *lab_DIAS;
    QLabel *lab_DBP;
    QLabel *lab_dbptop;
    QLabel *lab_dbplow;
    QLabel *lab_Maxdias;
    QLabel *lab_Mindias;
    QLabel *lab_DBP_2;
    QGroupBox *groupBox_3;
    QLabel *lab_TEMP;
    QLabel *lab_BT;
    QLabel *lab_bttop;
    QLabel *lab_btlow;
    QLabel *lab_Maxtemp;
    QLabel *lab_Mintemp;
    QLabel *label_6;
    QGroupBox *groupBox_5;
    QLabel *lab_MAP;
    QLabel *lab_AVER;
    QLabel *lab_maptop;
    QLabel *lab_maplow;
    QLabel *lab_Maxaver;
    QLabel *lab_Minaver;
    QLabel *lab_MAP_2;
    QGroupBox *groupBox_4;
    QLabel *lab_SYS;
    QLabel *lab_SBP;
    QLabel *lab_sbptop;
    QLabel *lab_sbplow;
    QLabel *lab_Maxsys;
    QLabel *lab_Minsys;
    QLabel *lab_SBP_2;
    QGroupBox *groupBox_7;
    QLabel *lab_BS;
    QLabel *lab_GLU;
    QLabel *lab_bstop;
    QLabel *lab_bslow;
    QLabel *lab_MaxGLU;
    QLabel *lab_MinGLU;
    QLabel *label_8;
    QGroupBox *groupBox_8;
    QPushButton *btnBPStart;
    QPushButton *btnPatientType;
    QwtPlot *qwtPlot_SPO2;
    QGroupBox *groupBox;
    QLabel *lab_Spo2Tag;
    QLabel *lab_spo2top;
    QLabel *lab_spo2low;
    QLabel *lab_Maxspo2;
    QLabel *lab_Minspo2;
    QLabel *lab_SPO2;
    QLabel *lab_Spo2Tag_2;
    QGroupBox *groupBox_2;
    QLabel *lab_PR;
    QLabel *lab_PRTag;
    QLabel *lab_prtop;
    QLabel *lab_prlow;
    QLabel *lab_Maxpr;
    QLabel *lab_Minpr;
    QLabel *lab_PRTag_2;

    void setupUi(QWidget *MonitorForm)
    {
        if (MonitorForm->objectName().isEmpty())
            MonitorForm->setObjectName(QStringLiteral("MonitorForm"));
        MonitorForm->resize(1366, 768);
        QPalette palette;
        QBrush brush(QColor(0, 0, 0, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QBrush brush1(QColor(255, 255, 255, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette.setBrush(QPalette::Active, QPalette::Light, brush1);
        palette.setBrush(QPalette::Active, QPalette::Midlight, brush1);
        QBrush brush2(QColor(127, 127, 127, 255));
        brush2.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Dark, brush2);
        QBrush brush3(QColor(170, 170, 170, 255));
        brush3.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Mid, brush3);
        palette.setBrush(QPalette::Active, QPalette::Text, brush);
        palette.setBrush(QPalette::Active, QPalette::BrightText, brush1);
        palette.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette.setBrush(QPalette::Active, QPalette::Window, brush);
        palette.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette.setBrush(QPalette::Active, QPalette::AlternateBase, brush1);
        QBrush brush4(QColor(255, 255, 220, 255));
        brush4.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::ToolTipBase, brush4);
        palette.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Light, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Midlight, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Dark, brush2);
        palette.setBrush(QPalette::Inactive, QPalette::Mid, brush3);
        palette.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette.setBrush(QPalette::Inactive, QPalette::BrightText, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush4);
        palette.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Light, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Midlight, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Dark, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::Mid, brush3);
        palette.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::BrightText, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::ButtonText, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette.setBrush(QPalette::Disabled, QPalette::Window, brush);
        palette.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        MonitorForm->setPalette(palette);
        groupBox_6 = new QGroupBox(MonitorForm);
        groupBox_6->setObjectName(QStringLiteral("groupBox_6"));
        groupBox_6->setGeometry(QRect(349, 91, 335, 288));
        QPalette palette1;
        palette1.setBrush(QPalette::Active, QPalette::WindowText, brush1);
        palette1.setBrush(QPalette::Active, QPalette::Dark, brush1);
        palette1.setBrush(QPalette::Active, QPalette::Mid, brush1);
        palette1.setBrush(QPalette::Active, QPalette::Text, brush1);
        palette1.setBrush(QPalette::Active, QPalette::ButtonText, brush1);
        palette1.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette1.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette1.setBrush(QPalette::Active, QPalette::Shadow, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::WindowText, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::Dark, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::Mid, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::Text, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::ButtonText, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::Shadow, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::Dark, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::Mid, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::Shadow, brush1);
        groupBox_6->setPalette(palette1);
        lab_DIAS = new QLabel(groupBox_6);
        lab_DIAS->setObjectName(QStringLiteral("lab_DIAS"));
        lab_DIAS->setGeometry(QRect(0, 61, 335, 141));
        QPalette palette2;
        QBrush brush5(QColor(178, 169, 135, 255));
        brush5.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::WindowText, brush5);
        palette2.setBrush(QPalette::Active, QPalette::Text, brush5);
        palette2.setBrush(QPalette::Inactive, QPalette::WindowText, brush5);
        palette2.setBrush(QPalette::Inactive, QPalette::Text, brush5);
        palette2.setBrush(QPalette::Disabled, QPalette::WindowText, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        lab_DIAS->setPalette(palette2);
        QFont font;
        font.setFamily(QStringLiteral("DejaVu Sans"));
        font.setPointSize(128);
        font.setBold(true);
        font.setWeight(75);
        lab_DIAS->setFont(font);
        lab_DIAS->setAlignment(Qt::AlignCenter);
        lab_DBP = new QLabel(groupBox_6);
        lab_DBP->setObjectName(QStringLiteral("lab_DBP"));
        lab_DBP->setGeometry(QRect(70, 1, 121, 41));
        QPalette palette3;
        palette3.setBrush(QPalette::Active, QPalette::WindowText, brush1);
        palette3.setBrush(QPalette::Inactive, QPalette::WindowText, brush1);
        palette3.setBrush(QPalette::Disabled, QPalette::WindowText, brush);
        lab_DBP->setPalette(palette3);
        QFont font1;
        font1.setFamily(QString::fromUtf8("\346\226\207\346\263\211\351\251\233\347\255\211\345\257\254\345\276\256\347\261\263\351\273\221"));
        font1.setPointSize(24);
        font1.setBold(false);
        font1.setWeight(50);
        lab_DBP->setFont(font1);
        lab_dbptop = new QLabel(groupBox_6);
        lab_dbptop->setObjectName(QStringLiteral("lab_dbptop"));
        lab_dbptop->setGeometry(QRect(20, 221, 61, 41));
        QPalette palette4;
        palette4.setBrush(QPalette::Active, QPalette::WindowText, brush1);
        palette4.setBrush(QPalette::Active, QPalette::Text, brush1);
        palette4.setBrush(QPalette::Inactive, QPalette::WindowText, brush1);
        palette4.setBrush(QPalette::Inactive, QPalette::Text, brush1);
        palette4.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette4.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        lab_dbptop->setPalette(palette4);
        QFont font2;
        font2.setFamily(QString::fromUtf8("\346\226\207\346\263\211\351\251\233\347\255\211\345\257\254\345\276\256\347\261\263\351\273\221"));
        font2.setPointSize(16);
        lab_dbptop->setFont(font2);
        lab_dbplow = new QLabel(groupBox_6);
        lab_dbplow->setObjectName(QStringLiteral("lab_dbplow"));
        lab_dbplow->setGeometry(QRect(230, 221, 51, 41));
        QPalette palette5;
        palette5.setBrush(QPalette::Active, QPalette::WindowText, brush1);
        palette5.setBrush(QPalette::Active, QPalette::Text, brush1);
        palette5.setBrush(QPalette::Inactive, QPalette::WindowText, brush1);
        palette5.setBrush(QPalette::Inactive, QPalette::Text, brush1);
        palette5.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette5.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        lab_dbplow->setPalette(palette5);
        lab_dbplow->setFont(font2);
        lab_Maxdias = new QLabel(groupBox_6);
        lab_Maxdias->setObjectName(QStringLiteral("lab_Maxdias"));
        lab_Maxdias->setGeometry(QRect(70, 221, 61, 41));
        QPalette palette6;
        palette6.setBrush(QPalette::Active, QPalette::WindowText, brush1);
        palette6.setBrush(QPalette::Active, QPalette::Text, brush1);
        palette6.setBrush(QPalette::Inactive, QPalette::WindowText, brush1);
        palette6.setBrush(QPalette::Inactive, QPalette::Text, brush1);
        palette6.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette6.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        lab_Maxdias->setPalette(palette6);
        lab_Maxdias->setFont(font2);
        lab_Mindias = new QLabel(groupBox_6);
        lab_Mindias->setObjectName(QStringLiteral("lab_Mindias"));
        lab_Mindias->setGeometry(QRect(280, 221, 61, 41));
        QPalette palette7;
        palette7.setBrush(QPalette::Active, QPalette::WindowText, brush1);
        palette7.setBrush(QPalette::Active, QPalette::Text, brush1);
        palette7.setBrush(QPalette::Inactive, QPalette::WindowText, brush1);
        palette7.setBrush(QPalette::Inactive, QPalette::Text, brush1);
        palette7.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette7.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        lab_Mindias->setPalette(palette7);
        lab_Mindias->setFont(font2);
        lab_DBP_2 = new QLabel(groupBox_6);
        lab_DBP_2->setObjectName(QStringLiteral("lab_DBP_2"));
        lab_DBP_2->setGeometry(QRect(210, 1, 111, 41));
        QPalette palette8;
        palette8.setBrush(QPalette::Active, QPalette::WindowText, brush1);
        palette8.setBrush(QPalette::Inactive, QPalette::WindowText, brush1);
        palette8.setBrush(QPalette::Disabled, QPalette::WindowText, brush);
        lab_DBP_2->setPalette(palette8);
        lab_DBP_2->setFont(font1);
        groupBox_3 = new QGroupBox(MonitorForm);
        groupBox_3->setObjectName(QStringLiteral("groupBox_3"));
        groupBox_3->setGeometry(QRect(349, 381, 335, 288));
        QPalette palette9;
        palette9.setBrush(QPalette::Active, QPalette::WindowText, brush1);
        palette9.setBrush(QPalette::Active, QPalette::Dark, brush1);
        palette9.setBrush(QPalette::Active, QPalette::Mid, brush1);
        palette9.setBrush(QPalette::Active, QPalette::Text, brush1);
        palette9.setBrush(QPalette::Active, QPalette::ButtonText, brush1);
        palette9.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette9.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette9.setBrush(QPalette::Active, QPalette::Shadow, brush1);
        palette9.setBrush(QPalette::Inactive, QPalette::WindowText, brush1);
        palette9.setBrush(QPalette::Inactive, QPalette::Dark, brush1);
        palette9.setBrush(QPalette::Inactive, QPalette::Mid, brush1);
        palette9.setBrush(QPalette::Inactive, QPalette::Text, brush1);
        palette9.setBrush(QPalette::Inactive, QPalette::ButtonText, brush1);
        palette9.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette9.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette9.setBrush(QPalette::Inactive, QPalette::Shadow, brush1);
        palette9.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette9.setBrush(QPalette::Disabled, QPalette::Dark, brush1);
        palette9.setBrush(QPalette::Disabled, QPalette::Mid, brush1);
        palette9.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        palette9.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        palette9.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette9.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette9.setBrush(QPalette::Disabled, QPalette::Shadow, brush1);
        groupBox_3->setPalette(palette9);
        lab_TEMP = new QLabel(groupBox_3);
        lab_TEMP->setObjectName(QStringLiteral("lab_TEMP"));
        lab_TEMP->setGeometry(QRect(0, 61, 335, 141));
        QPalette palette10;
        palette10.setBrush(QPalette::Active, QPalette::WindowText, brush1);
        palette10.setBrush(QPalette::Inactive, QPalette::WindowText, brush1);
        palette10.setBrush(QPalette::Disabled, QPalette::WindowText, brush);
        lab_TEMP->setPalette(palette10);
        QFont font3;
        font3.setFamily(QStringLiteral("DejaVu Serif"));
        font3.setPointSize(128);
        font3.setBold(true);
        font3.setWeight(75);
        lab_TEMP->setFont(font3);
        lab_TEMP->setAlignment(Qt::AlignCenter);
        lab_BT = new QLabel(groupBox_3);
        lab_BT->setObjectName(QStringLiteral("lab_BT"));
        lab_BT->setGeometry(QRect(70, 1, 111, 41));
        QPalette palette11;
        palette11.setBrush(QPalette::Active, QPalette::WindowText, brush1);
        palette11.setBrush(QPalette::Inactive, QPalette::WindowText, brush1);
        palette11.setBrush(QPalette::Disabled, QPalette::WindowText, brush);
        lab_BT->setPalette(palette11);
        lab_BT->setFont(font1);
        lab_bttop = new QLabel(groupBox_3);
        lab_bttop->setObjectName(QStringLiteral("lab_bttop"));
        lab_bttop->setGeometry(QRect(20, 221, 61, 41));
        QPalette palette12;
        palette12.setBrush(QPalette::Active, QPalette::WindowText, brush1);
        palette12.setBrush(QPalette::Active, QPalette::Text, brush1);
        palette12.setBrush(QPalette::Inactive, QPalette::WindowText, brush1);
        palette12.setBrush(QPalette::Inactive, QPalette::Text, brush1);
        palette12.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette12.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        lab_bttop->setPalette(palette12);
        lab_bttop->setFont(font2);
        lab_btlow = new QLabel(groupBox_3);
        lab_btlow->setObjectName(QStringLiteral("lab_btlow"));
        lab_btlow->setGeometry(QRect(230, 221, 51, 41));
        QPalette palette13;
        palette13.setBrush(QPalette::Active, QPalette::WindowText, brush1);
        palette13.setBrush(QPalette::Active, QPalette::Text, brush1);
        palette13.setBrush(QPalette::Inactive, QPalette::WindowText, brush1);
        palette13.setBrush(QPalette::Inactive, QPalette::Text, brush1);
        palette13.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette13.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        lab_btlow->setPalette(palette13);
        lab_btlow->setFont(font2);
        lab_Maxtemp = new QLabel(groupBox_3);
        lab_Maxtemp->setObjectName(QStringLiteral("lab_Maxtemp"));
        lab_Maxtemp->setGeometry(QRect(70, 221, 61, 41));
        QPalette palette14;
        palette14.setBrush(QPalette::Active, QPalette::WindowText, brush1);
        palette14.setBrush(QPalette::Active, QPalette::Text, brush1);
        palette14.setBrush(QPalette::Inactive, QPalette::WindowText, brush1);
        palette14.setBrush(QPalette::Inactive, QPalette::Text, brush1);
        palette14.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette14.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        lab_Maxtemp->setPalette(palette14);
        lab_Maxtemp->setFont(font2);
        lab_Mintemp = new QLabel(groupBox_3);
        lab_Mintemp->setObjectName(QStringLiteral("lab_Mintemp"));
        lab_Mintemp->setGeometry(QRect(280, 221, 61, 41));
        QPalette palette15;
        palette15.setBrush(QPalette::Active, QPalette::WindowText, brush1);
        palette15.setBrush(QPalette::Active, QPalette::Text, brush1);
        palette15.setBrush(QPalette::Inactive, QPalette::WindowText, brush1);
        palette15.setBrush(QPalette::Inactive, QPalette::Text, brush1);
        palette15.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette15.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        lab_Mintemp->setPalette(palette15);
        lab_Mintemp->setFont(font2);
        label_6 = new QLabel(groupBox_3);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(170, 1, 101, 41));
        QPalette palette16;
        palette16.setBrush(QPalette::Active, QPalette::WindowText, brush1);
        palette16.setBrush(QPalette::Inactive, QPalette::WindowText, brush1);
        palette16.setBrush(QPalette::Disabled, QPalette::WindowText, brush);
        label_6->setPalette(palette16);
        label_6->setFont(font1);
        groupBox_5 = new QGroupBox(MonitorForm);
        groupBox_5->setObjectName(QStringLiteral("groupBox_5"));
        groupBox_5->setGeometry(QRect(682, 91, 335, 288));
        QPalette palette17;
        palette17.setBrush(QPalette::Active, QPalette::WindowText, brush1);
        palette17.setBrush(QPalette::Active, QPalette::Dark, brush1);
        palette17.setBrush(QPalette::Active, QPalette::Mid, brush1);
        palette17.setBrush(QPalette::Active, QPalette::Text, brush1);
        palette17.setBrush(QPalette::Active, QPalette::ButtonText, brush1);
        palette17.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette17.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette17.setBrush(QPalette::Active, QPalette::Shadow, brush1);
        palette17.setBrush(QPalette::Inactive, QPalette::WindowText, brush1);
        palette17.setBrush(QPalette::Inactive, QPalette::Dark, brush1);
        palette17.setBrush(QPalette::Inactive, QPalette::Mid, brush1);
        palette17.setBrush(QPalette::Inactive, QPalette::Text, brush1);
        palette17.setBrush(QPalette::Inactive, QPalette::ButtonText, brush1);
        palette17.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette17.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette17.setBrush(QPalette::Inactive, QPalette::Shadow, brush1);
        palette17.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette17.setBrush(QPalette::Disabled, QPalette::Dark, brush1);
        palette17.setBrush(QPalette::Disabled, QPalette::Mid, brush1);
        palette17.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        palette17.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        palette17.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette17.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette17.setBrush(QPalette::Disabled, QPalette::Shadow, brush1);
        groupBox_5->setPalette(palette17);
        lab_MAP = new QLabel(groupBox_5);
        lab_MAP->setObjectName(QStringLiteral("lab_MAP"));
        lab_MAP->setGeometry(QRect(70, 1, 121, 41));
        QPalette palette18;
        palette18.setBrush(QPalette::Active, QPalette::WindowText, brush1);
        palette18.setBrush(QPalette::Inactive, QPalette::WindowText, brush1);
        palette18.setBrush(QPalette::Disabled, QPalette::WindowText, brush);
        lab_MAP->setPalette(palette18);
        lab_MAP->setFont(font1);
        lab_AVER = new QLabel(groupBox_5);
        lab_AVER->setObjectName(QStringLiteral("lab_AVER"));
        lab_AVER->setGeometry(QRect(0, 61, 335, 141));
        QPalette palette19;
        palette19.setBrush(QPalette::Active, QPalette::WindowText, brush5);
        palette19.setBrush(QPalette::Active, QPalette::Text, brush5);
        palette19.setBrush(QPalette::Inactive, QPalette::WindowText, brush5);
        palette19.setBrush(QPalette::Inactive, QPalette::Text, brush5);
        palette19.setBrush(QPalette::Disabled, QPalette::WindowText, brush);
        palette19.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        lab_AVER->setPalette(palette19);
        lab_AVER->setFont(font);
        lab_AVER->setAlignment(Qt::AlignCenter);
        lab_maptop = new QLabel(groupBox_5);
        lab_maptop->setObjectName(QStringLiteral("lab_maptop"));
        lab_maptop->setGeometry(QRect(20, 221, 61, 41));
        QPalette palette20;
        palette20.setBrush(QPalette::Active, QPalette::WindowText, brush1);
        palette20.setBrush(QPalette::Active, QPalette::Text, brush1);
        palette20.setBrush(QPalette::Inactive, QPalette::WindowText, brush1);
        palette20.setBrush(QPalette::Inactive, QPalette::Text, brush1);
        palette20.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette20.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        lab_maptop->setPalette(palette20);
        lab_maptop->setFont(font2);
        lab_maplow = new QLabel(groupBox_5);
        lab_maplow->setObjectName(QStringLiteral("lab_maplow"));
        lab_maplow->setGeometry(QRect(230, 221, 51, 41));
        QPalette palette21;
        palette21.setBrush(QPalette::Active, QPalette::WindowText, brush1);
        palette21.setBrush(QPalette::Active, QPalette::Text, brush1);
        palette21.setBrush(QPalette::Inactive, QPalette::WindowText, brush1);
        palette21.setBrush(QPalette::Inactive, QPalette::Text, brush1);
        palette21.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette21.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        lab_maplow->setPalette(palette21);
        lab_maplow->setFont(font2);
        lab_Maxaver = new QLabel(groupBox_5);
        lab_Maxaver->setObjectName(QStringLiteral("lab_Maxaver"));
        lab_Maxaver->setGeometry(QRect(70, 221, 61, 41));
        QPalette palette22;
        palette22.setBrush(QPalette::Active, QPalette::WindowText, brush1);
        palette22.setBrush(QPalette::Active, QPalette::Text, brush1);
        palette22.setBrush(QPalette::Inactive, QPalette::WindowText, brush1);
        palette22.setBrush(QPalette::Inactive, QPalette::Text, brush1);
        palette22.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette22.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        lab_Maxaver->setPalette(palette22);
        lab_Maxaver->setFont(font2);
        lab_Minaver = new QLabel(groupBox_5);
        lab_Minaver->setObjectName(QStringLiteral("lab_Minaver"));
        lab_Minaver->setGeometry(QRect(280, 221, 61, 41));
        QPalette palette23;
        palette23.setBrush(QPalette::Active, QPalette::WindowText, brush1);
        palette23.setBrush(QPalette::Active, QPalette::Text, brush1);
        palette23.setBrush(QPalette::Inactive, QPalette::WindowText, brush1);
        palette23.setBrush(QPalette::Inactive, QPalette::Text, brush1);
        palette23.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette23.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        lab_Minaver->setPalette(palette23);
        lab_Minaver->setFont(font2);
        lab_MAP_2 = new QLabel(groupBox_5);
        lab_MAP_2->setObjectName(QStringLiteral("lab_MAP_2"));
        lab_MAP_2->setGeometry(QRect(210, 1, 131, 41));
        QPalette palette24;
        palette24.setBrush(QPalette::Active, QPalette::WindowText, brush1);
        palette24.setBrush(QPalette::Inactive, QPalette::WindowText, brush1);
        palette24.setBrush(QPalette::Disabled, QPalette::WindowText, brush);
        lab_MAP_2->setPalette(palette24);
        lab_MAP_2->setFont(font1);
        groupBox_4 = new QGroupBox(MonitorForm);
        groupBox_4->setObjectName(QStringLiteral("groupBox_4"));
        groupBox_4->setGeometry(QRect(13, 91, 335, 288));
        QPalette palette25;
        palette25.setBrush(QPalette::Active, QPalette::WindowText, brush1);
        palette25.setBrush(QPalette::Active, QPalette::Dark, brush1);
        palette25.setBrush(QPalette::Active, QPalette::Mid, brush1);
        palette25.setBrush(QPalette::Active, QPalette::Text, brush1);
        palette25.setBrush(QPalette::Active, QPalette::ButtonText, brush1);
        palette25.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette25.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette25.setBrush(QPalette::Active, QPalette::Shadow, brush1);
        palette25.setBrush(QPalette::Inactive, QPalette::WindowText, brush1);
        palette25.setBrush(QPalette::Inactive, QPalette::Dark, brush1);
        palette25.setBrush(QPalette::Inactive, QPalette::Mid, brush1);
        palette25.setBrush(QPalette::Inactive, QPalette::Text, brush1);
        palette25.setBrush(QPalette::Inactive, QPalette::ButtonText, brush1);
        palette25.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette25.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette25.setBrush(QPalette::Inactive, QPalette::Shadow, brush1);
        palette25.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette25.setBrush(QPalette::Disabled, QPalette::Dark, brush1);
        palette25.setBrush(QPalette::Disabled, QPalette::Mid, brush1);
        palette25.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        palette25.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        palette25.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette25.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette25.setBrush(QPalette::Disabled, QPalette::Shadow, brush1);
        groupBox_4->setPalette(palette25);
        lab_SYS = new QLabel(groupBox_4);
        lab_SYS->setObjectName(QStringLiteral("lab_SYS"));
        lab_SYS->setGeometry(QRect(-10, 61, 335, 141));
        QPalette palette26;
        palette26.setBrush(QPalette::Active, QPalette::WindowText, brush5);
        palette26.setBrush(QPalette::Active, QPalette::Text, brush5);
        palette26.setBrush(QPalette::Inactive, QPalette::WindowText, brush5);
        palette26.setBrush(QPalette::Inactive, QPalette::Text, brush5);
        palette26.setBrush(QPalette::Disabled, QPalette::WindowText, brush);
        palette26.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        lab_SYS->setPalette(palette26);
        lab_SYS->setFont(font);
        lab_SYS->setAlignment(Qt::AlignCenter);
        lab_SBP = new QLabel(groupBox_4);
        lab_SBP->setObjectName(QStringLiteral("lab_SBP"));
        lab_SBP->setGeometry(QRect(80, 1, 131, 41));
        QPalette palette27;
        palette27.setBrush(QPalette::Active, QPalette::WindowText, brush1);
        palette27.setBrush(QPalette::Inactive, QPalette::WindowText, brush1);
        palette27.setBrush(QPalette::Disabled, QPalette::WindowText, brush);
        lab_SBP->setPalette(palette27);
        lab_SBP->setFont(font1);
        lab_sbptop = new QLabel(groupBox_4);
        lab_sbptop->setObjectName(QStringLiteral("lab_sbptop"));
        lab_sbptop->setGeometry(QRect(20, 221, 61, 41));
        QPalette palette28;
        palette28.setBrush(QPalette::Active, QPalette::WindowText, brush1);
        palette28.setBrush(QPalette::Active, QPalette::Text, brush1);
        palette28.setBrush(QPalette::Inactive, QPalette::WindowText, brush1);
        palette28.setBrush(QPalette::Inactive, QPalette::Text, brush1);
        palette28.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette28.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        lab_sbptop->setPalette(palette28);
        lab_sbptop->setFont(font2);
        lab_sbplow = new QLabel(groupBox_4);
        lab_sbplow->setObjectName(QStringLiteral("lab_sbplow"));
        lab_sbplow->setGeometry(QRect(230, 221, 51, 41));
        QPalette palette29;
        palette29.setBrush(QPalette::Active, QPalette::WindowText, brush1);
        palette29.setBrush(QPalette::Active, QPalette::Text, brush1);
        palette29.setBrush(QPalette::Inactive, QPalette::WindowText, brush1);
        palette29.setBrush(QPalette::Inactive, QPalette::Text, brush1);
        palette29.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette29.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        lab_sbplow->setPalette(palette29);
        lab_sbplow->setFont(font2);
        lab_Maxsys = new QLabel(groupBox_4);
        lab_Maxsys->setObjectName(QStringLiteral("lab_Maxsys"));
        lab_Maxsys->setGeometry(QRect(70, 221, 61, 41));
        QPalette palette30;
        palette30.setBrush(QPalette::Active, QPalette::WindowText, brush1);
        palette30.setBrush(QPalette::Active, QPalette::Text, brush1);
        palette30.setBrush(QPalette::Inactive, QPalette::WindowText, brush1);
        palette30.setBrush(QPalette::Inactive, QPalette::Text, brush1);
        palette30.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette30.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        lab_Maxsys->setPalette(palette30);
        lab_Maxsys->setFont(font2);
        lab_Minsys = new QLabel(groupBox_4);
        lab_Minsys->setObjectName(QStringLiteral("lab_Minsys"));
        lab_Minsys->setGeometry(QRect(280, 221, 61, 41));
        QPalette palette31;
        palette31.setBrush(QPalette::Active, QPalette::WindowText, brush1);
        palette31.setBrush(QPalette::Active, QPalette::Text, brush1);
        palette31.setBrush(QPalette::Inactive, QPalette::WindowText, brush1);
        palette31.setBrush(QPalette::Inactive, QPalette::Text, brush1);
        palette31.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette31.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        lab_Minsys->setPalette(palette31);
        lab_Minsys->setFont(font2);
        lab_SBP_2 = new QLabel(groupBox_4);
        lab_SBP_2->setObjectName(QStringLiteral("lab_SBP_2"));
        lab_SBP_2->setGeometry(QRect(210, 1, 131, 41));
        QPalette palette32;
        palette32.setBrush(QPalette::Active, QPalette::WindowText, brush1);
        palette32.setBrush(QPalette::Inactive, QPalette::WindowText, brush1);
        palette32.setBrush(QPalette::Disabled, QPalette::WindowText, brush);
        lab_SBP_2->setPalette(palette32);
        lab_SBP_2->setFont(font1);
        groupBox_7 = new QGroupBox(MonitorForm);
        groupBox_7->setObjectName(QStringLiteral("groupBox_7"));
        groupBox_7->setGeometry(QRect(13, 381, 335, 288));
        QPalette palette33;
        palette33.setBrush(QPalette::Active, QPalette::WindowText, brush1);
        palette33.setBrush(QPalette::Active, QPalette::Dark, brush1);
        palette33.setBrush(QPalette::Active, QPalette::Mid, brush1);
        palette33.setBrush(QPalette::Active, QPalette::Text, brush1);
        palette33.setBrush(QPalette::Active, QPalette::ButtonText, brush1);
        palette33.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette33.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette33.setBrush(QPalette::Active, QPalette::Shadow, brush1);
        palette33.setBrush(QPalette::Inactive, QPalette::WindowText, brush1);
        palette33.setBrush(QPalette::Inactive, QPalette::Dark, brush1);
        palette33.setBrush(QPalette::Inactive, QPalette::Mid, brush1);
        palette33.setBrush(QPalette::Inactive, QPalette::Text, brush1);
        palette33.setBrush(QPalette::Inactive, QPalette::ButtonText, brush1);
        palette33.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette33.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette33.setBrush(QPalette::Inactive, QPalette::Shadow, brush1);
        palette33.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette33.setBrush(QPalette::Disabled, QPalette::Dark, brush1);
        palette33.setBrush(QPalette::Disabled, QPalette::Mid, brush1);
        palette33.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        palette33.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        palette33.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette33.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette33.setBrush(QPalette::Disabled, QPalette::Shadow, brush1);
        groupBox_7->setPalette(palette33);
        lab_BS = new QLabel(groupBox_7);
        lab_BS->setObjectName(QStringLiteral("lab_BS"));
        lab_BS->setGeometry(QRect(70, 1, 91, 41));
        QPalette palette34;
        palette34.setBrush(QPalette::Active, QPalette::WindowText, brush1);
        palette34.setBrush(QPalette::Inactive, QPalette::WindowText, brush1);
        palette34.setBrush(QPalette::Disabled, QPalette::WindowText, brush);
        lab_BS->setPalette(palette34);
        lab_BS->setFont(font1);
        lab_GLU = new QLabel(groupBox_7);
        lab_GLU->setObjectName(QStringLiteral("lab_GLU"));
        lab_GLU->setGeometry(QRect(0, 61, 335, 141));
        QPalette palette35;
        QBrush brush6(QColor(149, 185, 221, 255));
        brush6.setStyle(Qt::SolidPattern);
        palette35.setBrush(QPalette::Active, QPalette::WindowText, brush6);
        palette35.setBrush(QPalette::Inactive, QPalette::WindowText, brush6);
        palette35.setBrush(QPalette::Disabled, QPalette::WindowText, brush);
        lab_GLU->setPalette(palette35);
        lab_GLU->setFont(font3);
        lab_GLU->setAlignment(Qt::AlignCenter);
        lab_bstop = new QLabel(groupBox_7);
        lab_bstop->setObjectName(QStringLiteral("lab_bstop"));
        lab_bstop->setGeometry(QRect(20, 221, 61, 41));
        QPalette palette36;
        palette36.setBrush(QPalette::Active, QPalette::WindowText, brush1);
        palette36.setBrush(QPalette::Active, QPalette::Text, brush1);
        palette36.setBrush(QPalette::Inactive, QPalette::WindowText, brush1);
        palette36.setBrush(QPalette::Inactive, QPalette::Text, brush1);
        palette36.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette36.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        lab_bstop->setPalette(palette36);
        lab_bstop->setFont(font2);
        lab_bslow = new QLabel(groupBox_7);
        lab_bslow->setObjectName(QStringLiteral("lab_bslow"));
        lab_bslow->setGeometry(QRect(230, 221, 51, 41));
        QPalette palette37;
        palette37.setBrush(QPalette::Active, QPalette::WindowText, brush1);
        palette37.setBrush(QPalette::Active, QPalette::Text, brush1);
        palette37.setBrush(QPalette::Inactive, QPalette::WindowText, brush1);
        palette37.setBrush(QPalette::Inactive, QPalette::Text, brush1);
        palette37.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette37.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        lab_bslow->setPalette(palette37);
        lab_bslow->setFont(font2);
        lab_MaxGLU = new QLabel(groupBox_7);
        lab_MaxGLU->setObjectName(QStringLiteral("lab_MaxGLU"));
        lab_MaxGLU->setGeometry(QRect(70, 221, 61, 41));
        QPalette palette38;
        palette38.setBrush(QPalette::Active, QPalette::WindowText, brush1);
        palette38.setBrush(QPalette::Active, QPalette::Text, brush1);
        palette38.setBrush(QPalette::Inactive, QPalette::WindowText, brush1);
        palette38.setBrush(QPalette::Inactive, QPalette::Text, brush1);
        palette38.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette38.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        lab_MaxGLU->setPalette(palette38);
        lab_MaxGLU->setFont(font2);
        lab_MinGLU = new QLabel(groupBox_7);
        lab_MinGLU->setObjectName(QStringLiteral("lab_MinGLU"));
        lab_MinGLU->setGeometry(QRect(280, 221, 61, 41));
        QPalette palette39;
        palette39.setBrush(QPalette::Active, QPalette::WindowText, brush1);
        palette39.setBrush(QPalette::Active, QPalette::Text, brush1);
        palette39.setBrush(QPalette::Inactive, QPalette::WindowText, brush1);
        palette39.setBrush(QPalette::Inactive, QPalette::Text, brush1);
        palette39.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette39.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        lab_MinGLU->setPalette(palette39);
        lab_MinGLU->setFont(font2);
        label_8 = new QLabel(groupBox_7);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(170, 1, 151, 41));
        QPalette palette40;
        palette40.setBrush(QPalette::Active, QPalette::WindowText, brush1);
        palette40.setBrush(QPalette::Inactive, QPalette::WindowText, brush1);
        palette40.setBrush(QPalette::Disabled, QPalette::WindowText, brush);
        label_8->setPalette(palette40);
        label_8->setFont(font1);
        groupBox_8 = new QGroupBox(MonitorForm);
        groupBox_8->setObjectName(QStringLiteral("groupBox_8"));
        groupBox_8->setGeometry(QRect(1018, 381, 335, 288));
        QPalette palette41;
        palette41.setBrush(QPalette::Active, QPalette::WindowText, brush1);
        palette41.setBrush(QPalette::Active, QPalette::Dark, brush1);
        palette41.setBrush(QPalette::Active, QPalette::Mid, brush1);
        palette41.setBrush(QPalette::Active, QPalette::Text, brush1);
        palette41.setBrush(QPalette::Active, QPalette::ButtonText, brush1);
        palette41.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette41.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette41.setBrush(QPalette::Active, QPalette::Shadow, brush1);
        palette41.setBrush(QPalette::Inactive, QPalette::WindowText, brush1);
        palette41.setBrush(QPalette::Inactive, QPalette::Dark, brush1);
        palette41.setBrush(QPalette::Inactive, QPalette::Mid, brush1);
        palette41.setBrush(QPalette::Inactive, QPalette::Text, brush1);
        palette41.setBrush(QPalette::Inactive, QPalette::ButtonText, brush1);
        palette41.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette41.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette41.setBrush(QPalette::Inactive, QPalette::Shadow, brush1);
        palette41.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette41.setBrush(QPalette::Disabled, QPalette::Dark, brush1);
        palette41.setBrush(QPalette::Disabled, QPalette::Mid, brush1);
        palette41.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        palette41.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        palette41.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette41.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette41.setBrush(QPalette::Disabled, QPalette::Shadow, brush1);
        groupBox_8->setPalette(palette41);
        btnBPStart = new QPushButton(groupBox_8);
        btnBPStart->setObjectName(QStringLiteral("btnBPStart"));
        btnBPStart->setGeometry(QRect(180, 210, 141, 61));
        QSizePolicy sizePolicy(QSizePolicy::Fixed, QSizePolicy::Fixed);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(btnBPStart->sizePolicy().hasHeightForWidth());
        btnBPStart->setSizePolicy(sizePolicy);
        btnBPStart->setMinimumSize(QSize(100, 50));
        QPalette palette42;
        palette42.setBrush(QPalette::Active, QPalette::WindowText, brush1);
        QBrush brush7(QColor(66, 71, 82, 255));
        brush7.setStyle(Qt::SolidPattern);
        palette42.setBrush(QPalette::Active, QPalette::Button, brush7);
        QBrush brush8(QColor(191, 191, 191, 255));
        brush8.setStyle(Qt::SolidPattern);
        palette42.setBrush(QPalette::Active, QPalette::Light, brush8);
        QBrush brush9(QColor(159, 159, 159, 255));
        brush9.setStyle(Qt::SolidPattern);
        palette42.setBrush(QPalette::Active, QPalette::Midlight, brush9);
        QBrush brush10(QColor(63, 63, 63, 255));
        brush10.setStyle(Qt::SolidPattern);
        palette42.setBrush(QPalette::Active, QPalette::Dark, brush10);
        QBrush brush11(QColor(84, 84, 84, 255));
        brush11.setStyle(Qt::SolidPattern);
        palette42.setBrush(QPalette::Active, QPalette::Mid, brush11);
        palette42.setBrush(QPalette::Active, QPalette::Text, brush1);
        palette42.setBrush(QPalette::Active, QPalette::BrightText, brush1);
        palette42.setBrush(QPalette::Active, QPalette::ButtonText, brush1);
        palette42.setBrush(QPalette::Active, QPalette::Base, brush);
        palette42.setBrush(QPalette::Active, QPalette::Window, brush2);
        palette42.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette42.setBrush(QPalette::Active, QPalette::AlternateBase, brush10);
        palette42.setBrush(QPalette::Active, QPalette::ToolTipBase, brush4);
        palette42.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette42.setBrush(QPalette::Inactive, QPalette::WindowText, brush1);
        palette42.setBrush(QPalette::Inactive, QPalette::Button, brush7);
        palette42.setBrush(QPalette::Inactive, QPalette::Light, brush8);
        palette42.setBrush(QPalette::Inactive, QPalette::Midlight, brush9);
        palette42.setBrush(QPalette::Inactive, QPalette::Dark, brush10);
        palette42.setBrush(QPalette::Inactive, QPalette::Mid, brush11);
        palette42.setBrush(QPalette::Inactive, QPalette::Text, brush1);
        palette42.setBrush(QPalette::Inactive, QPalette::BrightText, brush1);
        palette42.setBrush(QPalette::Inactive, QPalette::ButtonText, brush1);
        palette42.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette42.setBrush(QPalette::Inactive, QPalette::Window, brush2);
        palette42.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette42.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush10);
        palette42.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush4);
        palette42.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette42.setBrush(QPalette::Disabled, QPalette::WindowText, brush10);
        palette42.setBrush(QPalette::Disabled, QPalette::Button, brush7);
        palette42.setBrush(QPalette::Disabled, QPalette::Light, brush8);
        palette42.setBrush(QPalette::Disabled, QPalette::Midlight, brush9);
        palette42.setBrush(QPalette::Disabled, QPalette::Dark, brush10);
        palette42.setBrush(QPalette::Disabled, QPalette::Mid, brush11);
        palette42.setBrush(QPalette::Disabled, QPalette::Text, brush10);
        palette42.setBrush(QPalette::Disabled, QPalette::BrightText, brush1);
        palette42.setBrush(QPalette::Disabled, QPalette::ButtonText, brush10);
        palette42.setBrush(QPalette::Disabled, QPalette::Base, brush2);
        palette42.setBrush(QPalette::Disabled, QPalette::Window, brush2);
        palette42.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette42.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush2);
        palette42.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush4);
        palette42.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        btnBPStart->setPalette(palette42);
        QFont font4;
        font4.setFamily(QString::fromUtf8("\346\226\207\346\263\211\351\251\233\347\255\211\345\257\254\345\276\256\347\261\263\351\273\221"));
        font4.setPointSize(20);
        font4.setBold(false);
        font4.setWeight(50);
        btnBPStart->setFont(font4);
        btnBPStart->setFocusPolicy(Qt::NoFocus);
        btnBPStart->setStyleSheet(QStringLiteral("border-image: url(:/rsc/images/btnpressure.png);"));
        btnBPStart->setFlat(true);
        btnPatientType = new QPushButton(groupBox_8);
        btnPatientType->setObjectName(QStringLiteral("btnPatientType"));
        btnPatientType->setGeometry(QRect(20, 211, 141, 61));
        sizePolicy.setHeightForWidth(btnPatientType->sizePolicy().hasHeightForWidth());
        btnPatientType->setSizePolicy(sizePolicy);
        btnPatientType->setMinimumSize(QSize(100, 50));
        QPalette palette43;
        palette43.setBrush(QPalette::Active, QPalette::WindowText, brush1);
        palette43.setBrush(QPalette::Active, QPalette::Button, brush7);
        palette43.setBrush(QPalette::Active, QPalette::Light, brush8);
        palette43.setBrush(QPalette::Active, QPalette::Midlight, brush9);
        palette43.setBrush(QPalette::Active, QPalette::Dark, brush);
        palette43.setBrush(QPalette::Active, QPalette::Mid, brush11);
        palette43.setBrush(QPalette::Active, QPalette::Text, brush1);
        palette43.setBrush(QPalette::Active, QPalette::BrightText, brush1);
        QBrush brush12(QColor(255, 85, 0, 255));
        brush12.setStyle(Qt::SolidPattern);
        palette43.setBrush(QPalette::Active, QPalette::ButtonText, brush12);
        palette43.setBrush(QPalette::Active, QPalette::Base, brush);
        palette43.setBrush(QPalette::Active, QPalette::Window, brush2);
        palette43.setBrush(QPalette::Active, QPalette::Shadow, brush2);
        palette43.setBrush(QPalette::Active, QPalette::AlternateBase, brush10);
        palette43.setBrush(QPalette::Active, QPalette::ToolTipBase, brush4);
        palette43.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette43.setBrush(QPalette::Inactive, QPalette::WindowText, brush1);
        palette43.setBrush(QPalette::Inactive, QPalette::Button, brush7);
        palette43.setBrush(QPalette::Inactive, QPalette::Light, brush8);
        palette43.setBrush(QPalette::Inactive, QPalette::Midlight, brush9);
        palette43.setBrush(QPalette::Inactive, QPalette::Dark, brush);
        palette43.setBrush(QPalette::Inactive, QPalette::Mid, brush11);
        palette43.setBrush(QPalette::Inactive, QPalette::Text, brush1);
        palette43.setBrush(QPalette::Inactive, QPalette::BrightText, brush1);
        palette43.setBrush(QPalette::Inactive, QPalette::ButtonText, brush12);
        palette43.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette43.setBrush(QPalette::Inactive, QPalette::Window, brush2);
        palette43.setBrush(QPalette::Inactive, QPalette::Shadow, brush2);
        palette43.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush10);
        palette43.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush4);
        palette43.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette43.setBrush(QPalette::Disabled, QPalette::WindowText, brush);
        palette43.setBrush(QPalette::Disabled, QPalette::Button, brush7);
        palette43.setBrush(QPalette::Disabled, QPalette::Light, brush8);
        palette43.setBrush(QPalette::Disabled, QPalette::Midlight, brush9);
        palette43.setBrush(QPalette::Disabled, QPalette::Dark, brush);
        palette43.setBrush(QPalette::Disabled, QPalette::Mid, brush11);
        palette43.setBrush(QPalette::Disabled, QPalette::Text, brush);
        palette43.setBrush(QPalette::Disabled, QPalette::BrightText, brush1);
        palette43.setBrush(QPalette::Disabled, QPalette::ButtonText, brush);
        palette43.setBrush(QPalette::Disabled, QPalette::Base, brush2);
        palette43.setBrush(QPalette::Disabled, QPalette::Window, brush2);
        palette43.setBrush(QPalette::Disabled, QPalette::Shadow, brush2);
        palette43.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush2);
        palette43.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush4);
        palette43.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        btnPatientType->setPalette(palette43);
        btnPatientType->setFont(font4);
        btnPatientType->setFocusPolicy(Qt::NoFocus);
        btnPatientType->setLayoutDirection(Qt::LeftToRight);
        btnPatientType->setStyleSheet(QLatin1String("border-image: url(:/rsc/images/btnadult.png);\n"
""));
        btnPatientType->setFlat(true);
        qwtPlot_SPO2 = new QwtPlot(groupBox_8);
        qwtPlot_SPO2->setObjectName(QStringLiteral("qwtPlot_SPO2"));
        qwtPlot_SPO2->setGeometry(QRect(-2, -10, 330, 201));
        QPalette palette44;
        palette44.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette44.setBrush(QPalette::Active, QPalette::Light, brush);
        palette44.setBrush(QPalette::Active, QPalette::Midlight, brush);
        palette44.setBrush(QPalette::Active, QPalette::Dark, brush2);
        palette44.setBrush(QPalette::Active, QPalette::Text, brush1);
        palette44.setBrush(QPalette::Active, QPalette::ButtonText, brush1);
        palette44.setBrush(QPalette::Active, QPalette::Base, brush1);
        QBrush brush13(QColor(13, 17, 25, 255));
        brush13.setStyle(Qt::SolidPattern);
        palette44.setBrush(QPalette::Active, QPalette::Window, brush13);
        palette44.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette44.setBrush(QPalette::Inactive, QPalette::Light, brush);
        palette44.setBrush(QPalette::Inactive, QPalette::Midlight, brush);
        palette44.setBrush(QPalette::Inactive, QPalette::Dark, brush2);
        palette44.setBrush(QPalette::Inactive, QPalette::Text, brush1);
        palette44.setBrush(QPalette::Inactive, QPalette::ButtonText, brush1);
        palette44.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette44.setBrush(QPalette::Inactive, QPalette::Window, brush13);
        palette44.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette44.setBrush(QPalette::Disabled, QPalette::Light, brush);
        palette44.setBrush(QPalette::Disabled, QPalette::Midlight, brush);
        palette44.setBrush(QPalette::Disabled, QPalette::Dark, brush2);
        palette44.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        palette44.setBrush(QPalette::Disabled, QPalette::ButtonText, brush2);
        palette44.setBrush(QPalette::Disabled, QPalette::Base, brush13);
        palette44.setBrush(QPalette::Disabled, QPalette::Window, brush13);
        qwtPlot_SPO2->setPalette(palette44);
        qwtPlot_SPO2->setAutoFillBackground(false);
        groupBox = new QGroupBox(MonitorForm);
        groupBox->setObjectName(QStringLiteral("groupBox"));
        groupBox->setEnabled(true);
        groupBox->setGeometry(QRect(682, 381, 335, 288));
        QPalette palette45;
        palette45.setBrush(QPalette::Active, QPalette::WindowText, brush1);
        palette45.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette45.setBrush(QPalette::Active, QPalette::Light, brush1);
        palette45.setBrush(QPalette::Active, QPalette::Midlight, brush1);
        palette45.setBrush(QPalette::Active, QPalette::Dark, brush1);
        palette45.setBrush(QPalette::Active, QPalette::Mid, brush1);
        palette45.setBrush(QPalette::Active, QPalette::Text, brush1);
        palette45.setBrush(QPalette::Active, QPalette::BrightText, brush1);
        palette45.setBrush(QPalette::Active, QPalette::ButtonText, brush1);
        palette45.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette45.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette45.setBrush(QPalette::Active, QPalette::Shadow, brush1);
        palette45.setBrush(QPalette::Active, QPalette::AlternateBase, brush1);
        palette45.setBrush(QPalette::Active, QPalette::ToolTipBase, brush4);
        palette45.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette45.setBrush(QPalette::Inactive, QPalette::WindowText, brush1);
        palette45.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette45.setBrush(QPalette::Inactive, QPalette::Light, brush1);
        palette45.setBrush(QPalette::Inactive, QPalette::Midlight, brush1);
        palette45.setBrush(QPalette::Inactive, QPalette::Dark, brush1);
        palette45.setBrush(QPalette::Inactive, QPalette::Mid, brush1);
        palette45.setBrush(QPalette::Inactive, QPalette::Text, brush1);
        palette45.setBrush(QPalette::Inactive, QPalette::BrightText, brush1);
        palette45.setBrush(QPalette::Inactive, QPalette::ButtonText, brush1);
        palette45.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette45.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette45.setBrush(QPalette::Inactive, QPalette::Shadow, brush1);
        palette45.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush1);
        palette45.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush4);
        palette45.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette45.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette45.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette45.setBrush(QPalette::Disabled, QPalette::Light, brush1);
        palette45.setBrush(QPalette::Disabled, QPalette::Midlight, brush1);
        palette45.setBrush(QPalette::Disabled, QPalette::Dark, brush1);
        palette45.setBrush(QPalette::Disabled, QPalette::Mid, brush1);
        palette45.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        palette45.setBrush(QPalette::Disabled, QPalette::BrightText, brush1);
        palette45.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        palette45.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette45.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette45.setBrush(QPalette::Disabled, QPalette::Shadow, brush1);
        palette45.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette45.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush4);
        palette45.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        groupBox->setPalette(palette45);
        QFont font5;
        font5.setFamily(QString::fromUtf8("\346\226\207\346\263\211\351\251\233\345\276\256\347\261\263\351\273\221"));
        groupBox->setFont(font5);
        lab_Spo2Tag = new QLabel(groupBox);
        lab_Spo2Tag->setObjectName(QStringLiteral("lab_Spo2Tag"));
        lab_Spo2Tag->setGeometry(QRect(60, 1, 181, 41));
        QPalette palette46;
        palette46.setBrush(QPalette::Active, QPalette::WindowText, brush1);
        palette46.setBrush(QPalette::Inactive, QPalette::WindowText, brush1);
        palette46.setBrush(QPalette::Disabled, QPalette::WindowText, brush);
        lab_Spo2Tag->setPalette(palette46);
        QFont font6;
        font6.setFamily(QString::fromUtf8("\346\226\207\346\263\211\351\251\233\347\255\211\345\257\254\345\276\256\347\261\263\351\273\221"));
        font6.setPointSize(24);
        lab_Spo2Tag->setFont(font6);
        lab_spo2top = new QLabel(groupBox);
        lab_spo2top->setObjectName(QStringLiteral("lab_spo2top"));
        lab_spo2top->setGeometry(QRect(20, 221, 61, 41));
        QPalette palette47;
        palette47.setBrush(QPalette::Active, QPalette::WindowText, brush1);
        palette47.setBrush(QPalette::Active, QPalette::Text, brush1);
        palette47.setBrush(QPalette::Inactive, QPalette::WindowText, brush1);
        palette47.setBrush(QPalette::Inactive, QPalette::Text, brush1);
        palette47.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette47.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        lab_spo2top->setPalette(palette47);
        lab_spo2top->setFont(font2);
        lab_spo2low = new QLabel(groupBox);
        lab_spo2low->setObjectName(QStringLiteral("lab_spo2low"));
        lab_spo2low->setGeometry(QRect(230, 221, 51, 41));
        QPalette palette48;
        palette48.setBrush(QPalette::Active, QPalette::WindowText, brush1);
        palette48.setBrush(QPalette::Active, QPalette::Text, brush1);
        palette48.setBrush(QPalette::Inactive, QPalette::WindowText, brush1);
        palette48.setBrush(QPalette::Inactive, QPalette::Text, brush1);
        palette48.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette48.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        lab_spo2low->setPalette(palette48);
        lab_spo2low->setFont(font2);
        lab_Maxspo2 = new QLabel(groupBox);
        lab_Maxspo2->setObjectName(QStringLiteral("lab_Maxspo2"));
        lab_Maxspo2->setGeometry(QRect(70, 221, 61, 41));
        QPalette palette49;
        palette49.setBrush(QPalette::Active, QPalette::WindowText, brush1);
        palette49.setBrush(QPalette::Active, QPalette::Text, brush1);
        palette49.setBrush(QPalette::Inactive, QPalette::WindowText, brush1);
        palette49.setBrush(QPalette::Inactive, QPalette::Text, brush1);
        palette49.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette49.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        lab_Maxspo2->setPalette(palette49);
        lab_Maxspo2->setFont(font2);
        lab_Minspo2 = new QLabel(groupBox);
        lab_Minspo2->setObjectName(QStringLiteral("lab_Minspo2"));
        lab_Minspo2->setGeometry(QRect(280, 221, 61, 41));
        QPalette palette50;
        palette50.setBrush(QPalette::Active, QPalette::WindowText, brush1);
        palette50.setBrush(QPalette::Active, QPalette::Text, brush1);
        palette50.setBrush(QPalette::Inactive, QPalette::WindowText, brush1);
        palette50.setBrush(QPalette::Inactive, QPalette::Text, brush1);
        palette50.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette50.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        lab_Minspo2->setPalette(palette50);
        lab_Minspo2->setFont(font2);
        lab_SPO2 = new QLabel(groupBox);
        lab_SPO2->setObjectName(QStringLiteral("lab_SPO2"));
        lab_SPO2->setGeometry(QRect(0, 61, 335, 141));
        QPalette palette51;
        QBrush brush14(QColor(139, 199, 31, 255));
        brush14.setStyle(Qt::SolidPattern);
        palette51.setBrush(QPalette::Active, QPalette::WindowText, brush14);
        palette51.setBrush(QPalette::Inactive, QPalette::WindowText, brush14);
        palette51.setBrush(QPalette::Disabled, QPalette::WindowText, brush);
        lab_SPO2->setPalette(palette51);
        lab_SPO2->setFont(font);
        lab_SPO2->setAlignment(Qt::AlignCenter);
        lab_Spo2Tag_2 = new QLabel(groupBox);
        lab_Spo2Tag_2->setObjectName(QStringLiteral("lab_Spo2Tag_2"));
        lab_Spo2Tag_2->setGeometry(QRect(240, 1, 61, 41));
        QPalette palette52;
        palette52.setBrush(QPalette::Active, QPalette::WindowText, brush1);
        palette52.setBrush(QPalette::Inactive, QPalette::WindowText, brush1);
        palette52.setBrush(QPalette::Disabled, QPalette::WindowText, brush);
        lab_Spo2Tag_2->setPalette(palette52);
        lab_Spo2Tag_2->setFont(font6);
        groupBox_2 = new QGroupBox(MonitorForm);
        groupBox_2->setObjectName(QStringLiteral("groupBox_2"));
        groupBox_2->setGeometry(QRect(1018, 91, 335, 288));
        QPalette palette53;
        palette53.setBrush(QPalette::Active, QPalette::WindowText, brush1);
        palette53.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette53.setBrush(QPalette::Active, QPalette::Light, brush1);
        palette53.setBrush(QPalette::Active, QPalette::Midlight, brush1);
        palette53.setBrush(QPalette::Active, QPalette::Dark, brush1);
        palette53.setBrush(QPalette::Active, QPalette::Mid, brush1);
        palette53.setBrush(QPalette::Active, QPalette::Text, brush1);
        palette53.setBrush(QPalette::Active, QPalette::BrightText, brush1);
        palette53.setBrush(QPalette::Active, QPalette::ButtonText, brush1);
        palette53.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette53.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette53.setBrush(QPalette::Active, QPalette::Shadow, brush1);
        palette53.setBrush(QPalette::Active, QPalette::AlternateBase, brush1);
        palette53.setBrush(QPalette::Active, QPalette::ToolTipBase, brush4);
        palette53.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette53.setBrush(QPalette::Inactive, QPalette::WindowText, brush1);
        palette53.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette53.setBrush(QPalette::Inactive, QPalette::Light, brush1);
        palette53.setBrush(QPalette::Inactive, QPalette::Midlight, brush1);
        palette53.setBrush(QPalette::Inactive, QPalette::Dark, brush1);
        palette53.setBrush(QPalette::Inactive, QPalette::Mid, brush1);
        palette53.setBrush(QPalette::Inactive, QPalette::Text, brush1);
        palette53.setBrush(QPalette::Inactive, QPalette::BrightText, brush1);
        palette53.setBrush(QPalette::Inactive, QPalette::ButtonText, brush1);
        palette53.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette53.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette53.setBrush(QPalette::Inactive, QPalette::Shadow, brush1);
        palette53.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush1);
        palette53.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush4);
        palette53.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette53.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette53.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette53.setBrush(QPalette::Disabled, QPalette::Light, brush1);
        palette53.setBrush(QPalette::Disabled, QPalette::Midlight, brush1);
        palette53.setBrush(QPalette::Disabled, QPalette::Dark, brush1);
        palette53.setBrush(QPalette::Disabled, QPalette::Mid, brush1);
        palette53.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        palette53.setBrush(QPalette::Disabled, QPalette::BrightText, brush1);
        palette53.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        palette53.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette53.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette53.setBrush(QPalette::Disabled, QPalette::Shadow, brush1);
        palette53.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette53.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush4);
        palette53.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        groupBox_2->setPalette(palette53);
        QFont font7;
        font7.setFamily(QString::fromUtf8("\346\226\207\346\263\211\351\251\233\345\276\256\347\261\263\351\273\221"));
        font7.setPointSize(20);
        groupBox_2->setFont(font7);
        lab_PR = new QLabel(groupBox_2);
        lab_PR->setObjectName(QStringLiteral("lab_PR"));
        lab_PR->setGeometry(QRect(0, 61, 335, 151));
        QPalette palette54;
        palette54.setBrush(QPalette::Active, QPalette::WindowText, brush14);
        palette54.setBrush(QPalette::Inactive, QPalette::WindowText, brush14);
        palette54.setBrush(QPalette::Disabled, QPalette::WindowText, brush);
        lab_PR->setPalette(palette54);
        QFont font8;
        font8.setFamily(QStringLiteral("DejaVu Serif"));
        font8.setPointSize(128);
        font8.setBold(true);
        font8.setItalic(false);
        font8.setWeight(75);
        lab_PR->setFont(font8);
        lab_PR->setAlignment(Qt::AlignCenter);
        lab_PRTag = new QLabel(groupBox_2);
        lab_PRTag->setObjectName(QStringLiteral("lab_PRTag"));
        lab_PRTag->setGeometry(QRect(70, 1, 91, 41));
        QPalette palette55;
        palette55.setBrush(QPalette::Active, QPalette::WindowText, brush1);
        palette55.setBrush(QPalette::Inactive, QPalette::WindowText, brush1);
        palette55.setBrush(QPalette::Disabled, QPalette::WindowText, brush);
        lab_PRTag->setPalette(palette55);
        lab_PRTag->setFont(font6);
        lab_prtop = new QLabel(groupBox_2);
        lab_prtop->setObjectName(QStringLiteral("lab_prtop"));
        lab_prtop->setGeometry(QRect(20, 221, 61, 41));
        QPalette palette56;
        palette56.setBrush(QPalette::Active, QPalette::WindowText, brush1);
        palette56.setBrush(QPalette::Active, QPalette::Text, brush1);
        palette56.setBrush(QPalette::Inactive, QPalette::WindowText, brush1);
        palette56.setBrush(QPalette::Inactive, QPalette::Text, brush1);
        palette56.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette56.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        lab_prtop->setPalette(palette56);
        lab_prtop->setFont(font2);
        lab_prlow = new QLabel(groupBox_2);
        lab_prlow->setObjectName(QStringLiteral("lab_prlow"));
        lab_prlow->setGeometry(QRect(230, 221, 51, 41));
        QPalette palette57;
        palette57.setBrush(QPalette::Active, QPalette::WindowText, brush1);
        palette57.setBrush(QPalette::Active, QPalette::Text, brush1);
        palette57.setBrush(QPalette::Inactive, QPalette::WindowText, brush1);
        palette57.setBrush(QPalette::Inactive, QPalette::Text, brush1);
        palette57.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette57.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        lab_prlow->setPalette(palette57);
        lab_prlow->setFont(font2);
        lab_Maxpr = new QLabel(groupBox_2);
        lab_Maxpr->setObjectName(QStringLiteral("lab_Maxpr"));
        lab_Maxpr->setGeometry(QRect(70, 221, 61, 41));
        QPalette palette58;
        palette58.setBrush(QPalette::Active, QPalette::WindowText, brush1);
        palette58.setBrush(QPalette::Active, QPalette::Text, brush1);
        palette58.setBrush(QPalette::Inactive, QPalette::WindowText, brush1);
        palette58.setBrush(QPalette::Inactive, QPalette::Text, brush1);
        palette58.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette58.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        lab_Maxpr->setPalette(palette58);
        lab_Maxpr->setFont(font2);
        lab_Minpr = new QLabel(groupBox_2);
        lab_Minpr->setObjectName(QStringLiteral("lab_Minpr"));
        lab_Minpr->setGeometry(QRect(280, 221, 61, 41));
        QPalette palette59;
        palette59.setBrush(QPalette::Active, QPalette::WindowText, brush1);
        palette59.setBrush(QPalette::Active, QPalette::Text, brush1);
        palette59.setBrush(QPalette::Inactive, QPalette::WindowText, brush1);
        palette59.setBrush(QPalette::Inactive, QPalette::Text, brush1);
        palette59.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette59.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        lab_Minpr->setPalette(palette59);
        lab_Minpr->setFont(font2);
        lab_PRTag_2 = new QLabel(groupBox_2);
        lab_PRTag_2->setObjectName(QStringLiteral("lab_PRTag_2"));
        lab_PRTag_2->setGeometry(QRect(180, 1, 111, 41));
        QPalette palette60;
        palette60.setBrush(QPalette::Active, QPalette::WindowText, brush1);
        palette60.setBrush(QPalette::Inactive, QPalette::WindowText, brush1);
        palette60.setBrush(QPalette::Disabled, QPalette::WindowText, brush);
        lab_PRTag_2->setPalette(palette60);
        lab_PRTag_2->setFont(font6);

        retranslateUi(MonitorForm);

        QMetaObject::connectSlotsByName(MonitorForm);
    } // setupUi

    void retranslateUi(QWidget *MonitorForm)
    {
        MonitorForm->setWindowTitle(QApplication::translate("MonitorForm", "Form", 0));
        groupBox_6->setTitle(QString());
        lab_DIAS->setText(QApplication::translate("MonitorForm", "--", 0));
        lab_DBP->setText(QApplication::translate("MonitorForm", "\350\210\222\345\274\240\345\216\213", 0));
        lab_dbptop->setText(QApplication::translate("MonitorForm", "\344\270\212\351\231\220:", 0));
        lab_dbplow->setText(QApplication::translate("MonitorForm", "\344\270\213\351\231\220:", 0));
        lab_Maxdias->setText(QApplication::translate("MonitorForm", "80", 0));
        lab_Mindias->setText(QApplication::translate("MonitorForm", "50", 0));
        lab_DBP_2->setText(QApplication::translate("MonitorForm", "mmHg", 0));
        groupBox_3->setTitle(QString());
        lab_TEMP->setText(QApplication::translate("MonitorForm", "--", 0));
        lab_BT->setText(QApplication::translate("MonitorForm", "\344\275\223\346\270\251", 0));
        lab_bttop->setText(QApplication::translate("MonitorForm", "\344\270\212\351\231\220:", 0));
        lab_btlow->setText(QApplication::translate("MonitorForm", "\344\270\213\351\231\220:", 0));
        lab_Maxtemp->setText(QApplication::translate("MonitorForm", "40.0", 0));
        lab_Mintemp->setText(QApplication::translate("MonitorForm", "20.0", 0));
        label_6->setText(QApplication::translate("MonitorForm", "\302\260C", 0));
        groupBox_5->setTitle(QString());
        lab_MAP->setText(QApplication::translate("MonitorForm", "\345\271\263\345\235\207\345\216\213", 0));
        lab_AVER->setText(QApplication::translate("MonitorForm", "--", 0));
        lab_maptop->setText(QApplication::translate("MonitorForm", "\344\270\212\351\231\220:", 0));
        lab_maplow->setText(QApplication::translate("MonitorForm", "\344\270\213\351\231\220:", 0));
        lab_Maxaver->setText(QApplication::translate("MonitorForm", "100", 0));
        lab_Minaver->setText(QApplication::translate("MonitorForm", "50", 0));
        lab_MAP_2->setText(QApplication::translate("MonitorForm", "mmHg", 0));
        groupBox_4->setTitle(QString());
        lab_SYS->setText(QApplication::translate("MonitorForm", "--", 0));
        lab_SBP->setText(QApplication::translate("MonitorForm", "\346\224\266\347\274\251\345\216\213", 0));
        lab_sbptop->setText(QApplication::translate("MonitorForm", "\344\270\212\351\231\220:", 0));
        lab_sbplow->setText(QApplication::translate("MonitorForm", "\344\270\213\351\231\220:", 0));
        lab_Maxsys->setText(QApplication::translate("MonitorForm", "140", 0));
        lab_Minsys->setText(QApplication::translate("MonitorForm", "80", 0));
        lab_SBP_2->setText(QApplication::translate("MonitorForm", " mmHg", 0));
        groupBox_7->setTitle(QString());
        lab_BS->setText(QApplication::translate("MonitorForm", "\350\241\200\347\263\226", 0));
        lab_GLU->setText(QApplication::translate("MonitorForm", "--", 0));
        lab_bstop->setText(QApplication::translate("MonitorForm", "\344\270\212\351\231\220:", 0));
        lab_bslow->setText(QApplication::translate("MonitorForm", "\344\270\213\351\231\220:", 0));
        lab_MaxGLU->setText(QApplication::translate("MonitorForm", "27.2", 0));
        lab_MinGLU->setText(QApplication::translate("MonitorForm", "2.2", 0));
        label_8->setText(QApplication::translate("MonitorForm", "mmol/dl", 0));
        groupBox_8->setTitle(QString());
        btnBPStart->setText(QApplication::translate("MonitorForm", "\350\241\200\345\216\213\346\265\213\351\207\217", 0));
        btnPatientType->setText(QApplication::translate("MonitorForm", "\346\210\220\344\272\272/\345\204\277\347\253\245", 0));
        groupBox->setTitle(QString());
        lab_Spo2Tag->setText(QApplication::translate("MonitorForm", "\350\241\200\346\260\247\351\245\261\345\222\214\345\272\246", 0));
        lab_spo2top->setText(QApplication::translate("MonitorForm", "\344\270\212\351\231\220:", 0));
        lab_spo2low->setText(QApplication::translate("MonitorForm", "\344\270\213\351\231\220:", 0));
        lab_Maxspo2->setText(QApplication::translate("MonitorForm", "100", 0));
        lab_Minspo2->setText(QApplication::translate("MonitorForm", "50", 0));
        lab_SPO2->setText(QApplication::translate("MonitorForm", "--", 0));
        lab_Spo2Tag_2->setText(QApplication::translate("MonitorForm", "%", 0));
        groupBox_2->setTitle(QString());
        lab_PR->setText(QApplication::translate("MonitorForm", "--", 0));
        lab_PRTag->setText(QApplication::translate("MonitorForm", "\350\204\211\347\216\207", 0));
        lab_prtop->setText(QApplication::translate("MonitorForm", "\344\270\212\351\231\220:", 0));
        lab_prlow->setText(QApplication::translate("MonitorForm", "\344\270\213\351\231\220:", 0));
        lab_Maxpr->setText(QApplication::translate("MonitorForm", "100", 0));
        lab_Minpr->setText(QApplication::translate("MonitorForm", "50", 0));
        lab_PRTag_2->setText(QApplication::translate("MonitorForm", "BPM", 0));
    } // retranslateUi

};

namespace Ui {
    class MonitorForm: public Ui_MonitorForm {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MONITORFORM_H
