/********************************************************************************
** Form generated from reading UI file 'passworddialog.ui'
**
** Created by: Qt User Interface Compiler version 5.6.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_PASSWORDDIALOG_H
#define UI_PASSWORDDIALOG_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QDialog>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QPushButton>

QT_BEGIN_NAMESPACE

class Ui_PassWordDialog
{
public:
    QPushButton *btnOK;
    QPushButton *btn_Cancel;
    QGroupBox *grbbtn;
    QPushButton *btn2;
    QPushButton *btn0;
    QPushButton *btn3;
    QPushButton *btn1;
    QPushButton *btn6;
    QPushButton *btn5;
    QPushButton *btn8;
    QPushButton *btn7;
    QPushButton *btn4;
    QPushButton *btnDelete;
    QPushButton *btn9;
    QLabel *label_25;
    QLineEdit *Txtpassword;
    QLabel *labwarn;

    void setupUi(QDialog *PassWordDialog)
    {
        if (PassWordDialog->objectName().isEmpty())
            PassWordDialog->setObjectName(QStringLiteral("PassWordDialog"));
        PassWordDialog->resize(661, 421);
        QPalette palette;
        QBrush brush(QColor(255, 255, 255, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QBrush brush1(QColor(0, 0, 0, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette.setBrush(QPalette::Active, QPalette::Light, brush1);
        palette.setBrush(QPalette::Active, QPalette::Midlight, brush1);
        palette.setBrush(QPalette::Active, QPalette::Dark, brush1);
        palette.setBrush(QPalette::Active, QPalette::Mid, brush1);
        palette.setBrush(QPalette::Active, QPalette::Text, brush);
        palette.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette.setBrush(QPalette::Active, QPalette::Shadow, brush1);
        palette.setBrush(QPalette::Active, QPalette::AlternateBase, brush1);
        QBrush brush2(QColor(255, 255, 220, 255));
        brush2.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::ToolTipBase, brush2);
        palette.setBrush(QPalette::Active, QPalette::ToolTipText, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Light, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Midlight, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Dark, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Mid, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Shadow, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush2);
        palette.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Light, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Midlight, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Dark, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Mid, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Shadow, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush1);
        PassWordDialog->setPalette(palette);
        QFont font;
        font.setFamily(QString::fromUtf8("\346\226\207\346\263\211\351\251\233\347\255\211\345\257\254\345\276\256\347\261\263\351\273\221"));
        font.setPointSize(24);
        PassWordDialog->setFont(font);
        QIcon icon;
        icon.addFile(QStringLiteral(":/rsc/images/lock.png"), QSize(), QIcon::Normal, QIcon::Off);
        PassWordDialog->setWindowIcon(icon);
        btnOK = new QPushButton(PassWordDialog);
        btnOK->setObjectName(QStringLiteral("btnOK"));
        btnOK->setGeometry(QRect(356, 330, 141, 61));
        QPalette palette1;
        palette1.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QBrush brush3(QColor(165, 179, 205, 255));
        brush3.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Button, brush3);
        QBrush brush4(QColor(191, 191, 191, 255));
        brush4.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Light, brush4);
        QBrush brush5(QColor(159, 159, 159, 255));
        brush5.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Midlight, brush5);
        QBrush brush6(QColor(63, 63, 63, 255));
        brush6.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Dark, brush6);
        QBrush brush7(QColor(84, 84, 84, 255));
        brush7.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Mid, brush7);
        palette1.setBrush(QPalette::Active, QPalette::Text, brush);
        palette1.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette1.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette1.setBrush(QPalette::Active, QPalette::Base, brush3);
        palette1.setBrush(QPalette::Active, QPalette::Window, brush3);
        palette1.setBrush(QPalette::Active, QPalette::Shadow, brush1);
        palette1.setBrush(QPalette::Active, QPalette::AlternateBase, brush6);
        palette1.setBrush(QPalette::Active, QPalette::ToolTipBase, brush2);
        palette1.setBrush(QPalette::Active, QPalette::ToolTipText, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Button, brush3);
        palette1.setBrush(QPalette::Inactive, QPalette::Light, brush4);
        palette1.setBrush(QPalette::Inactive, QPalette::Midlight, brush5);
        palette1.setBrush(QPalette::Inactive, QPalette::Dark, brush6);
        palette1.setBrush(QPalette::Inactive, QPalette::Mid, brush7);
        palette1.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Base, brush3);
        palette1.setBrush(QPalette::Inactive, QPalette::Window, brush3);
        palette1.setBrush(QPalette::Inactive, QPalette::Shadow, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush6);
        palette1.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush2);
        palette1.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::WindowText, brush6);
        palette1.setBrush(QPalette::Disabled, QPalette::Button, brush3);
        palette1.setBrush(QPalette::Disabled, QPalette::Light, brush4);
        palette1.setBrush(QPalette::Disabled, QPalette::Midlight, brush5);
        palette1.setBrush(QPalette::Disabled, QPalette::Dark, brush6);
        palette1.setBrush(QPalette::Disabled, QPalette::Mid, brush7);
        palette1.setBrush(QPalette::Disabled, QPalette::Text, brush6);
        palette1.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::ButtonText, brush6);
        palette1.setBrush(QPalette::Disabled, QPalette::Base, brush3);
        palette1.setBrush(QPalette::Disabled, QPalette::Window, brush3);
        palette1.setBrush(QPalette::Disabled, QPalette::Shadow, brush1);
        QBrush brush8(QColor(127, 127, 127, 255));
        brush8.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush8);
        palette1.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush2);
        palette1.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush1);
        btnOK->setPalette(palette1);
        QFont font1;
        font1.setFamily(QString::fromUtf8("\346\226\207\346\263\211\351\251\233\347\255\211\345\257\254\345\276\256\347\261\263\351\273\221"));
        font1.setPointSize(24);
        font1.setBold(false);
        font1.setWeight(50);
        btnOK->setFont(font1);
        btnOK->setStyleSheet(QStringLiteral("background-color: rgb(165, 179, 205);"));
        btn_Cancel = new QPushButton(PassWordDialog);
        btn_Cancel->setObjectName(QStringLiteral("btn_Cancel"));
        btn_Cancel->setGeometry(QRect(500, 330, 131, 61));
        QPalette palette2;
        palette2.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette2.setBrush(QPalette::Active, QPalette::Button, brush3);
        palette2.setBrush(QPalette::Active, QPalette::Light, brush4);
        palette2.setBrush(QPalette::Active, QPalette::Midlight, brush5);
        palette2.setBrush(QPalette::Active, QPalette::Dark, brush6);
        palette2.setBrush(QPalette::Active, QPalette::Mid, brush7);
        palette2.setBrush(QPalette::Active, QPalette::Text, brush);
        palette2.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette2.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette2.setBrush(QPalette::Active, QPalette::Base, brush3);
        palette2.setBrush(QPalette::Active, QPalette::Window, brush3);
        palette2.setBrush(QPalette::Active, QPalette::Shadow, brush1);
        palette2.setBrush(QPalette::Active, QPalette::AlternateBase, brush6);
        palette2.setBrush(QPalette::Active, QPalette::ToolTipBase, brush2);
        palette2.setBrush(QPalette::Active, QPalette::ToolTipText, brush1);
        palette2.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Button, brush3);
        palette2.setBrush(QPalette::Inactive, QPalette::Light, brush4);
        palette2.setBrush(QPalette::Inactive, QPalette::Midlight, brush5);
        palette2.setBrush(QPalette::Inactive, QPalette::Dark, brush6);
        palette2.setBrush(QPalette::Inactive, QPalette::Mid, brush7);
        palette2.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Base, brush3);
        palette2.setBrush(QPalette::Inactive, QPalette::Window, brush3);
        palette2.setBrush(QPalette::Inactive, QPalette::Shadow, brush1);
        palette2.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush6);
        palette2.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush2);
        palette2.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush1);
        palette2.setBrush(QPalette::Disabled, QPalette::WindowText, brush6);
        palette2.setBrush(QPalette::Disabled, QPalette::Button, brush3);
        palette2.setBrush(QPalette::Disabled, QPalette::Light, brush4);
        palette2.setBrush(QPalette::Disabled, QPalette::Midlight, brush5);
        palette2.setBrush(QPalette::Disabled, QPalette::Dark, brush6);
        palette2.setBrush(QPalette::Disabled, QPalette::Mid, brush7);
        palette2.setBrush(QPalette::Disabled, QPalette::Text, brush6);
        palette2.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::ButtonText, brush6);
        palette2.setBrush(QPalette::Disabled, QPalette::Base, brush3);
        palette2.setBrush(QPalette::Disabled, QPalette::Window, brush3);
        palette2.setBrush(QPalette::Disabled, QPalette::Shadow, brush1);
        palette2.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush8);
        palette2.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush2);
        palette2.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush1);
        btn_Cancel->setPalette(palette2);
        btn_Cancel->setFont(font1);
        btn_Cancel->setStyleSheet(QStringLiteral("background-color: rgb(165, 179, 205);"));
        grbbtn = new QGroupBox(PassWordDialog);
        grbbtn->setObjectName(QStringLiteral("grbbtn"));
        grbbtn->setGeometry(QRect(130, 110, 421, 221));
        btn2 = new QPushButton(grbbtn);
        btn2->setObjectName(QStringLiteral("btn2"));
        btn2->setGeometry(QRect(120, 10, 90, 60));
        QPalette palette3;
        palette3.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QLinearGradient gradient(0.464, 1, 0.468, 0);
        gradient.setSpread(QGradient::PadSpread);
        gradient.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient.setColorAt(0.286364, QColor(23, 32, 42, 255));
        gradient.setColorAt(0.681818, QColor(79, 112, 123, 255));
        QBrush brush9(gradient);
        palette3.setBrush(QPalette::Active, QPalette::Button, brush9);
        palette3.setBrush(QPalette::Active, QPalette::Light, brush4);
        palette3.setBrush(QPalette::Active, QPalette::Midlight, brush5);
        palette3.setBrush(QPalette::Active, QPalette::Dark, brush6);
        palette3.setBrush(QPalette::Active, QPalette::Mid, brush7);
        palette3.setBrush(QPalette::Active, QPalette::Text, brush);
        palette3.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette3.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        QLinearGradient gradient1(0.464, 1, 0.468, 0);
        gradient1.setSpread(QGradient::PadSpread);
        gradient1.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient1.setColorAt(0.286364, QColor(23, 32, 42, 255));
        gradient1.setColorAt(0.681818, QColor(79, 112, 123, 255));
        QBrush brush10(gradient1);
        palette3.setBrush(QPalette::Active, QPalette::Base, brush10);
        QLinearGradient gradient2(0.464, 1, 0.468, 0);
        gradient2.setSpread(QGradient::PadSpread);
        gradient2.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient2.setColorAt(0.286364, QColor(23, 32, 42, 255));
        gradient2.setColorAt(0.681818, QColor(79, 112, 123, 255));
        QBrush brush11(gradient2);
        palette3.setBrush(QPalette::Active, QPalette::Window, brush11);
        palette3.setBrush(QPalette::Active, QPalette::Shadow, brush1);
        palette3.setBrush(QPalette::Active, QPalette::AlternateBase, brush6);
        palette3.setBrush(QPalette::Active, QPalette::ToolTipBase, brush2);
        palette3.setBrush(QPalette::Active, QPalette::ToolTipText, brush1);
        palette3.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        QLinearGradient gradient3(0.464, 1, 0.468, 0);
        gradient3.setSpread(QGradient::PadSpread);
        gradient3.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient3.setColorAt(0.286364, QColor(23, 32, 42, 255));
        gradient3.setColorAt(0.681818, QColor(79, 112, 123, 255));
        QBrush brush12(gradient3);
        palette3.setBrush(QPalette::Inactive, QPalette::Button, brush12);
        palette3.setBrush(QPalette::Inactive, QPalette::Light, brush4);
        palette3.setBrush(QPalette::Inactive, QPalette::Midlight, brush5);
        palette3.setBrush(QPalette::Inactive, QPalette::Dark, brush6);
        palette3.setBrush(QPalette::Inactive, QPalette::Mid, brush7);
        palette3.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        QLinearGradient gradient4(0.464, 1, 0.468, 0);
        gradient4.setSpread(QGradient::PadSpread);
        gradient4.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient4.setColorAt(0.286364, QColor(23, 32, 42, 255));
        gradient4.setColorAt(0.681818, QColor(79, 112, 123, 255));
        QBrush brush13(gradient4);
        palette3.setBrush(QPalette::Inactive, QPalette::Base, brush13);
        QLinearGradient gradient5(0.464, 1, 0.468, 0);
        gradient5.setSpread(QGradient::PadSpread);
        gradient5.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient5.setColorAt(0.286364, QColor(23, 32, 42, 255));
        gradient5.setColorAt(0.681818, QColor(79, 112, 123, 255));
        QBrush brush14(gradient5);
        palette3.setBrush(QPalette::Inactive, QPalette::Window, brush14);
        palette3.setBrush(QPalette::Inactive, QPalette::Shadow, brush1);
        palette3.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush6);
        palette3.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush2);
        palette3.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush1);
        palette3.setBrush(QPalette::Disabled, QPalette::WindowText, brush6);
        QLinearGradient gradient6(0.464, 1, 0.468, 0);
        gradient6.setSpread(QGradient::PadSpread);
        gradient6.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient6.setColorAt(0.286364, QColor(23, 32, 42, 255));
        gradient6.setColorAt(0.681818, QColor(79, 112, 123, 255));
        QBrush brush15(gradient6);
        palette3.setBrush(QPalette::Disabled, QPalette::Button, brush15);
        palette3.setBrush(QPalette::Disabled, QPalette::Light, brush4);
        palette3.setBrush(QPalette::Disabled, QPalette::Midlight, brush5);
        palette3.setBrush(QPalette::Disabled, QPalette::Dark, brush6);
        palette3.setBrush(QPalette::Disabled, QPalette::Mid, brush7);
        palette3.setBrush(QPalette::Disabled, QPalette::Text, brush6);
        palette3.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::ButtonText, brush6);
        QLinearGradient gradient7(0.464, 1, 0.468, 0);
        gradient7.setSpread(QGradient::PadSpread);
        gradient7.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient7.setColorAt(0.286364, QColor(23, 32, 42, 255));
        gradient7.setColorAt(0.681818, QColor(79, 112, 123, 255));
        QBrush brush16(gradient7);
        palette3.setBrush(QPalette::Disabled, QPalette::Base, brush16);
        QLinearGradient gradient8(0.464, 1, 0.468, 0);
        gradient8.setSpread(QGradient::PadSpread);
        gradient8.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient8.setColorAt(0.286364, QColor(23, 32, 42, 255));
        gradient8.setColorAt(0.681818, QColor(79, 112, 123, 255));
        QBrush brush17(gradient8);
        palette3.setBrush(QPalette::Disabled, QPalette::Window, brush17);
        palette3.setBrush(QPalette::Disabled, QPalette::Shadow, brush1);
        palette3.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush8);
        palette3.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush2);
        palette3.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush1);
        btn2->setPalette(palette3);
        QFont font2;
        font2.setFamily(QString::fromUtf8("\346\226\207\346\263\211\351\251\233\345\276\256\347\261\263\351\273\221"));
        font2.setPointSize(24);
        font2.setBold(false);
        font2.setWeight(50);
        btn2->setFont(font2);
        btn2->setFocusPolicy(Qt::NoFocus);
        btn2->setStyleSheet(QStringLiteral("background-color: qlineargradient(spread:pad, x1:0.464, y1:1, x2:0.468, y2:0, stop:0.286364 rgba(23, 32, 42, 255), stop:0.681818 rgba(79, 112, 123, 255));"));
        btn0 = new QPushButton(grbbtn);
        btn0->setObjectName(QStringLiteral("btn0"));
        btn0->setGeometry(QRect(120, 150, 90, 60));
        QPalette palette4;
        palette4.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QLinearGradient gradient9(0.464, 1, 0.468, 0);
        gradient9.setSpread(QGradient::PadSpread);
        gradient9.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient9.setColorAt(0.286364, QColor(23, 32, 42, 255));
        gradient9.setColorAt(0.681818, QColor(79, 112, 123, 255));
        QBrush brush18(gradient9);
        palette4.setBrush(QPalette::Active, QPalette::Button, brush18);
        palette4.setBrush(QPalette::Active, QPalette::Light, brush4);
        palette4.setBrush(QPalette::Active, QPalette::Midlight, brush5);
        palette4.setBrush(QPalette::Active, QPalette::Dark, brush6);
        palette4.setBrush(QPalette::Active, QPalette::Mid, brush7);
        palette4.setBrush(QPalette::Active, QPalette::Text, brush);
        palette4.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette4.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        QLinearGradient gradient10(0.464, 1, 0.468, 0);
        gradient10.setSpread(QGradient::PadSpread);
        gradient10.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient10.setColorAt(0.286364, QColor(23, 32, 42, 255));
        gradient10.setColorAt(0.681818, QColor(79, 112, 123, 255));
        QBrush brush19(gradient10);
        palette4.setBrush(QPalette::Active, QPalette::Base, brush19);
        QLinearGradient gradient11(0.464, 1, 0.468, 0);
        gradient11.setSpread(QGradient::PadSpread);
        gradient11.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient11.setColorAt(0.286364, QColor(23, 32, 42, 255));
        gradient11.setColorAt(0.681818, QColor(79, 112, 123, 255));
        QBrush brush20(gradient11);
        palette4.setBrush(QPalette::Active, QPalette::Window, brush20);
        palette4.setBrush(QPalette::Active, QPalette::Shadow, brush1);
        palette4.setBrush(QPalette::Active, QPalette::AlternateBase, brush6);
        palette4.setBrush(QPalette::Active, QPalette::ToolTipBase, brush2);
        palette4.setBrush(QPalette::Active, QPalette::ToolTipText, brush1);
        palette4.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        QLinearGradient gradient12(0.464, 1, 0.468, 0);
        gradient12.setSpread(QGradient::PadSpread);
        gradient12.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient12.setColorAt(0.286364, QColor(23, 32, 42, 255));
        gradient12.setColorAt(0.681818, QColor(79, 112, 123, 255));
        QBrush brush21(gradient12);
        palette4.setBrush(QPalette::Inactive, QPalette::Button, brush21);
        palette4.setBrush(QPalette::Inactive, QPalette::Light, brush4);
        palette4.setBrush(QPalette::Inactive, QPalette::Midlight, brush5);
        palette4.setBrush(QPalette::Inactive, QPalette::Dark, brush6);
        palette4.setBrush(QPalette::Inactive, QPalette::Mid, brush7);
        palette4.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        QLinearGradient gradient13(0.464, 1, 0.468, 0);
        gradient13.setSpread(QGradient::PadSpread);
        gradient13.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient13.setColorAt(0.286364, QColor(23, 32, 42, 255));
        gradient13.setColorAt(0.681818, QColor(79, 112, 123, 255));
        QBrush brush22(gradient13);
        palette4.setBrush(QPalette::Inactive, QPalette::Base, brush22);
        QLinearGradient gradient14(0.464, 1, 0.468, 0);
        gradient14.setSpread(QGradient::PadSpread);
        gradient14.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient14.setColorAt(0.286364, QColor(23, 32, 42, 255));
        gradient14.setColorAt(0.681818, QColor(79, 112, 123, 255));
        QBrush brush23(gradient14);
        palette4.setBrush(QPalette::Inactive, QPalette::Window, brush23);
        palette4.setBrush(QPalette::Inactive, QPalette::Shadow, brush1);
        palette4.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush6);
        palette4.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush2);
        palette4.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush1);
        palette4.setBrush(QPalette::Disabled, QPalette::WindowText, brush6);
        QLinearGradient gradient15(0.464, 1, 0.468, 0);
        gradient15.setSpread(QGradient::PadSpread);
        gradient15.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient15.setColorAt(0.286364, QColor(23, 32, 42, 255));
        gradient15.setColorAt(0.681818, QColor(79, 112, 123, 255));
        QBrush brush24(gradient15);
        palette4.setBrush(QPalette::Disabled, QPalette::Button, brush24);
        palette4.setBrush(QPalette::Disabled, QPalette::Light, brush4);
        palette4.setBrush(QPalette::Disabled, QPalette::Midlight, brush5);
        palette4.setBrush(QPalette::Disabled, QPalette::Dark, brush6);
        palette4.setBrush(QPalette::Disabled, QPalette::Mid, brush7);
        palette4.setBrush(QPalette::Disabled, QPalette::Text, brush6);
        palette4.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::ButtonText, brush6);
        QLinearGradient gradient16(0.464, 1, 0.468, 0);
        gradient16.setSpread(QGradient::PadSpread);
        gradient16.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient16.setColorAt(0.286364, QColor(23, 32, 42, 255));
        gradient16.setColorAt(0.681818, QColor(79, 112, 123, 255));
        QBrush brush25(gradient16);
        palette4.setBrush(QPalette::Disabled, QPalette::Base, brush25);
        QLinearGradient gradient17(0.464, 1, 0.468, 0);
        gradient17.setSpread(QGradient::PadSpread);
        gradient17.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient17.setColorAt(0.286364, QColor(23, 32, 42, 255));
        gradient17.setColorAt(0.681818, QColor(79, 112, 123, 255));
        QBrush brush26(gradient17);
        palette4.setBrush(QPalette::Disabled, QPalette::Window, brush26);
        palette4.setBrush(QPalette::Disabled, QPalette::Shadow, brush1);
        palette4.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush8);
        palette4.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush2);
        palette4.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush1);
        btn0->setPalette(palette4);
        btn0->setFont(font2);
        btn0->setFocusPolicy(Qt::NoFocus);
        btn0->setStyleSheet(QStringLiteral("background-color: qlineargradient(spread:pad, x1:0.464, y1:1, x2:0.468, y2:0, stop:0.286364 rgba(23, 32, 42, 255), stop:0.681818 rgba(79, 112, 123, 255));"));
        btn3 = new QPushButton(grbbtn);
        btn3->setObjectName(QStringLiteral("btn3"));
        btn3->setGeometry(QRect(220, 10, 90, 60));
        QPalette palette5;
        palette5.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QLinearGradient gradient18(0.464, 1, 0.468, 0);
        gradient18.setSpread(QGradient::PadSpread);
        gradient18.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient18.setColorAt(0.286364, QColor(23, 32, 42, 255));
        gradient18.setColorAt(0.681818, QColor(79, 112, 123, 255));
        QBrush brush27(gradient18);
        palette5.setBrush(QPalette::Active, QPalette::Button, brush27);
        palette5.setBrush(QPalette::Active, QPalette::Light, brush4);
        palette5.setBrush(QPalette::Active, QPalette::Midlight, brush5);
        palette5.setBrush(QPalette::Active, QPalette::Dark, brush6);
        palette5.setBrush(QPalette::Active, QPalette::Mid, brush7);
        palette5.setBrush(QPalette::Active, QPalette::Text, brush);
        palette5.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette5.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        QLinearGradient gradient19(0.464, 1, 0.468, 0);
        gradient19.setSpread(QGradient::PadSpread);
        gradient19.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient19.setColorAt(0.286364, QColor(23, 32, 42, 255));
        gradient19.setColorAt(0.681818, QColor(79, 112, 123, 255));
        QBrush brush28(gradient19);
        palette5.setBrush(QPalette::Active, QPalette::Base, brush28);
        QLinearGradient gradient20(0.464, 1, 0.468, 0);
        gradient20.setSpread(QGradient::PadSpread);
        gradient20.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient20.setColorAt(0.286364, QColor(23, 32, 42, 255));
        gradient20.setColorAt(0.681818, QColor(79, 112, 123, 255));
        QBrush brush29(gradient20);
        palette5.setBrush(QPalette::Active, QPalette::Window, brush29);
        palette5.setBrush(QPalette::Active, QPalette::Shadow, brush1);
        palette5.setBrush(QPalette::Active, QPalette::AlternateBase, brush6);
        palette5.setBrush(QPalette::Active, QPalette::ToolTipBase, brush2);
        palette5.setBrush(QPalette::Active, QPalette::ToolTipText, brush1);
        palette5.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        QLinearGradient gradient21(0.464, 1, 0.468, 0);
        gradient21.setSpread(QGradient::PadSpread);
        gradient21.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient21.setColorAt(0.286364, QColor(23, 32, 42, 255));
        gradient21.setColorAt(0.681818, QColor(79, 112, 123, 255));
        QBrush brush30(gradient21);
        palette5.setBrush(QPalette::Inactive, QPalette::Button, brush30);
        palette5.setBrush(QPalette::Inactive, QPalette::Light, brush4);
        palette5.setBrush(QPalette::Inactive, QPalette::Midlight, brush5);
        palette5.setBrush(QPalette::Inactive, QPalette::Dark, brush6);
        palette5.setBrush(QPalette::Inactive, QPalette::Mid, brush7);
        palette5.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        QLinearGradient gradient22(0.464, 1, 0.468, 0);
        gradient22.setSpread(QGradient::PadSpread);
        gradient22.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient22.setColorAt(0.286364, QColor(23, 32, 42, 255));
        gradient22.setColorAt(0.681818, QColor(79, 112, 123, 255));
        QBrush brush31(gradient22);
        palette5.setBrush(QPalette::Inactive, QPalette::Base, brush31);
        QLinearGradient gradient23(0.464, 1, 0.468, 0);
        gradient23.setSpread(QGradient::PadSpread);
        gradient23.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient23.setColorAt(0.286364, QColor(23, 32, 42, 255));
        gradient23.setColorAt(0.681818, QColor(79, 112, 123, 255));
        QBrush brush32(gradient23);
        palette5.setBrush(QPalette::Inactive, QPalette::Window, brush32);
        palette5.setBrush(QPalette::Inactive, QPalette::Shadow, brush1);
        palette5.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush6);
        palette5.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush2);
        palette5.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush1);
        palette5.setBrush(QPalette::Disabled, QPalette::WindowText, brush6);
        QLinearGradient gradient24(0.464, 1, 0.468, 0);
        gradient24.setSpread(QGradient::PadSpread);
        gradient24.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient24.setColorAt(0.286364, QColor(23, 32, 42, 255));
        gradient24.setColorAt(0.681818, QColor(79, 112, 123, 255));
        QBrush brush33(gradient24);
        palette5.setBrush(QPalette::Disabled, QPalette::Button, brush33);
        palette5.setBrush(QPalette::Disabled, QPalette::Light, brush4);
        palette5.setBrush(QPalette::Disabled, QPalette::Midlight, brush5);
        palette5.setBrush(QPalette::Disabled, QPalette::Dark, brush6);
        palette5.setBrush(QPalette::Disabled, QPalette::Mid, brush7);
        palette5.setBrush(QPalette::Disabled, QPalette::Text, brush6);
        palette5.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette5.setBrush(QPalette::Disabled, QPalette::ButtonText, brush6);
        QLinearGradient gradient25(0.464, 1, 0.468, 0);
        gradient25.setSpread(QGradient::PadSpread);
        gradient25.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient25.setColorAt(0.286364, QColor(23, 32, 42, 255));
        gradient25.setColorAt(0.681818, QColor(79, 112, 123, 255));
        QBrush brush34(gradient25);
        palette5.setBrush(QPalette::Disabled, QPalette::Base, brush34);
        QLinearGradient gradient26(0.464, 1, 0.468, 0);
        gradient26.setSpread(QGradient::PadSpread);
        gradient26.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient26.setColorAt(0.286364, QColor(23, 32, 42, 255));
        gradient26.setColorAt(0.681818, QColor(79, 112, 123, 255));
        QBrush brush35(gradient26);
        palette5.setBrush(QPalette::Disabled, QPalette::Window, brush35);
        palette5.setBrush(QPalette::Disabled, QPalette::Shadow, brush1);
        palette5.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush8);
        palette5.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush2);
        palette5.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush1);
        btn3->setPalette(palette5);
        btn3->setFont(font2);
        btn3->setFocusPolicy(Qt::NoFocus);
        btn3->setStyleSheet(QStringLiteral("background-color: qlineargradient(spread:pad, x1:0.464, y1:1, x2:0.468, y2:0, stop:0.286364 rgba(23, 32, 42, 255), stop:0.681818 rgba(79, 112, 123, 255));"));
        btn1 = new QPushButton(grbbtn);
        btn1->setObjectName(QStringLiteral("btn1"));
        btn1->setGeometry(QRect(20, 10, 90, 60));
        QPalette palette6;
        palette6.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QLinearGradient gradient27(0.464, 1, 0.468, 0);
        gradient27.setSpread(QGradient::PadSpread);
        gradient27.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient27.setColorAt(0.286364, QColor(23, 32, 42, 255));
        gradient27.setColorAt(0.681818, QColor(79, 112, 123, 255));
        QBrush brush36(gradient27);
        palette6.setBrush(QPalette::Active, QPalette::Button, brush36);
        palette6.setBrush(QPalette::Active, QPalette::Light, brush4);
        palette6.setBrush(QPalette::Active, QPalette::Midlight, brush5);
        palette6.setBrush(QPalette::Active, QPalette::Dark, brush6);
        palette6.setBrush(QPalette::Active, QPalette::Mid, brush7);
        palette6.setBrush(QPalette::Active, QPalette::Text, brush);
        palette6.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette6.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        QLinearGradient gradient28(0.464, 1, 0.468, 0);
        gradient28.setSpread(QGradient::PadSpread);
        gradient28.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient28.setColorAt(0.286364, QColor(23, 32, 42, 255));
        gradient28.setColorAt(0.681818, QColor(79, 112, 123, 255));
        QBrush brush37(gradient28);
        palette6.setBrush(QPalette::Active, QPalette::Base, brush37);
        QLinearGradient gradient29(0.464, 1, 0.468, 0);
        gradient29.setSpread(QGradient::PadSpread);
        gradient29.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient29.setColorAt(0.286364, QColor(23, 32, 42, 255));
        gradient29.setColorAt(0.681818, QColor(79, 112, 123, 255));
        QBrush brush38(gradient29);
        palette6.setBrush(QPalette::Active, QPalette::Window, brush38);
        palette6.setBrush(QPalette::Active, QPalette::Shadow, brush1);
        palette6.setBrush(QPalette::Active, QPalette::AlternateBase, brush6);
        palette6.setBrush(QPalette::Active, QPalette::ToolTipBase, brush2);
        palette6.setBrush(QPalette::Active, QPalette::ToolTipText, brush1);
        palette6.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        QLinearGradient gradient30(0.464, 1, 0.468, 0);
        gradient30.setSpread(QGradient::PadSpread);
        gradient30.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient30.setColorAt(0.286364, QColor(23, 32, 42, 255));
        gradient30.setColorAt(0.681818, QColor(79, 112, 123, 255));
        QBrush brush39(gradient30);
        palette6.setBrush(QPalette::Inactive, QPalette::Button, brush39);
        palette6.setBrush(QPalette::Inactive, QPalette::Light, brush4);
        palette6.setBrush(QPalette::Inactive, QPalette::Midlight, brush5);
        palette6.setBrush(QPalette::Inactive, QPalette::Dark, brush6);
        palette6.setBrush(QPalette::Inactive, QPalette::Mid, brush7);
        palette6.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        QLinearGradient gradient31(0.464, 1, 0.468, 0);
        gradient31.setSpread(QGradient::PadSpread);
        gradient31.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient31.setColorAt(0.286364, QColor(23, 32, 42, 255));
        gradient31.setColorAt(0.681818, QColor(79, 112, 123, 255));
        QBrush brush40(gradient31);
        palette6.setBrush(QPalette::Inactive, QPalette::Base, brush40);
        QLinearGradient gradient32(0.464, 1, 0.468, 0);
        gradient32.setSpread(QGradient::PadSpread);
        gradient32.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient32.setColorAt(0.286364, QColor(23, 32, 42, 255));
        gradient32.setColorAt(0.681818, QColor(79, 112, 123, 255));
        QBrush brush41(gradient32);
        palette6.setBrush(QPalette::Inactive, QPalette::Window, brush41);
        palette6.setBrush(QPalette::Inactive, QPalette::Shadow, brush1);
        palette6.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush6);
        palette6.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush2);
        palette6.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush1);
        palette6.setBrush(QPalette::Disabled, QPalette::WindowText, brush6);
        QLinearGradient gradient33(0.464, 1, 0.468, 0);
        gradient33.setSpread(QGradient::PadSpread);
        gradient33.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient33.setColorAt(0.286364, QColor(23, 32, 42, 255));
        gradient33.setColorAt(0.681818, QColor(79, 112, 123, 255));
        QBrush brush42(gradient33);
        palette6.setBrush(QPalette::Disabled, QPalette::Button, brush42);
        palette6.setBrush(QPalette::Disabled, QPalette::Light, brush4);
        palette6.setBrush(QPalette::Disabled, QPalette::Midlight, brush5);
        palette6.setBrush(QPalette::Disabled, QPalette::Dark, brush6);
        palette6.setBrush(QPalette::Disabled, QPalette::Mid, brush7);
        palette6.setBrush(QPalette::Disabled, QPalette::Text, brush6);
        palette6.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette6.setBrush(QPalette::Disabled, QPalette::ButtonText, brush6);
        QLinearGradient gradient34(0.464, 1, 0.468, 0);
        gradient34.setSpread(QGradient::PadSpread);
        gradient34.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient34.setColorAt(0.286364, QColor(23, 32, 42, 255));
        gradient34.setColorAt(0.681818, QColor(79, 112, 123, 255));
        QBrush brush43(gradient34);
        palette6.setBrush(QPalette::Disabled, QPalette::Base, brush43);
        QLinearGradient gradient35(0.464, 1, 0.468, 0);
        gradient35.setSpread(QGradient::PadSpread);
        gradient35.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient35.setColorAt(0.286364, QColor(23, 32, 42, 255));
        gradient35.setColorAt(0.681818, QColor(79, 112, 123, 255));
        QBrush brush44(gradient35);
        palette6.setBrush(QPalette::Disabled, QPalette::Window, brush44);
        palette6.setBrush(QPalette::Disabled, QPalette::Shadow, brush1);
        palette6.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush8);
        palette6.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush2);
        palette6.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush1);
        btn1->setPalette(palette6);
        btn1->setFont(font2);
        btn1->setFocusPolicy(Qt::NoFocus);
        btn1->setStyleSheet(QStringLiteral("background-color: qlineargradient(spread:pad, x1:0.464, y1:1, x2:0.468, y2:0, stop:0.286364 rgba(23, 32, 42, 255), stop:0.681818 rgba(79, 112, 123, 255));"));
        btn6 = new QPushButton(grbbtn);
        btn6->setObjectName(QStringLiteral("btn6"));
        btn6->setGeometry(QRect(120, 80, 90, 60));
        QPalette palette7;
        palette7.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QLinearGradient gradient36(0.464, 1, 0.468, 0);
        gradient36.setSpread(QGradient::PadSpread);
        gradient36.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient36.setColorAt(0.286364, QColor(23, 32, 42, 255));
        gradient36.setColorAt(0.681818, QColor(79, 112, 123, 255));
        QBrush brush45(gradient36);
        palette7.setBrush(QPalette::Active, QPalette::Button, brush45);
        palette7.setBrush(QPalette::Active, QPalette::Light, brush4);
        palette7.setBrush(QPalette::Active, QPalette::Midlight, brush5);
        palette7.setBrush(QPalette::Active, QPalette::Dark, brush6);
        palette7.setBrush(QPalette::Active, QPalette::Mid, brush7);
        palette7.setBrush(QPalette::Active, QPalette::Text, brush);
        palette7.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette7.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        QLinearGradient gradient37(0.464, 1, 0.468, 0);
        gradient37.setSpread(QGradient::PadSpread);
        gradient37.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient37.setColorAt(0.286364, QColor(23, 32, 42, 255));
        gradient37.setColorAt(0.681818, QColor(79, 112, 123, 255));
        QBrush brush46(gradient37);
        palette7.setBrush(QPalette::Active, QPalette::Base, brush46);
        QLinearGradient gradient38(0.464, 1, 0.468, 0);
        gradient38.setSpread(QGradient::PadSpread);
        gradient38.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient38.setColorAt(0.286364, QColor(23, 32, 42, 255));
        gradient38.setColorAt(0.681818, QColor(79, 112, 123, 255));
        QBrush brush47(gradient38);
        palette7.setBrush(QPalette::Active, QPalette::Window, brush47);
        palette7.setBrush(QPalette::Active, QPalette::Shadow, brush1);
        palette7.setBrush(QPalette::Active, QPalette::AlternateBase, brush6);
        palette7.setBrush(QPalette::Active, QPalette::ToolTipBase, brush2);
        palette7.setBrush(QPalette::Active, QPalette::ToolTipText, brush1);
        palette7.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        QLinearGradient gradient39(0.464, 1, 0.468, 0);
        gradient39.setSpread(QGradient::PadSpread);
        gradient39.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient39.setColorAt(0.286364, QColor(23, 32, 42, 255));
        gradient39.setColorAt(0.681818, QColor(79, 112, 123, 255));
        QBrush brush48(gradient39);
        palette7.setBrush(QPalette::Inactive, QPalette::Button, brush48);
        palette7.setBrush(QPalette::Inactive, QPalette::Light, brush4);
        palette7.setBrush(QPalette::Inactive, QPalette::Midlight, brush5);
        palette7.setBrush(QPalette::Inactive, QPalette::Dark, brush6);
        palette7.setBrush(QPalette::Inactive, QPalette::Mid, brush7);
        palette7.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette7.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette7.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        QLinearGradient gradient40(0.464, 1, 0.468, 0);
        gradient40.setSpread(QGradient::PadSpread);
        gradient40.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient40.setColorAt(0.286364, QColor(23, 32, 42, 255));
        gradient40.setColorAt(0.681818, QColor(79, 112, 123, 255));
        QBrush brush49(gradient40);
        palette7.setBrush(QPalette::Inactive, QPalette::Base, brush49);
        QLinearGradient gradient41(0.464, 1, 0.468, 0);
        gradient41.setSpread(QGradient::PadSpread);
        gradient41.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient41.setColorAt(0.286364, QColor(23, 32, 42, 255));
        gradient41.setColorAt(0.681818, QColor(79, 112, 123, 255));
        QBrush brush50(gradient41);
        palette7.setBrush(QPalette::Inactive, QPalette::Window, brush50);
        palette7.setBrush(QPalette::Inactive, QPalette::Shadow, brush1);
        palette7.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush6);
        palette7.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush2);
        palette7.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush1);
        palette7.setBrush(QPalette::Disabled, QPalette::WindowText, brush6);
        QLinearGradient gradient42(0.464, 1, 0.468, 0);
        gradient42.setSpread(QGradient::PadSpread);
        gradient42.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient42.setColorAt(0.286364, QColor(23, 32, 42, 255));
        gradient42.setColorAt(0.681818, QColor(79, 112, 123, 255));
        QBrush brush51(gradient42);
        palette7.setBrush(QPalette::Disabled, QPalette::Button, brush51);
        palette7.setBrush(QPalette::Disabled, QPalette::Light, brush4);
        palette7.setBrush(QPalette::Disabled, QPalette::Midlight, brush5);
        palette7.setBrush(QPalette::Disabled, QPalette::Dark, brush6);
        palette7.setBrush(QPalette::Disabled, QPalette::Mid, brush7);
        palette7.setBrush(QPalette::Disabled, QPalette::Text, brush6);
        palette7.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette7.setBrush(QPalette::Disabled, QPalette::ButtonText, brush6);
        QLinearGradient gradient43(0.464, 1, 0.468, 0);
        gradient43.setSpread(QGradient::PadSpread);
        gradient43.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient43.setColorAt(0.286364, QColor(23, 32, 42, 255));
        gradient43.setColorAt(0.681818, QColor(79, 112, 123, 255));
        QBrush brush52(gradient43);
        palette7.setBrush(QPalette::Disabled, QPalette::Base, brush52);
        QLinearGradient gradient44(0.464, 1, 0.468, 0);
        gradient44.setSpread(QGradient::PadSpread);
        gradient44.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient44.setColorAt(0.286364, QColor(23, 32, 42, 255));
        gradient44.setColorAt(0.681818, QColor(79, 112, 123, 255));
        QBrush brush53(gradient44);
        palette7.setBrush(QPalette::Disabled, QPalette::Window, brush53);
        palette7.setBrush(QPalette::Disabled, QPalette::Shadow, brush1);
        palette7.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush8);
        palette7.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush2);
        palette7.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush1);
        btn6->setPalette(palette7);
        btn6->setFont(font2);
        btn6->setFocusPolicy(Qt::NoFocus);
        btn6->setStyleSheet(QStringLiteral("background-color: qlineargradient(spread:pad, x1:0.464, y1:1, x2:0.468, y2:0, stop:0.286364 rgba(23, 32, 42, 255), stop:0.681818 rgba(79, 112, 123, 255));"));
        btn5 = new QPushButton(grbbtn);
        btn5->setObjectName(QStringLiteral("btn5"));
        btn5->setGeometry(QRect(20, 80, 90, 60));
        QPalette palette8;
        palette8.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QLinearGradient gradient45(0.464, 1, 0.468, 0);
        gradient45.setSpread(QGradient::PadSpread);
        gradient45.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient45.setColorAt(0.286364, QColor(23, 32, 42, 255));
        gradient45.setColorAt(0.681818, QColor(79, 112, 123, 255));
        QBrush brush54(gradient45);
        palette8.setBrush(QPalette::Active, QPalette::Button, brush54);
        palette8.setBrush(QPalette::Active, QPalette::Light, brush4);
        palette8.setBrush(QPalette::Active, QPalette::Midlight, brush5);
        palette8.setBrush(QPalette::Active, QPalette::Dark, brush6);
        palette8.setBrush(QPalette::Active, QPalette::Mid, brush7);
        palette8.setBrush(QPalette::Active, QPalette::Text, brush);
        palette8.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette8.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        QLinearGradient gradient46(0.464, 1, 0.468, 0);
        gradient46.setSpread(QGradient::PadSpread);
        gradient46.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient46.setColorAt(0.286364, QColor(23, 32, 42, 255));
        gradient46.setColorAt(0.681818, QColor(79, 112, 123, 255));
        QBrush brush55(gradient46);
        palette8.setBrush(QPalette::Active, QPalette::Base, brush55);
        QLinearGradient gradient47(0.464, 1, 0.468, 0);
        gradient47.setSpread(QGradient::PadSpread);
        gradient47.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient47.setColorAt(0.286364, QColor(23, 32, 42, 255));
        gradient47.setColorAt(0.681818, QColor(79, 112, 123, 255));
        QBrush brush56(gradient47);
        palette8.setBrush(QPalette::Active, QPalette::Window, brush56);
        palette8.setBrush(QPalette::Active, QPalette::Shadow, brush1);
        palette8.setBrush(QPalette::Active, QPalette::AlternateBase, brush6);
        palette8.setBrush(QPalette::Active, QPalette::ToolTipBase, brush2);
        palette8.setBrush(QPalette::Active, QPalette::ToolTipText, brush1);
        palette8.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        QLinearGradient gradient48(0.464, 1, 0.468, 0);
        gradient48.setSpread(QGradient::PadSpread);
        gradient48.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient48.setColorAt(0.286364, QColor(23, 32, 42, 255));
        gradient48.setColorAt(0.681818, QColor(79, 112, 123, 255));
        QBrush brush57(gradient48);
        palette8.setBrush(QPalette::Inactive, QPalette::Button, brush57);
        palette8.setBrush(QPalette::Inactive, QPalette::Light, brush4);
        palette8.setBrush(QPalette::Inactive, QPalette::Midlight, brush5);
        palette8.setBrush(QPalette::Inactive, QPalette::Dark, brush6);
        palette8.setBrush(QPalette::Inactive, QPalette::Mid, brush7);
        palette8.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        QLinearGradient gradient49(0.464, 1, 0.468, 0);
        gradient49.setSpread(QGradient::PadSpread);
        gradient49.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient49.setColorAt(0.286364, QColor(23, 32, 42, 255));
        gradient49.setColorAt(0.681818, QColor(79, 112, 123, 255));
        QBrush brush58(gradient49);
        palette8.setBrush(QPalette::Inactive, QPalette::Base, brush58);
        QLinearGradient gradient50(0.464, 1, 0.468, 0);
        gradient50.setSpread(QGradient::PadSpread);
        gradient50.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient50.setColorAt(0.286364, QColor(23, 32, 42, 255));
        gradient50.setColorAt(0.681818, QColor(79, 112, 123, 255));
        QBrush brush59(gradient50);
        palette8.setBrush(QPalette::Inactive, QPalette::Window, brush59);
        palette8.setBrush(QPalette::Inactive, QPalette::Shadow, brush1);
        palette8.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush6);
        palette8.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush2);
        palette8.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush1);
        palette8.setBrush(QPalette::Disabled, QPalette::WindowText, brush6);
        QLinearGradient gradient51(0.464, 1, 0.468, 0);
        gradient51.setSpread(QGradient::PadSpread);
        gradient51.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient51.setColorAt(0.286364, QColor(23, 32, 42, 255));
        gradient51.setColorAt(0.681818, QColor(79, 112, 123, 255));
        QBrush brush60(gradient51);
        palette8.setBrush(QPalette::Disabled, QPalette::Button, brush60);
        palette8.setBrush(QPalette::Disabled, QPalette::Light, brush4);
        palette8.setBrush(QPalette::Disabled, QPalette::Midlight, brush5);
        palette8.setBrush(QPalette::Disabled, QPalette::Dark, brush6);
        palette8.setBrush(QPalette::Disabled, QPalette::Mid, brush7);
        palette8.setBrush(QPalette::Disabled, QPalette::Text, brush6);
        palette8.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette8.setBrush(QPalette::Disabled, QPalette::ButtonText, brush6);
        QLinearGradient gradient52(0.464, 1, 0.468, 0);
        gradient52.setSpread(QGradient::PadSpread);
        gradient52.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient52.setColorAt(0.286364, QColor(23, 32, 42, 255));
        gradient52.setColorAt(0.681818, QColor(79, 112, 123, 255));
        QBrush brush61(gradient52);
        palette8.setBrush(QPalette::Disabled, QPalette::Base, brush61);
        QLinearGradient gradient53(0.464, 1, 0.468, 0);
        gradient53.setSpread(QGradient::PadSpread);
        gradient53.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient53.setColorAt(0.286364, QColor(23, 32, 42, 255));
        gradient53.setColorAt(0.681818, QColor(79, 112, 123, 255));
        QBrush brush62(gradient53);
        palette8.setBrush(QPalette::Disabled, QPalette::Window, brush62);
        palette8.setBrush(QPalette::Disabled, QPalette::Shadow, brush1);
        palette8.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush8);
        palette8.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush2);
        palette8.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush1);
        btn5->setPalette(palette8);
        btn5->setFont(font2);
        btn5->setFocusPolicy(Qt::NoFocus);
        btn5->setStyleSheet(QStringLiteral("background-color: qlineargradient(spread:pad, x1:0.464, y1:1, x2:0.468, y2:0, stop:0.286364 rgba(23, 32, 42, 255), stop:0.681818 rgba(79, 112, 123, 255));"));
        btn8 = new QPushButton(grbbtn);
        btn8->setObjectName(QStringLiteral("btn8"));
        btn8->setGeometry(QRect(320, 80, 90, 60));
        QPalette palette9;
        palette9.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QLinearGradient gradient54(0.464, 1, 0.468, 0);
        gradient54.setSpread(QGradient::PadSpread);
        gradient54.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient54.setColorAt(0.286364, QColor(23, 32, 42, 255));
        gradient54.setColorAt(0.681818, QColor(79, 112, 123, 255));
        QBrush brush63(gradient54);
        palette9.setBrush(QPalette::Active, QPalette::Button, brush63);
        palette9.setBrush(QPalette::Active, QPalette::Light, brush4);
        palette9.setBrush(QPalette::Active, QPalette::Midlight, brush5);
        palette9.setBrush(QPalette::Active, QPalette::Dark, brush6);
        palette9.setBrush(QPalette::Active, QPalette::Mid, brush7);
        palette9.setBrush(QPalette::Active, QPalette::Text, brush);
        palette9.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette9.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        QLinearGradient gradient55(0.464, 1, 0.468, 0);
        gradient55.setSpread(QGradient::PadSpread);
        gradient55.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient55.setColorAt(0.286364, QColor(23, 32, 42, 255));
        gradient55.setColorAt(0.681818, QColor(79, 112, 123, 255));
        QBrush brush64(gradient55);
        palette9.setBrush(QPalette::Active, QPalette::Base, brush64);
        QLinearGradient gradient56(0.464, 1, 0.468, 0);
        gradient56.setSpread(QGradient::PadSpread);
        gradient56.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient56.setColorAt(0.286364, QColor(23, 32, 42, 255));
        gradient56.setColorAt(0.681818, QColor(79, 112, 123, 255));
        QBrush brush65(gradient56);
        palette9.setBrush(QPalette::Active, QPalette::Window, brush65);
        palette9.setBrush(QPalette::Active, QPalette::Shadow, brush1);
        palette9.setBrush(QPalette::Active, QPalette::AlternateBase, brush6);
        palette9.setBrush(QPalette::Active, QPalette::ToolTipBase, brush2);
        palette9.setBrush(QPalette::Active, QPalette::ToolTipText, brush1);
        palette9.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        QLinearGradient gradient57(0.464, 1, 0.468, 0);
        gradient57.setSpread(QGradient::PadSpread);
        gradient57.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient57.setColorAt(0.286364, QColor(23, 32, 42, 255));
        gradient57.setColorAt(0.681818, QColor(79, 112, 123, 255));
        QBrush brush66(gradient57);
        palette9.setBrush(QPalette::Inactive, QPalette::Button, brush66);
        palette9.setBrush(QPalette::Inactive, QPalette::Light, brush4);
        palette9.setBrush(QPalette::Inactive, QPalette::Midlight, brush5);
        palette9.setBrush(QPalette::Inactive, QPalette::Dark, brush6);
        palette9.setBrush(QPalette::Inactive, QPalette::Mid, brush7);
        palette9.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette9.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette9.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        QLinearGradient gradient58(0.464, 1, 0.468, 0);
        gradient58.setSpread(QGradient::PadSpread);
        gradient58.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient58.setColorAt(0.286364, QColor(23, 32, 42, 255));
        gradient58.setColorAt(0.681818, QColor(79, 112, 123, 255));
        QBrush brush67(gradient58);
        palette9.setBrush(QPalette::Inactive, QPalette::Base, brush67);
        QLinearGradient gradient59(0.464, 1, 0.468, 0);
        gradient59.setSpread(QGradient::PadSpread);
        gradient59.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient59.setColorAt(0.286364, QColor(23, 32, 42, 255));
        gradient59.setColorAt(0.681818, QColor(79, 112, 123, 255));
        QBrush brush68(gradient59);
        palette9.setBrush(QPalette::Inactive, QPalette::Window, brush68);
        palette9.setBrush(QPalette::Inactive, QPalette::Shadow, brush1);
        palette9.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush6);
        palette9.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush2);
        palette9.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush1);
        palette9.setBrush(QPalette::Disabled, QPalette::WindowText, brush6);
        QLinearGradient gradient60(0.464, 1, 0.468, 0);
        gradient60.setSpread(QGradient::PadSpread);
        gradient60.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient60.setColorAt(0.286364, QColor(23, 32, 42, 255));
        gradient60.setColorAt(0.681818, QColor(79, 112, 123, 255));
        QBrush brush69(gradient60);
        palette9.setBrush(QPalette::Disabled, QPalette::Button, brush69);
        palette9.setBrush(QPalette::Disabled, QPalette::Light, brush4);
        palette9.setBrush(QPalette::Disabled, QPalette::Midlight, brush5);
        palette9.setBrush(QPalette::Disabled, QPalette::Dark, brush6);
        palette9.setBrush(QPalette::Disabled, QPalette::Mid, brush7);
        palette9.setBrush(QPalette::Disabled, QPalette::Text, brush6);
        palette9.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette9.setBrush(QPalette::Disabled, QPalette::ButtonText, brush6);
        QLinearGradient gradient61(0.464, 1, 0.468, 0);
        gradient61.setSpread(QGradient::PadSpread);
        gradient61.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient61.setColorAt(0.286364, QColor(23, 32, 42, 255));
        gradient61.setColorAt(0.681818, QColor(79, 112, 123, 255));
        QBrush brush70(gradient61);
        palette9.setBrush(QPalette::Disabled, QPalette::Base, brush70);
        QLinearGradient gradient62(0.464, 1, 0.468, 0);
        gradient62.setSpread(QGradient::PadSpread);
        gradient62.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient62.setColorAt(0.286364, QColor(23, 32, 42, 255));
        gradient62.setColorAt(0.681818, QColor(79, 112, 123, 255));
        QBrush brush71(gradient62);
        palette9.setBrush(QPalette::Disabled, QPalette::Window, brush71);
        palette9.setBrush(QPalette::Disabled, QPalette::Shadow, brush1);
        palette9.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush8);
        palette9.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush2);
        palette9.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush1);
        btn8->setPalette(palette9);
        btn8->setFont(font2);
        btn8->setFocusPolicy(Qt::NoFocus);
        btn8->setStyleSheet(QStringLiteral("background-color: qlineargradient(spread:pad, x1:0.464, y1:1, x2:0.468, y2:0, stop:0.286364 rgba(23, 32, 42, 255), stop:0.681818 rgba(79, 112, 123, 255));"));
        btn7 = new QPushButton(grbbtn);
        btn7->setObjectName(QStringLiteral("btn7"));
        btn7->setGeometry(QRect(220, 80, 90, 60));
        QPalette palette10;
        palette10.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QLinearGradient gradient63(0.464, 1, 0.468, 0);
        gradient63.setSpread(QGradient::PadSpread);
        gradient63.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient63.setColorAt(0.286364, QColor(23, 32, 42, 255));
        gradient63.setColorAt(0.681818, QColor(79, 112, 123, 255));
        QBrush brush72(gradient63);
        palette10.setBrush(QPalette::Active, QPalette::Button, brush72);
        palette10.setBrush(QPalette::Active, QPalette::Light, brush4);
        palette10.setBrush(QPalette::Active, QPalette::Midlight, brush5);
        palette10.setBrush(QPalette::Active, QPalette::Dark, brush6);
        palette10.setBrush(QPalette::Active, QPalette::Mid, brush7);
        palette10.setBrush(QPalette::Active, QPalette::Text, brush);
        palette10.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette10.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        QLinearGradient gradient64(0.464, 1, 0.468, 0);
        gradient64.setSpread(QGradient::PadSpread);
        gradient64.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient64.setColorAt(0.286364, QColor(23, 32, 42, 255));
        gradient64.setColorAt(0.681818, QColor(79, 112, 123, 255));
        QBrush brush73(gradient64);
        palette10.setBrush(QPalette::Active, QPalette::Base, brush73);
        QLinearGradient gradient65(0.464, 1, 0.468, 0);
        gradient65.setSpread(QGradient::PadSpread);
        gradient65.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient65.setColorAt(0.286364, QColor(23, 32, 42, 255));
        gradient65.setColorAt(0.681818, QColor(79, 112, 123, 255));
        QBrush brush74(gradient65);
        palette10.setBrush(QPalette::Active, QPalette::Window, brush74);
        palette10.setBrush(QPalette::Active, QPalette::Shadow, brush1);
        palette10.setBrush(QPalette::Active, QPalette::AlternateBase, brush6);
        palette10.setBrush(QPalette::Active, QPalette::ToolTipBase, brush2);
        palette10.setBrush(QPalette::Active, QPalette::ToolTipText, brush1);
        palette10.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        QLinearGradient gradient66(0.464, 1, 0.468, 0);
        gradient66.setSpread(QGradient::PadSpread);
        gradient66.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient66.setColorAt(0.286364, QColor(23, 32, 42, 255));
        gradient66.setColorAt(0.681818, QColor(79, 112, 123, 255));
        QBrush brush75(gradient66);
        palette10.setBrush(QPalette::Inactive, QPalette::Button, brush75);
        palette10.setBrush(QPalette::Inactive, QPalette::Light, brush4);
        palette10.setBrush(QPalette::Inactive, QPalette::Midlight, brush5);
        palette10.setBrush(QPalette::Inactive, QPalette::Dark, brush6);
        palette10.setBrush(QPalette::Inactive, QPalette::Mid, brush7);
        palette10.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette10.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette10.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        QLinearGradient gradient67(0.464, 1, 0.468, 0);
        gradient67.setSpread(QGradient::PadSpread);
        gradient67.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient67.setColorAt(0.286364, QColor(23, 32, 42, 255));
        gradient67.setColorAt(0.681818, QColor(79, 112, 123, 255));
        QBrush brush76(gradient67);
        palette10.setBrush(QPalette::Inactive, QPalette::Base, brush76);
        QLinearGradient gradient68(0.464, 1, 0.468, 0);
        gradient68.setSpread(QGradient::PadSpread);
        gradient68.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient68.setColorAt(0.286364, QColor(23, 32, 42, 255));
        gradient68.setColorAt(0.681818, QColor(79, 112, 123, 255));
        QBrush brush77(gradient68);
        palette10.setBrush(QPalette::Inactive, QPalette::Window, brush77);
        palette10.setBrush(QPalette::Inactive, QPalette::Shadow, brush1);
        palette10.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush6);
        palette10.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush2);
        palette10.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush1);
        palette10.setBrush(QPalette::Disabled, QPalette::WindowText, brush6);
        QLinearGradient gradient69(0.464, 1, 0.468, 0);
        gradient69.setSpread(QGradient::PadSpread);
        gradient69.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient69.setColorAt(0.286364, QColor(23, 32, 42, 255));
        gradient69.setColorAt(0.681818, QColor(79, 112, 123, 255));
        QBrush brush78(gradient69);
        palette10.setBrush(QPalette::Disabled, QPalette::Button, brush78);
        palette10.setBrush(QPalette::Disabled, QPalette::Light, brush4);
        palette10.setBrush(QPalette::Disabled, QPalette::Midlight, brush5);
        palette10.setBrush(QPalette::Disabled, QPalette::Dark, brush6);
        palette10.setBrush(QPalette::Disabled, QPalette::Mid, brush7);
        palette10.setBrush(QPalette::Disabled, QPalette::Text, brush6);
        palette10.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette10.setBrush(QPalette::Disabled, QPalette::ButtonText, brush6);
        QLinearGradient gradient70(0.464, 1, 0.468, 0);
        gradient70.setSpread(QGradient::PadSpread);
        gradient70.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient70.setColorAt(0.286364, QColor(23, 32, 42, 255));
        gradient70.setColorAt(0.681818, QColor(79, 112, 123, 255));
        QBrush brush79(gradient70);
        palette10.setBrush(QPalette::Disabled, QPalette::Base, brush79);
        QLinearGradient gradient71(0.464, 1, 0.468, 0);
        gradient71.setSpread(QGradient::PadSpread);
        gradient71.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient71.setColorAt(0.286364, QColor(23, 32, 42, 255));
        gradient71.setColorAt(0.681818, QColor(79, 112, 123, 255));
        QBrush brush80(gradient71);
        palette10.setBrush(QPalette::Disabled, QPalette::Window, brush80);
        palette10.setBrush(QPalette::Disabled, QPalette::Shadow, brush1);
        palette10.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush8);
        palette10.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush2);
        palette10.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush1);
        btn7->setPalette(palette10);
        btn7->setFont(font2);
        btn7->setFocusPolicy(Qt::NoFocus);
        btn7->setStyleSheet(QStringLiteral("background-color: qlineargradient(spread:pad, x1:0.464, y1:1, x2:0.468, y2:0, stop:0.286364 rgba(23, 32, 42, 255), stop:0.681818 rgba(79, 112, 123, 255));"));
        btn4 = new QPushButton(grbbtn);
        btn4->setObjectName(QStringLiteral("btn4"));
        btn4->setGeometry(QRect(320, 10, 90, 60));
        QPalette palette11;
        palette11.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QLinearGradient gradient72(0.464, 1, 0.468, 0);
        gradient72.setSpread(QGradient::PadSpread);
        gradient72.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient72.setColorAt(0.286364, QColor(23, 32, 42, 255));
        gradient72.setColorAt(0.681818, QColor(79, 112, 123, 255));
        QBrush brush81(gradient72);
        palette11.setBrush(QPalette::Active, QPalette::Button, brush81);
        palette11.setBrush(QPalette::Active, QPalette::Light, brush4);
        palette11.setBrush(QPalette::Active, QPalette::Midlight, brush5);
        palette11.setBrush(QPalette::Active, QPalette::Dark, brush6);
        palette11.setBrush(QPalette::Active, QPalette::Mid, brush7);
        palette11.setBrush(QPalette::Active, QPalette::Text, brush);
        palette11.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette11.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        QLinearGradient gradient73(0.464, 1, 0.468, 0);
        gradient73.setSpread(QGradient::PadSpread);
        gradient73.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient73.setColorAt(0.286364, QColor(23, 32, 42, 255));
        gradient73.setColorAt(0.681818, QColor(79, 112, 123, 255));
        QBrush brush82(gradient73);
        palette11.setBrush(QPalette::Active, QPalette::Base, brush82);
        QLinearGradient gradient74(0.464, 1, 0.468, 0);
        gradient74.setSpread(QGradient::PadSpread);
        gradient74.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient74.setColorAt(0.286364, QColor(23, 32, 42, 255));
        gradient74.setColorAt(0.681818, QColor(79, 112, 123, 255));
        QBrush brush83(gradient74);
        palette11.setBrush(QPalette::Active, QPalette::Window, brush83);
        palette11.setBrush(QPalette::Active, QPalette::Shadow, brush1);
        palette11.setBrush(QPalette::Active, QPalette::AlternateBase, brush6);
        palette11.setBrush(QPalette::Active, QPalette::ToolTipBase, brush2);
        palette11.setBrush(QPalette::Active, QPalette::ToolTipText, brush1);
        palette11.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        QLinearGradient gradient75(0.464, 1, 0.468, 0);
        gradient75.setSpread(QGradient::PadSpread);
        gradient75.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient75.setColorAt(0.286364, QColor(23, 32, 42, 255));
        gradient75.setColorAt(0.681818, QColor(79, 112, 123, 255));
        QBrush brush84(gradient75);
        palette11.setBrush(QPalette::Inactive, QPalette::Button, brush84);
        palette11.setBrush(QPalette::Inactive, QPalette::Light, brush4);
        palette11.setBrush(QPalette::Inactive, QPalette::Midlight, brush5);
        palette11.setBrush(QPalette::Inactive, QPalette::Dark, brush6);
        palette11.setBrush(QPalette::Inactive, QPalette::Mid, brush7);
        palette11.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette11.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette11.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        QLinearGradient gradient76(0.464, 1, 0.468, 0);
        gradient76.setSpread(QGradient::PadSpread);
        gradient76.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient76.setColorAt(0.286364, QColor(23, 32, 42, 255));
        gradient76.setColorAt(0.681818, QColor(79, 112, 123, 255));
        QBrush brush85(gradient76);
        palette11.setBrush(QPalette::Inactive, QPalette::Base, brush85);
        QLinearGradient gradient77(0.464, 1, 0.468, 0);
        gradient77.setSpread(QGradient::PadSpread);
        gradient77.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient77.setColorAt(0.286364, QColor(23, 32, 42, 255));
        gradient77.setColorAt(0.681818, QColor(79, 112, 123, 255));
        QBrush brush86(gradient77);
        palette11.setBrush(QPalette::Inactive, QPalette::Window, brush86);
        palette11.setBrush(QPalette::Inactive, QPalette::Shadow, brush1);
        palette11.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush6);
        palette11.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush2);
        palette11.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush1);
        palette11.setBrush(QPalette::Disabled, QPalette::WindowText, brush6);
        QLinearGradient gradient78(0.464, 1, 0.468, 0);
        gradient78.setSpread(QGradient::PadSpread);
        gradient78.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient78.setColorAt(0.286364, QColor(23, 32, 42, 255));
        gradient78.setColorAt(0.681818, QColor(79, 112, 123, 255));
        QBrush brush87(gradient78);
        palette11.setBrush(QPalette::Disabled, QPalette::Button, brush87);
        palette11.setBrush(QPalette::Disabled, QPalette::Light, brush4);
        palette11.setBrush(QPalette::Disabled, QPalette::Midlight, brush5);
        palette11.setBrush(QPalette::Disabled, QPalette::Dark, brush6);
        palette11.setBrush(QPalette::Disabled, QPalette::Mid, brush7);
        palette11.setBrush(QPalette::Disabled, QPalette::Text, brush6);
        palette11.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette11.setBrush(QPalette::Disabled, QPalette::ButtonText, brush6);
        QLinearGradient gradient79(0.464, 1, 0.468, 0);
        gradient79.setSpread(QGradient::PadSpread);
        gradient79.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient79.setColorAt(0.286364, QColor(23, 32, 42, 255));
        gradient79.setColorAt(0.681818, QColor(79, 112, 123, 255));
        QBrush brush88(gradient79);
        palette11.setBrush(QPalette::Disabled, QPalette::Base, brush88);
        QLinearGradient gradient80(0.464, 1, 0.468, 0);
        gradient80.setSpread(QGradient::PadSpread);
        gradient80.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient80.setColorAt(0.286364, QColor(23, 32, 42, 255));
        gradient80.setColorAt(0.681818, QColor(79, 112, 123, 255));
        QBrush brush89(gradient80);
        palette11.setBrush(QPalette::Disabled, QPalette::Window, brush89);
        palette11.setBrush(QPalette::Disabled, QPalette::Shadow, brush1);
        palette11.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush8);
        palette11.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush2);
        palette11.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush1);
        btn4->setPalette(palette11);
        btn4->setFont(font2);
        btn4->setFocusPolicy(Qt::NoFocus);
        btn4->setStyleSheet(QStringLiteral("background-color: qlineargradient(spread:pad, x1:0.464, y1:1, x2:0.468, y2:0, stop:0.286364 rgba(23, 32, 42, 255), stop:0.681818 rgba(79, 112, 123, 255));"));
        btnDelete = new QPushButton(grbbtn);
        btnDelete->setObjectName(QStringLiteral("btnDelete"));
        btnDelete->setGeometry(QRect(220, 150, 191, 60));
        QPalette palette12;
        palette12.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QLinearGradient gradient81(0.464, 1, 0.468, 0);
        gradient81.setSpread(QGradient::PadSpread);
        gradient81.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient81.setColorAt(0.286364, QColor(23, 32, 42, 255));
        gradient81.setColorAt(0.681818, QColor(79, 112, 123, 255));
        QBrush brush90(gradient81);
        palette12.setBrush(QPalette::Active, QPalette::Button, brush90);
        palette12.setBrush(QPalette::Active, QPalette::Light, brush4);
        palette12.setBrush(QPalette::Active, QPalette::Midlight, brush5);
        palette12.setBrush(QPalette::Active, QPalette::Dark, brush6);
        palette12.setBrush(QPalette::Active, QPalette::Mid, brush7);
        palette12.setBrush(QPalette::Active, QPalette::Text, brush);
        palette12.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette12.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        QLinearGradient gradient82(0.464, 1, 0.468, 0);
        gradient82.setSpread(QGradient::PadSpread);
        gradient82.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient82.setColorAt(0.286364, QColor(23, 32, 42, 255));
        gradient82.setColorAt(0.681818, QColor(79, 112, 123, 255));
        QBrush brush91(gradient82);
        palette12.setBrush(QPalette::Active, QPalette::Base, brush91);
        QLinearGradient gradient83(0.464, 1, 0.468, 0);
        gradient83.setSpread(QGradient::PadSpread);
        gradient83.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient83.setColorAt(0.286364, QColor(23, 32, 42, 255));
        gradient83.setColorAt(0.681818, QColor(79, 112, 123, 255));
        QBrush brush92(gradient83);
        palette12.setBrush(QPalette::Active, QPalette::Window, brush92);
        palette12.setBrush(QPalette::Active, QPalette::Shadow, brush1);
        palette12.setBrush(QPalette::Active, QPalette::AlternateBase, brush6);
        palette12.setBrush(QPalette::Active, QPalette::ToolTipBase, brush2);
        palette12.setBrush(QPalette::Active, QPalette::ToolTipText, brush1);
        palette12.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        QLinearGradient gradient84(0.464, 1, 0.468, 0);
        gradient84.setSpread(QGradient::PadSpread);
        gradient84.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient84.setColorAt(0.286364, QColor(23, 32, 42, 255));
        gradient84.setColorAt(0.681818, QColor(79, 112, 123, 255));
        QBrush brush93(gradient84);
        palette12.setBrush(QPalette::Inactive, QPalette::Button, brush93);
        palette12.setBrush(QPalette::Inactive, QPalette::Light, brush4);
        palette12.setBrush(QPalette::Inactive, QPalette::Midlight, brush5);
        palette12.setBrush(QPalette::Inactive, QPalette::Dark, brush6);
        palette12.setBrush(QPalette::Inactive, QPalette::Mid, brush7);
        palette12.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette12.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette12.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        QLinearGradient gradient85(0.464, 1, 0.468, 0);
        gradient85.setSpread(QGradient::PadSpread);
        gradient85.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient85.setColorAt(0.286364, QColor(23, 32, 42, 255));
        gradient85.setColorAt(0.681818, QColor(79, 112, 123, 255));
        QBrush brush94(gradient85);
        palette12.setBrush(QPalette::Inactive, QPalette::Base, brush94);
        QLinearGradient gradient86(0.464, 1, 0.468, 0);
        gradient86.setSpread(QGradient::PadSpread);
        gradient86.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient86.setColorAt(0.286364, QColor(23, 32, 42, 255));
        gradient86.setColorAt(0.681818, QColor(79, 112, 123, 255));
        QBrush brush95(gradient86);
        palette12.setBrush(QPalette::Inactive, QPalette::Window, brush95);
        palette12.setBrush(QPalette::Inactive, QPalette::Shadow, brush1);
        palette12.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush6);
        palette12.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush2);
        palette12.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush1);
        palette12.setBrush(QPalette::Disabled, QPalette::WindowText, brush6);
        QLinearGradient gradient87(0.464, 1, 0.468, 0);
        gradient87.setSpread(QGradient::PadSpread);
        gradient87.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient87.setColorAt(0.286364, QColor(23, 32, 42, 255));
        gradient87.setColorAt(0.681818, QColor(79, 112, 123, 255));
        QBrush brush96(gradient87);
        palette12.setBrush(QPalette::Disabled, QPalette::Button, brush96);
        palette12.setBrush(QPalette::Disabled, QPalette::Light, brush4);
        palette12.setBrush(QPalette::Disabled, QPalette::Midlight, brush5);
        palette12.setBrush(QPalette::Disabled, QPalette::Dark, brush6);
        palette12.setBrush(QPalette::Disabled, QPalette::Mid, brush7);
        palette12.setBrush(QPalette::Disabled, QPalette::Text, brush6);
        palette12.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette12.setBrush(QPalette::Disabled, QPalette::ButtonText, brush6);
        QLinearGradient gradient88(0.464, 1, 0.468, 0);
        gradient88.setSpread(QGradient::PadSpread);
        gradient88.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient88.setColorAt(0.286364, QColor(23, 32, 42, 255));
        gradient88.setColorAt(0.681818, QColor(79, 112, 123, 255));
        QBrush brush97(gradient88);
        palette12.setBrush(QPalette::Disabled, QPalette::Base, brush97);
        QLinearGradient gradient89(0.464, 1, 0.468, 0);
        gradient89.setSpread(QGradient::PadSpread);
        gradient89.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient89.setColorAt(0.286364, QColor(23, 32, 42, 255));
        gradient89.setColorAt(0.681818, QColor(79, 112, 123, 255));
        QBrush brush98(gradient89);
        palette12.setBrush(QPalette::Disabled, QPalette::Window, brush98);
        palette12.setBrush(QPalette::Disabled, QPalette::Shadow, brush1);
        palette12.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush8);
        palette12.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush2);
        palette12.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush1);
        btnDelete->setPalette(palette12);
        btnDelete->setFont(font1);
        btnDelete->setFocusPolicy(Qt::NoFocus);
        btnDelete->setStyleSheet(QStringLiteral("background-color: qlineargradient(spread:pad, x1:0.464, y1:1, x2:0.468, y2:0, stop:0.286364 rgba(23, 32, 42, 255), stop:0.681818 rgba(79, 112, 123, 255));"));
        btn9 = new QPushButton(grbbtn);
        btn9->setObjectName(QStringLiteral("btn9"));
        btn9->setGeometry(QRect(20, 150, 90, 60));
        QPalette palette13;
        palette13.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QLinearGradient gradient90(0.464, 1, 0.468, 0);
        gradient90.setSpread(QGradient::PadSpread);
        gradient90.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient90.setColorAt(0.286364, QColor(23, 32, 42, 255));
        gradient90.setColorAt(0.681818, QColor(79, 112, 123, 255));
        QBrush brush99(gradient90);
        palette13.setBrush(QPalette::Active, QPalette::Button, brush99);
        palette13.setBrush(QPalette::Active, QPalette::Light, brush4);
        palette13.setBrush(QPalette::Active, QPalette::Midlight, brush5);
        palette13.setBrush(QPalette::Active, QPalette::Dark, brush6);
        palette13.setBrush(QPalette::Active, QPalette::Mid, brush7);
        palette13.setBrush(QPalette::Active, QPalette::Text, brush);
        palette13.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette13.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        QLinearGradient gradient91(0.464, 1, 0.468, 0);
        gradient91.setSpread(QGradient::PadSpread);
        gradient91.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient91.setColorAt(0.286364, QColor(23, 32, 42, 255));
        gradient91.setColorAt(0.681818, QColor(79, 112, 123, 255));
        QBrush brush100(gradient91);
        palette13.setBrush(QPalette::Active, QPalette::Base, brush100);
        QLinearGradient gradient92(0.464, 1, 0.468, 0);
        gradient92.setSpread(QGradient::PadSpread);
        gradient92.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient92.setColorAt(0.286364, QColor(23, 32, 42, 255));
        gradient92.setColorAt(0.681818, QColor(79, 112, 123, 255));
        QBrush brush101(gradient92);
        palette13.setBrush(QPalette::Active, QPalette::Window, brush101);
        palette13.setBrush(QPalette::Active, QPalette::Shadow, brush1);
        palette13.setBrush(QPalette::Active, QPalette::AlternateBase, brush6);
        palette13.setBrush(QPalette::Active, QPalette::ToolTipBase, brush2);
        palette13.setBrush(QPalette::Active, QPalette::ToolTipText, brush1);
        palette13.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        QLinearGradient gradient93(0.464, 1, 0.468, 0);
        gradient93.setSpread(QGradient::PadSpread);
        gradient93.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient93.setColorAt(0.286364, QColor(23, 32, 42, 255));
        gradient93.setColorAt(0.681818, QColor(79, 112, 123, 255));
        QBrush brush102(gradient93);
        palette13.setBrush(QPalette::Inactive, QPalette::Button, brush102);
        palette13.setBrush(QPalette::Inactive, QPalette::Light, brush4);
        palette13.setBrush(QPalette::Inactive, QPalette::Midlight, brush5);
        palette13.setBrush(QPalette::Inactive, QPalette::Dark, brush6);
        palette13.setBrush(QPalette::Inactive, QPalette::Mid, brush7);
        palette13.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette13.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette13.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        QLinearGradient gradient94(0.464, 1, 0.468, 0);
        gradient94.setSpread(QGradient::PadSpread);
        gradient94.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient94.setColorAt(0.286364, QColor(23, 32, 42, 255));
        gradient94.setColorAt(0.681818, QColor(79, 112, 123, 255));
        QBrush brush103(gradient94);
        palette13.setBrush(QPalette::Inactive, QPalette::Base, brush103);
        QLinearGradient gradient95(0.464, 1, 0.468, 0);
        gradient95.setSpread(QGradient::PadSpread);
        gradient95.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient95.setColorAt(0.286364, QColor(23, 32, 42, 255));
        gradient95.setColorAt(0.681818, QColor(79, 112, 123, 255));
        QBrush brush104(gradient95);
        palette13.setBrush(QPalette::Inactive, QPalette::Window, brush104);
        palette13.setBrush(QPalette::Inactive, QPalette::Shadow, brush1);
        palette13.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush6);
        palette13.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush2);
        palette13.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush1);
        palette13.setBrush(QPalette::Disabled, QPalette::WindowText, brush6);
        QLinearGradient gradient96(0.464, 1, 0.468, 0);
        gradient96.setSpread(QGradient::PadSpread);
        gradient96.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient96.setColorAt(0.286364, QColor(23, 32, 42, 255));
        gradient96.setColorAt(0.681818, QColor(79, 112, 123, 255));
        QBrush brush105(gradient96);
        palette13.setBrush(QPalette::Disabled, QPalette::Button, brush105);
        palette13.setBrush(QPalette::Disabled, QPalette::Light, brush4);
        palette13.setBrush(QPalette::Disabled, QPalette::Midlight, brush5);
        palette13.setBrush(QPalette::Disabled, QPalette::Dark, brush6);
        palette13.setBrush(QPalette::Disabled, QPalette::Mid, brush7);
        palette13.setBrush(QPalette::Disabled, QPalette::Text, brush6);
        palette13.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette13.setBrush(QPalette::Disabled, QPalette::ButtonText, brush6);
        QLinearGradient gradient97(0.464, 1, 0.468, 0);
        gradient97.setSpread(QGradient::PadSpread);
        gradient97.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient97.setColorAt(0.286364, QColor(23, 32, 42, 255));
        gradient97.setColorAt(0.681818, QColor(79, 112, 123, 255));
        QBrush brush106(gradient97);
        palette13.setBrush(QPalette::Disabled, QPalette::Base, brush106);
        QLinearGradient gradient98(0.464, 1, 0.468, 0);
        gradient98.setSpread(QGradient::PadSpread);
        gradient98.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient98.setColorAt(0.286364, QColor(23, 32, 42, 255));
        gradient98.setColorAt(0.681818, QColor(79, 112, 123, 255));
        QBrush brush107(gradient98);
        palette13.setBrush(QPalette::Disabled, QPalette::Window, brush107);
        palette13.setBrush(QPalette::Disabled, QPalette::Shadow, brush1);
        palette13.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush8);
        palette13.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush2);
        palette13.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush1);
        btn9->setPalette(palette13);
        btn9->setFont(font2);
        btn9->setFocusPolicy(Qt::NoFocus);
        btn9->setStyleSheet(QStringLiteral("background-color: qlineargradient(spread:pad, x1:0.464, y1:1, x2:0.468, y2:0, stop:0.286364 rgba(23, 32, 42, 255), stop:0.681818 rgba(79, 112, 123, 255));"));
        label_25 = new QLabel(PassWordDialog);
        label_25->setObjectName(QStringLiteral("label_25"));
        label_25->setGeometry(QRect(150, 40, 131, 61));
        label_25->setFont(font1);
        label_25->setStyleSheet(QStringLiteral("background-color: qlineargradient(spread:reflect, x1:0.932, y1:0, x2:0.733, y2:1, stop:0 rgba(194, 205, 209, 255), stop:0.590909 rgba(143, 163, 171, 255));"));
        label_25->setFrameShape(QFrame::Box);
        label_25->setAlignment(Qt::AlignCenter);
        Txtpassword = new QLineEdit(PassWordDialog);
        Txtpassword->setObjectName(QStringLiteral("Txtpassword"));
        Txtpassword->setGeometry(QRect(280, 40, 261, 61));
        QPalette palette14;
        palette14.setBrush(QPalette::Active, QPalette::WindowText, brush1);
        QBrush brush108(QColor(194, 205, 209, 255));
        brush108.setStyle(Qt::SolidPattern);
        palette14.setBrush(QPalette::Active, QPalette::Button, brush108);
        palette14.setBrush(QPalette::Active, QPalette::Light, brush);
        palette14.setBrush(QPalette::Active, QPalette::Midlight, brush);
        palette14.setBrush(QPalette::Active, QPalette::Dark, brush8);
        QBrush brush109(QColor(170, 170, 170, 255));
        brush109.setStyle(Qt::SolidPattern);
        palette14.setBrush(QPalette::Active, QPalette::Mid, brush109);
        palette14.setBrush(QPalette::Active, QPalette::Text, brush1);
        palette14.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette14.setBrush(QPalette::Active, QPalette::ButtonText, brush1);
        palette14.setBrush(QPalette::Active, QPalette::Base, brush108);
        palette14.setBrush(QPalette::Active, QPalette::Window, brush108);
        palette14.setBrush(QPalette::Active, QPalette::Shadow, brush1);
        palette14.setBrush(QPalette::Active, QPalette::AlternateBase, brush);
        palette14.setBrush(QPalette::Active, QPalette::ToolTipBase, brush2);
        palette14.setBrush(QPalette::Active, QPalette::ToolTipText, brush1);
        palette14.setBrush(QPalette::Inactive, QPalette::WindowText, brush1);
        palette14.setBrush(QPalette::Inactive, QPalette::Button, brush108);
        palette14.setBrush(QPalette::Inactive, QPalette::Light, brush);
        palette14.setBrush(QPalette::Inactive, QPalette::Midlight, brush);
        palette14.setBrush(QPalette::Inactive, QPalette::Dark, brush8);
        palette14.setBrush(QPalette::Inactive, QPalette::Mid, brush109);
        palette14.setBrush(QPalette::Inactive, QPalette::Text, brush1);
        palette14.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette14.setBrush(QPalette::Inactive, QPalette::ButtonText, brush1);
        palette14.setBrush(QPalette::Inactive, QPalette::Base, brush108);
        palette14.setBrush(QPalette::Inactive, QPalette::Window, brush108);
        palette14.setBrush(QPalette::Inactive, QPalette::Shadow, brush1);
        palette14.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush);
        palette14.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush2);
        palette14.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush1);
        palette14.setBrush(QPalette::Disabled, QPalette::WindowText, brush8);
        palette14.setBrush(QPalette::Disabled, QPalette::Button, brush108);
        palette14.setBrush(QPalette::Disabled, QPalette::Light, brush);
        palette14.setBrush(QPalette::Disabled, QPalette::Midlight, brush);
        palette14.setBrush(QPalette::Disabled, QPalette::Dark, brush8);
        palette14.setBrush(QPalette::Disabled, QPalette::Mid, brush109);
        palette14.setBrush(QPalette::Disabled, QPalette::Text, brush8);
        palette14.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette14.setBrush(QPalette::Disabled, QPalette::ButtonText, brush8);
        palette14.setBrush(QPalette::Disabled, QPalette::Base, brush108);
        palette14.setBrush(QPalette::Disabled, QPalette::Window, brush108);
        palette14.setBrush(QPalette::Disabled, QPalette::Shadow, brush1);
        palette14.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush);
        palette14.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush2);
        palette14.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush1);
        Txtpassword->setPalette(palette14);
        QFont font3;
        font3.setPointSize(22);
        font3.setBold(true);
        font3.setWeight(75);
        Txtpassword->setFont(font3);
        Txtpassword->setFocusPolicy(Qt::WheelFocus);
        Txtpassword->setStyleSheet(QStringLiteral("background-color: rgb(194, 205, 209);"));
        Txtpassword->setCursorPosition(0);
        labwarn = new QLabel(PassWordDialog);
        labwarn->setObjectName(QStringLiteral("labwarn"));
        labwarn->setGeometry(QRect(150, 340, 201, 41));
        QPalette palette15;
        QBrush brush110(QColor(255, 0, 0, 255));
        brush110.setStyle(Qt::SolidPattern);
        palette15.setBrush(QPalette::Active, QPalette::WindowText, brush110);
        palette15.setBrush(QPalette::Active, QPalette::Text, brush110);
        palette15.setBrush(QPalette::Inactive, QPalette::WindowText, brush110);
        palette15.setBrush(QPalette::Inactive, QPalette::Text, brush110);
        palette15.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette15.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        labwarn->setPalette(palette15);
        labwarn->setFont(font1);

        retranslateUi(PassWordDialog);

        QMetaObject::connectSlotsByName(PassWordDialog);
    } // setupUi

    void retranslateUi(QDialog *PassWordDialog)
    {
        PassWordDialog->setWindowTitle(QApplication::translate("PassWordDialog", "\345\257\206\347\240\201\351\252\214\350\257\201", 0));
        btnOK->setText(QApplication::translate("PassWordDialog", "\347\241\256\350\256\244", 0));
        btn_Cancel->setText(QApplication::translate("PassWordDialog", "\345\217\226\346\266\210", 0));
        grbbtn->setTitle(QString());
        btn2->setText(QApplication::translate("PassWordDialog", "2", 0));
        btn0->setText(QApplication::translate("PassWordDialog", "0", 0));
        btn3->setText(QApplication::translate("PassWordDialog", "3", 0));
        btn1->setText(QApplication::translate("PassWordDialog", "1", 0));
        btn6->setText(QApplication::translate("PassWordDialog", "6", 0));
        btn5->setText(QApplication::translate("PassWordDialog", "5", 0));
        btn8->setText(QApplication::translate("PassWordDialog", "8", 0));
        btn7->setText(QApplication::translate("PassWordDialog", "7", 0));
        btn4->setText(QApplication::translate("PassWordDialog", "4", 0));
        btnDelete->setText(QApplication::translate("PassWordDialog", "\345\210\240\351\231\244", 0));
        btn9->setText(QApplication::translate("PassWordDialog", "9", 0));
        label_25->setText(QApplication::translate("PassWordDialog", "\345\257\206\347\240\201", 0));
        Txtpassword->setText(QString());
        labwarn->setText(QApplication::translate("PassWordDialog", "\345\257\206\347\240\201\350\276\223\345\205\245\351\224\231\350\257\257", 0));
    } // retranslateUi

};

namespace Ui {
    class PassWordDialog: public Ui_PassWordDialog {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_PASSWORDDIALOG_H
