/********************************************************************************
** Form generated from reading UI file 'waveform.ui'
**
** Created by: Qt User Interface Compiler version 5.6.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_WAVEFORM_H
#define UI_WAVEFORM_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QWidget>
#include "qwt_plot.h"

QT_BEGIN_NAMESPACE

class Ui_WaveForm
{
public:
    QwtPlot *qwtPlot_ECG2;
    QLabel *lab_ecg2leadtag;
    QLabel *lab_ecg2gaintag;
    QLabel *lab_ECG2lead;
    QLabel *lab_ECG2Gain;
    QGroupBox *groupBox;
    QLabel *lab_ECGSET;
    QGroupBox *gpecgchannel1;
    QLabel *lab_lead1set;
    QLabel *lab_gain1set;
    QPushButton *btnECG1lead;
    QPushButton *btnECG1gain;
    QPushButton *btnECGChanel1;
    QGroupBox *gpecgchannel2;
    QLabel *lab_lead2set;
    QLabel *lab_gain2set;
    QPushButton *btnECG2lead;
    QPushButton *btnECG2gain;
    QPushButton *btnECGChanel2;
    QGroupBox *gpother;
    QPushButton *btnECGModel;
    QPushButton *btnDiagnoseModel;
    QPushButton *btnECGcall;
    QPushButton *btnOther;
    QPushButton *btnLeadswitch;
    QPushButton *btnECGFreeze;
    QwtPlot *qwtPlot_ECG;
    QLabel *lab_HR;
    QLabel *lab_ecg1gaintag;
    QLabel *lab_ecg1leadtag;
    QLabel *lab_hrtag;
    QLabel *lab_ECG1lead;
    QLabel *lab_ECG1Gain;

    void setupUi(QWidget *WaveForm)
    {
        if (WaveForm->objectName().isEmpty())
            WaveForm->setObjectName(QStringLiteral("WaveForm"));
        WaveForm->resize(1366, 768);
        QPalette palette;
        QBrush brush(QColor(255, 255, 255, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QBrush brush1(QColor(0, 0, 0, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette.setBrush(QPalette::Active, QPalette::Light, brush1);
        palette.setBrush(QPalette::Active, QPalette::Midlight, brush1);
        palette.setBrush(QPalette::Active, QPalette::Dark, brush1);
        palette.setBrush(QPalette::Active, QPalette::Mid, brush1);
        palette.setBrush(QPalette::Active, QPalette::Text, brush);
        palette.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette.setBrush(QPalette::Active, QPalette::Shadow, brush1);
        palette.setBrush(QPalette::Active, QPalette::AlternateBase, brush1);
        QBrush brush2(QColor(255, 255, 220, 255));
        brush2.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::ToolTipBase, brush2);
        palette.setBrush(QPalette::Active, QPalette::ToolTipText, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Light, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Midlight, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Dark, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Mid, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Shadow, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush2);
        palette.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Light, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Midlight, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Dark, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Mid, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Shadow, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush1);
        WaveForm->setPalette(palette);
        qwtPlot_ECG2 = new QwtPlot(WaveForm);
        qwtPlot_ECG2->setObjectName(QStringLiteral("qwtPlot_ECG2"));
        qwtPlot_ECG2->setGeometry(QRect(0, 280, 1361, 211));
        QPalette palette1;
        palette1.setBrush(QPalette::Active, QPalette::Base, brush1);
        QBrush brush3(QColor(13, 17, 25, 255));
        brush3.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Window, brush3);
        palette1.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::Window, brush3);
        palette1.setBrush(QPalette::Disabled, QPalette::Base, brush3);
        palette1.setBrush(QPalette::Disabled, QPalette::Window, brush3);
        qwtPlot_ECG2->setPalette(palette1);
        lab_ecg2leadtag = new QLabel(qwtPlot_ECG2);
        lab_ecg2leadtag->setObjectName(QStringLiteral("lab_ecg2leadtag"));
        lab_ecg2leadtag->setGeometry(QRect(10, 10, 101, 31));
        QFont font;
        font.setPointSize(20);
        lab_ecg2leadtag->setFont(font);
        lab_ecg2gaintag = new QLabel(qwtPlot_ECG2);
        lab_ecg2gaintag->setObjectName(QStringLiteral("lab_ecg2gaintag"));
        lab_ecg2gaintag->setGeometry(QRect(210, 10, 91, 31));
        lab_ecg2gaintag->setFont(font);
        lab_ECG2lead = new QLabel(qwtPlot_ECG2);
        lab_ECG2lead->setObjectName(QStringLiteral("lab_ECG2lead"));
        lab_ECG2lead->setGeometry(QRect(90, 10, 91, 31));
        lab_ECG2lead->setFont(font);
        lab_ECG2Gain = new QLabel(qwtPlot_ECG2);
        lab_ECG2Gain->setObjectName(QStringLiteral("lab_ECG2Gain"));
        lab_ECG2Gain->setGeometry(QRect(300, 10, 101, 31));
        lab_ECG2Gain->setFont(font);
        groupBox = new QGroupBox(WaveForm);
        groupBox->setObjectName(QStringLiteral("groupBox"));
        groupBox->setGeometry(QRect(0, 500, 1351, 181));
        QPalette palette2;
        palette2.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette2.setBrush(QPalette::Active, QPalette::Button, brush);
        palette2.setBrush(QPalette::Active, QPalette::Dark, brush);
        palette2.setBrush(QPalette::Active, QPalette::Mid, brush);
        palette2.setBrush(QPalette::Active, QPalette::Text, brush);
        palette2.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette2.setBrush(QPalette::Active, QPalette::Base, brush);
        palette2.setBrush(QPalette::Active, QPalette::Window, brush);
        palette2.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Dark, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Mid, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::WindowText, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::Dark, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::Mid, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::Text, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::ButtonText, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::Window, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        groupBox->setPalette(palette2);
        QFont font1;
        font1.setFamily(QString::fromUtf8("\345\276\256\350\275\257\351\233\205\351\273\221"));
        font1.setPointSize(14);
        font1.setBold(true);
        font1.setWeight(75);
        groupBox->setFont(font1);
        lab_ECGSET = new QLabel(groupBox);
        lab_ECGSET->setObjectName(QStringLiteral("lab_ECGSET"));
        lab_ECGSET->setGeometry(QRect(0, 0, 121, 181));
        QPalette palette3;
        QBrush brush4(QColor(144, 202, 36, 255));
        brush4.setStyle(Qt::SolidPattern);
        palette3.setBrush(QPalette::Active, QPalette::WindowText, brush4);
        QLinearGradient gradient(1, 0.534091, 0, 0.511);
        gradient.setSpread(QGradient::PadSpread);
        gradient.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient.setColorAt(0.477273, QColor(9, 10, 18, 255));
        gradient.setColorAt(0.6, QColor(64, 65, 72, 255));
        QBrush brush5(gradient);
        palette3.setBrush(QPalette::Active, QPalette::Button, brush5);
        QLinearGradient gradient1(1, 0.534091, 0, 0.511);
        gradient1.setSpread(QGradient::PadSpread);
        gradient1.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient1.setColorAt(0.477273, QColor(9, 10, 18, 255));
        gradient1.setColorAt(0.6, QColor(64, 65, 72, 255));
        QBrush brush6(gradient1);
        palette3.setBrush(QPalette::Active, QPalette::Base, brush6);
        QLinearGradient gradient2(1, 0.534091, 0, 0.511);
        gradient2.setSpread(QGradient::PadSpread);
        gradient2.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient2.setColorAt(0.477273, QColor(9, 10, 18, 255));
        gradient2.setColorAt(0.6, QColor(64, 65, 72, 255));
        QBrush brush7(gradient2);
        palette3.setBrush(QPalette::Active, QPalette::Window, brush7);
        palette3.setBrush(QPalette::Inactive, QPalette::WindowText, brush4);
        QLinearGradient gradient3(1, 0.534091, 0, 0.511);
        gradient3.setSpread(QGradient::PadSpread);
        gradient3.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient3.setColorAt(0.477273, QColor(9, 10, 18, 255));
        gradient3.setColorAt(0.6, QColor(64, 65, 72, 255));
        QBrush brush8(gradient3);
        palette3.setBrush(QPalette::Inactive, QPalette::Button, brush8);
        QLinearGradient gradient4(1, 0.534091, 0, 0.511);
        gradient4.setSpread(QGradient::PadSpread);
        gradient4.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient4.setColorAt(0.477273, QColor(9, 10, 18, 255));
        gradient4.setColorAt(0.6, QColor(64, 65, 72, 255));
        QBrush brush9(gradient4);
        palette3.setBrush(QPalette::Inactive, QPalette::Base, brush9);
        QLinearGradient gradient5(1, 0.534091, 0, 0.511);
        gradient5.setSpread(QGradient::PadSpread);
        gradient5.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient5.setColorAt(0.477273, QColor(9, 10, 18, 255));
        gradient5.setColorAt(0.6, QColor(64, 65, 72, 255));
        QBrush brush10(gradient5);
        palette3.setBrush(QPalette::Inactive, QPalette::Window, brush10);
        palette3.setBrush(QPalette::Disabled, QPalette::WindowText, brush);
        QLinearGradient gradient6(1, 0.534091, 0, 0.511);
        gradient6.setSpread(QGradient::PadSpread);
        gradient6.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient6.setColorAt(0.477273, QColor(9, 10, 18, 255));
        gradient6.setColorAt(0.6, QColor(64, 65, 72, 255));
        QBrush brush11(gradient6);
        palette3.setBrush(QPalette::Disabled, QPalette::Button, brush11);
        QLinearGradient gradient7(1, 0.534091, 0, 0.511);
        gradient7.setSpread(QGradient::PadSpread);
        gradient7.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient7.setColorAt(0.477273, QColor(9, 10, 18, 255));
        gradient7.setColorAt(0.6, QColor(64, 65, 72, 255));
        QBrush brush12(gradient7);
        palette3.setBrush(QPalette::Disabled, QPalette::Base, brush12);
        QLinearGradient gradient8(1, 0.534091, 0, 0.511);
        gradient8.setSpread(QGradient::PadSpread);
        gradient8.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient8.setColorAt(0.477273, QColor(9, 10, 18, 255));
        gradient8.setColorAt(0.6, QColor(64, 65, 72, 255));
        QBrush brush13(gradient8);
        palette3.setBrush(QPalette::Disabled, QPalette::Window, brush13);
        lab_ECGSET->setPalette(palette3);
        QFont font2;
        font2.setFamily(QString::fromUtf8("\346\226\207\346\263\211\351\251\233\347\255\211\345\257\254\345\276\256\347\261\263\351\273\221"));
        font2.setPointSize(36);
        font2.setBold(false);
        font2.setWeight(50);
        lab_ECGSET->setFont(font2);
        lab_ECGSET->setStyleSheet(QStringLiteral("background-color: qlineargradient(spread:pad, x1:1, y1:0.534091, x2:0, y2:0.511, stop:0.477273 rgba(9, 10, 18, 255), stop:0.6 rgba(64, 65, 72, 255));"));
        lab_ECGSET->setFrameShape(QFrame::Box);
        lab_ECGSET->setAlignment(Qt::AlignCenter);
        gpecgchannel1 = new QGroupBox(groupBox);
        gpecgchannel1->setObjectName(QStringLiteral("gpecgchannel1"));
        gpecgchannel1->setGeometry(QRect(120, 0, 371, 180));
        QPalette palette4;
        palette4.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette4.setBrush(QPalette::Active, QPalette::Button, brush);
        palette4.setBrush(QPalette::Active, QPalette::Light, brush);
        palette4.setBrush(QPalette::Active, QPalette::Midlight, brush);
        palette4.setBrush(QPalette::Active, QPalette::Dark, brush);
        palette4.setBrush(QPalette::Active, QPalette::Mid, brush);
        QBrush brush14(QColor(127, 127, 127, 127));
        brush14.setStyle(Qt::SolidPattern);
        palette4.setBrush(QPalette::Active, QPalette::Text, brush14);
        palette4.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette4.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette4.setBrush(QPalette::Active, QPalette::Base, brush);
        palette4.setBrush(QPalette::Active, QPalette::Window, brush);
        palette4.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette4.setBrush(QPalette::Active, QPalette::AlternateBase, brush);
        palette4.setBrush(QPalette::Active, QPalette::ToolTipBase, brush2);
        palette4.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::Light, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::Midlight, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::Dark, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::Mid, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::Text, brush14);
        palette4.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush2);
        palette4.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::WindowText, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::Light, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::Midlight, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::Dark, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::Mid, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::Text, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::ButtonText, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::Window, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush2);
        palette4.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        gpecgchannel1->setPalette(palette4);
        QFont font3;
        font3.setFamily(QString::fromUtf8("\346\226\207\346\263\211\351\251\233\347\255\211\345\257\254\345\276\256\347\261\263\351\273\221"));
        font3.setPointSize(20);
        font3.setBold(false);
        font3.setWeight(50);
        gpecgchannel1->setFont(font3);
        lab_lead1set = new QLabel(gpecgchannel1);
        lab_lead1set->setObjectName(QStringLiteral("lab_lead1set"));
        lab_lead1set->setGeometry(QRect(20, 75, 111, 31));
        lab_lead1set->setFont(font);
        lab_gain1set = new QLabel(gpecgchannel1);
        lab_gain1set->setObjectName(QStringLiteral("lab_gain1set"));
        lab_gain1set->setGeometry(QRect(20, 135, 111, 31));
        lab_gain1set->setFont(font);
        btnECG1lead = new QPushButton(gpecgchannel1);
        btnECG1lead->setObjectName(QStringLiteral("btnECG1lead"));
        btnECG1lead->setGeometry(QRect(150, 70, 181, 41));
        QPalette palette5;
        palette5.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QBrush brush15(QColor(127, 127, 127, 255));
        brush15.setStyle(Qt::SolidPattern);
        palette5.setBrush(QPalette::Active, QPalette::Button, brush15);
        QBrush brush16(QColor(191, 191, 191, 255));
        brush16.setStyle(Qt::SolidPattern);
        palette5.setBrush(QPalette::Active, QPalette::Light, brush16);
        QBrush brush17(QColor(159, 159, 159, 255));
        brush17.setStyle(Qt::SolidPattern);
        palette5.setBrush(QPalette::Active, QPalette::Midlight, brush17);
        QBrush brush18(QColor(63, 63, 63, 255));
        brush18.setStyle(Qt::SolidPattern);
        palette5.setBrush(QPalette::Active, QPalette::Dark, brush18);
        QBrush brush19(QColor(84, 84, 84, 255));
        brush19.setStyle(Qt::SolidPattern);
        palette5.setBrush(QPalette::Active, QPalette::Mid, brush19);
        palette5.setBrush(QPalette::Active, QPalette::Text, brush);
        palette5.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette5.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette5.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette5.setBrush(QPalette::Active, QPalette::Window, brush15);
        palette5.setBrush(QPalette::Active, QPalette::Shadow, brush1);
        palette5.setBrush(QPalette::Active, QPalette::AlternateBase, brush18);
        palette5.setBrush(QPalette::Active, QPalette::ToolTipBase, brush2);
        palette5.setBrush(QPalette::Active, QPalette::ToolTipText, brush1);
        palette5.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::Button, brush15);
        palette5.setBrush(QPalette::Inactive, QPalette::Light, brush16);
        palette5.setBrush(QPalette::Inactive, QPalette::Midlight, brush17);
        palette5.setBrush(QPalette::Inactive, QPalette::Dark, brush18);
        palette5.setBrush(QPalette::Inactive, QPalette::Mid, brush19);
        palette5.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette5.setBrush(QPalette::Inactive, QPalette::Window, brush15);
        palette5.setBrush(QPalette::Inactive, QPalette::Shadow, brush1);
        palette5.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush18);
        palette5.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush2);
        palette5.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush1);
        palette5.setBrush(QPalette::Disabled, QPalette::WindowText, brush18);
        palette5.setBrush(QPalette::Disabled, QPalette::Button, brush15);
        palette5.setBrush(QPalette::Disabled, QPalette::Light, brush16);
        palette5.setBrush(QPalette::Disabled, QPalette::Midlight, brush17);
        palette5.setBrush(QPalette::Disabled, QPalette::Dark, brush18);
        palette5.setBrush(QPalette::Disabled, QPalette::Mid, brush19);
        palette5.setBrush(QPalette::Disabled, QPalette::Text, brush18);
        palette5.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette5.setBrush(QPalette::Disabled, QPalette::ButtonText, brush18);
        palette5.setBrush(QPalette::Disabled, QPalette::Base, brush15);
        palette5.setBrush(QPalette::Disabled, QPalette::Window, brush15);
        palette5.setBrush(QPalette::Disabled, QPalette::Shadow, brush1);
        palette5.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush15);
        palette5.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush2);
        palette5.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush1);
        btnECG1lead->setPalette(palette5);
        QFont font4;
        font4.setFamily(QString::fromUtf8("\346\226\207\346\263\211\351\251\233\347\255\211\345\257\254\345\276\256\347\261\263\351\273\221"));
        font4.setPointSize(20);
        btnECG1lead->setFont(font4);
        btnECG1lead->setFocusPolicy(Qt::NoFocus);
        btnECG1lead->setStyleSheet(QStringLiteral("border-image: url(:/rsc/images/btnecg.png);"));
        btnECG1gain = new QPushButton(gpecgchannel1);
        btnECG1gain->setObjectName(QStringLiteral("btnECG1gain"));
        btnECG1gain->setGeometry(QRect(150, 130, 171, 41));
        QPalette palette6;
        palette6.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette6.setBrush(QPalette::Active, QPalette::Button, brush15);
        palette6.setBrush(QPalette::Active, QPalette::Light, brush16);
        palette6.setBrush(QPalette::Active, QPalette::Midlight, brush17);
        palette6.setBrush(QPalette::Active, QPalette::Dark, brush18);
        palette6.setBrush(QPalette::Active, QPalette::Mid, brush19);
        palette6.setBrush(QPalette::Active, QPalette::Text, brush);
        palette6.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette6.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette6.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette6.setBrush(QPalette::Active, QPalette::Window, brush15);
        palette6.setBrush(QPalette::Active, QPalette::Shadow, brush1);
        palette6.setBrush(QPalette::Active, QPalette::AlternateBase, brush18);
        palette6.setBrush(QPalette::Active, QPalette::ToolTipBase, brush2);
        palette6.setBrush(QPalette::Active, QPalette::ToolTipText, brush1);
        palette6.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::Button, brush15);
        palette6.setBrush(QPalette::Inactive, QPalette::Light, brush16);
        palette6.setBrush(QPalette::Inactive, QPalette::Midlight, brush17);
        palette6.setBrush(QPalette::Inactive, QPalette::Dark, brush18);
        palette6.setBrush(QPalette::Inactive, QPalette::Mid, brush19);
        palette6.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette6.setBrush(QPalette::Inactive, QPalette::Window, brush15);
        palette6.setBrush(QPalette::Inactive, QPalette::Shadow, brush1);
        palette6.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush18);
        palette6.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush2);
        palette6.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush1);
        palette6.setBrush(QPalette::Disabled, QPalette::WindowText, brush18);
        palette6.setBrush(QPalette::Disabled, QPalette::Button, brush15);
        palette6.setBrush(QPalette::Disabled, QPalette::Light, brush16);
        palette6.setBrush(QPalette::Disabled, QPalette::Midlight, brush17);
        palette6.setBrush(QPalette::Disabled, QPalette::Dark, brush18);
        palette6.setBrush(QPalette::Disabled, QPalette::Mid, brush19);
        palette6.setBrush(QPalette::Disabled, QPalette::Text, brush18);
        palette6.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette6.setBrush(QPalette::Disabled, QPalette::ButtonText, brush18);
        palette6.setBrush(QPalette::Disabled, QPalette::Base, brush15);
        palette6.setBrush(QPalette::Disabled, QPalette::Window, brush15);
        palette6.setBrush(QPalette::Disabled, QPalette::Shadow, brush1);
        palette6.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush15);
        palette6.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush2);
        palette6.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush1);
        btnECG1gain->setPalette(palette6);
        btnECG1gain->setFocusPolicy(Qt::NoFocus);
        btnECG1gain->setStyleSheet(QStringLiteral("border-image: url(:/rsc/images/btnecg.png);"));
        btnECGChanel1 = new QPushButton(gpecgchannel1);
        btnECGChanel1->setObjectName(QStringLiteral("btnECGChanel1"));
        btnECGChanel1->setGeometry(QRect(0, 0, 371, 50));
        QPalette palette7;
        palette7.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QLinearGradient gradient9(0.5, 1, 0.463636, 0);
        gradient9.setSpread(QGradient::PadSpread);
        gradient9.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient9.setColorAt(0.290909, QColor(25, 30, 46, 255));
        gradient9.setColorAt(0.540909, QColor(70, 72, 93, 255));
        QBrush brush20(gradient9);
        palette7.setBrush(QPalette::Active, QPalette::Button, brush20);
        palette7.setBrush(QPalette::Active, QPalette::Light, brush16);
        palette7.setBrush(QPalette::Active, QPalette::Midlight, brush17);
        palette7.setBrush(QPalette::Active, QPalette::Dark, brush18);
        palette7.setBrush(QPalette::Active, QPalette::Mid, brush19);
        palette7.setBrush(QPalette::Active, QPalette::Text, brush);
        palette7.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette7.setBrush(QPalette::Active, QPalette::ButtonText, brush4);
        QLinearGradient gradient10(0.5, 1, 0.463636, 0);
        gradient10.setSpread(QGradient::PadSpread);
        gradient10.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient10.setColorAt(0.290909, QColor(25, 30, 46, 255));
        gradient10.setColorAt(0.540909, QColor(70, 72, 93, 255));
        QBrush brush21(gradient10);
        palette7.setBrush(QPalette::Active, QPalette::Base, brush21);
        QLinearGradient gradient11(0.5, 1, 0.463636, 0);
        gradient11.setSpread(QGradient::PadSpread);
        gradient11.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient11.setColorAt(0.290909, QColor(25, 30, 46, 255));
        gradient11.setColorAt(0.540909, QColor(70, 72, 93, 255));
        QBrush brush22(gradient11);
        palette7.setBrush(QPalette::Active, QPalette::Window, brush22);
        palette7.setBrush(QPalette::Active, QPalette::Shadow, brush15);
        palette7.setBrush(QPalette::Active, QPalette::AlternateBase, brush18);
        palette7.setBrush(QPalette::Active, QPalette::ToolTipBase, brush2);
        palette7.setBrush(QPalette::Active, QPalette::ToolTipText, brush1);
        palette7.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        QLinearGradient gradient12(0.5, 1, 0.463636, 0);
        gradient12.setSpread(QGradient::PadSpread);
        gradient12.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient12.setColorAt(0.290909, QColor(25, 30, 46, 255));
        gradient12.setColorAt(0.540909, QColor(70, 72, 93, 255));
        QBrush brush23(gradient12);
        palette7.setBrush(QPalette::Inactive, QPalette::Button, brush23);
        palette7.setBrush(QPalette::Inactive, QPalette::Light, brush16);
        palette7.setBrush(QPalette::Inactive, QPalette::Midlight, brush17);
        palette7.setBrush(QPalette::Inactive, QPalette::Dark, brush18);
        palette7.setBrush(QPalette::Inactive, QPalette::Mid, brush19);
        palette7.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette7.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette7.setBrush(QPalette::Inactive, QPalette::ButtonText, brush4);
        QLinearGradient gradient13(0.5, 1, 0.463636, 0);
        gradient13.setSpread(QGradient::PadSpread);
        gradient13.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient13.setColorAt(0.290909, QColor(25, 30, 46, 255));
        gradient13.setColorAt(0.540909, QColor(70, 72, 93, 255));
        QBrush brush24(gradient13);
        palette7.setBrush(QPalette::Inactive, QPalette::Base, brush24);
        QLinearGradient gradient14(0.5, 1, 0.463636, 0);
        gradient14.setSpread(QGradient::PadSpread);
        gradient14.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient14.setColorAt(0.290909, QColor(25, 30, 46, 255));
        gradient14.setColorAt(0.540909, QColor(70, 72, 93, 255));
        QBrush brush25(gradient14);
        palette7.setBrush(QPalette::Inactive, QPalette::Window, brush25);
        palette7.setBrush(QPalette::Inactive, QPalette::Shadow, brush15);
        palette7.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush18);
        palette7.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush2);
        palette7.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush1);
        palette7.setBrush(QPalette::Disabled, QPalette::WindowText, brush18);
        QLinearGradient gradient15(0.5, 1, 0.463636, 0);
        gradient15.setSpread(QGradient::PadSpread);
        gradient15.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient15.setColorAt(0.290909, QColor(25, 30, 46, 255));
        gradient15.setColorAt(0.540909, QColor(70, 72, 93, 255));
        QBrush brush26(gradient15);
        palette7.setBrush(QPalette::Disabled, QPalette::Button, brush26);
        palette7.setBrush(QPalette::Disabled, QPalette::Light, brush16);
        palette7.setBrush(QPalette::Disabled, QPalette::Midlight, brush17);
        palette7.setBrush(QPalette::Disabled, QPalette::Dark, brush18);
        palette7.setBrush(QPalette::Disabled, QPalette::Mid, brush19);
        palette7.setBrush(QPalette::Disabled, QPalette::Text, brush18);
        palette7.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette7.setBrush(QPalette::Disabled, QPalette::ButtonText, brush18);
        QLinearGradient gradient16(0.5, 1, 0.463636, 0);
        gradient16.setSpread(QGradient::PadSpread);
        gradient16.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient16.setColorAt(0.290909, QColor(25, 30, 46, 255));
        gradient16.setColorAt(0.540909, QColor(70, 72, 93, 255));
        QBrush brush27(gradient16);
        palette7.setBrush(QPalette::Disabled, QPalette::Base, brush27);
        QLinearGradient gradient17(0.5, 1, 0.463636, 0);
        gradient17.setSpread(QGradient::PadSpread);
        gradient17.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient17.setColorAt(0.290909, QColor(25, 30, 46, 255));
        gradient17.setColorAt(0.540909, QColor(70, 72, 93, 255));
        QBrush brush28(gradient17);
        palette7.setBrush(QPalette::Disabled, QPalette::Window, brush28);
        palette7.setBrush(QPalette::Disabled, QPalette::Shadow, brush15);
        palette7.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush15);
        palette7.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush2);
        palette7.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush1);
        btnECGChanel1->setPalette(palette7);
        QFont font5;
        font5.setPointSize(28);
        btnECGChanel1->setFont(font5);
        btnECGChanel1->setFocusPolicy(Qt::NoFocus);
        btnECGChanel1->setStyleSheet(QStringLiteral("background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.463636, y2:0, stop:0.290909 rgba(25, 30, 46, 255), stop:0.540909 rgba(70, 72, 93, 255));"));
        gpecgchannel2 = new QGroupBox(groupBox);
        gpecgchannel2->setObjectName(QStringLiteral("gpecgchannel2"));
        gpecgchannel2->setGeometry(QRect(490, 0, 371, 180));
        QPalette palette8;
        palette8.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette8.setBrush(QPalette::Active, QPalette::Button, brush);
        palette8.setBrush(QPalette::Active, QPalette::Light, brush);
        palette8.setBrush(QPalette::Active, QPalette::Midlight, brush);
        palette8.setBrush(QPalette::Active, QPalette::Dark, brush);
        palette8.setBrush(QPalette::Active, QPalette::Mid, brush);
        palette8.setBrush(QPalette::Active, QPalette::Text, brush);
        palette8.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette8.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette8.setBrush(QPalette::Active, QPalette::Base, brush);
        palette8.setBrush(QPalette::Active, QPalette::Window, brush);
        palette8.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette8.setBrush(QPalette::Active, QPalette::AlternateBase, brush);
        palette8.setBrush(QPalette::Active, QPalette::ToolTipBase, brush2);
        palette8.setBrush(QPalette::Active, QPalette::ToolTipText, brush1);
        palette8.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::Light, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::Midlight, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::Dark, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::Mid, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush2);
        palette8.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush1);
        palette8.setBrush(QPalette::Disabled, QPalette::WindowText, brush);
        palette8.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette8.setBrush(QPalette::Disabled, QPalette::Light, brush);
        palette8.setBrush(QPalette::Disabled, QPalette::Midlight, brush);
        palette8.setBrush(QPalette::Disabled, QPalette::Dark, brush);
        palette8.setBrush(QPalette::Disabled, QPalette::Mid, brush);
        palette8.setBrush(QPalette::Disabled, QPalette::Text, brush);
        palette8.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette8.setBrush(QPalette::Disabled, QPalette::ButtonText, brush);
        palette8.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette8.setBrush(QPalette::Disabled, QPalette::Window, brush);
        palette8.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette8.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush);
        palette8.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush2);
        palette8.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush1);
        gpecgchannel2->setPalette(palette8);
        gpecgchannel2->setFont(font3);
        lab_lead2set = new QLabel(gpecgchannel2);
        lab_lead2set->setObjectName(QStringLiteral("lab_lead2set"));
        lab_lead2set->setGeometry(QRect(20, 75, 111, 31));
        lab_lead2set->setFont(font);
        lab_gain2set = new QLabel(gpecgchannel2);
        lab_gain2set->setObjectName(QStringLiteral("lab_gain2set"));
        lab_gain2set->setGeometry(QRect(20, 135, 111, 31));
        lab_gain2set->setFont(font);
        btnECG2lead = new QPushButton(gpecgchannel2);
        btnECG2lead->setObjectName(QStringLiteral("btnECG2lead"));
        btnECG2lead->setGeometry(QRect(160, 70, 181, 41));
        QPalette palette9;
        palette9.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette9.setBrush(QPalette::Active, QPalette::Button, brush15);
        palette9.setBrush(QPalette::Active, QPalette::Light, brush16);
        palette9.setBrush(QPalette::Active, QPalette::Midlight, brush17);
        palette9.setBrush(QPalette::Active, QPalette::Dark, brush18);
        palette9.setBrush(QPalette::Active, QPalette::Mid, brush19);
        palette9.setBrush(QPalette::Active, QPalette::Text, brush);
        palette9.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette9.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette9.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette9.setBrush(QPalette::Active, QPalette::Window, brush15);
        palette9.setBrush(QPalette::Active, QPalette::Shadow, brush1);
        palette9.setBrush(QPalette::Active, QPalette::AlternateBase, brush18);
        palette9.setBrush(QPalette::Active, QPalette::ToolTipBase, brush2);
        palette9.setBrush(QPalette::Active, QPalette::ToolTipText, brush1);
        palette9.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette9.setBrush(QPalette::Inactive, QPalette::Button, brush15);
        palette9.setBrush(QPalette::Inactive, QPalette::Light, brush16);
        palette9.setBrush(QPalette::Inactive, QPalette::Midlight, brush17);
        palette9.setBrush(QPalette::Inactive, QPalette::Dark, brush18);
        palette9.setBrush(QPalette::Inactive, QPalette::Mid, brush19);
        palette9.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette9.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette9.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette9.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette9.setBrush(QPalette::Inactive, QPalette::Window, brush15);
        palette9.setBrush(QPalette::Inactive, QPalette::Shadow, brush1);
        palette9.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush18);
        palette9.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush2);
        palette9.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush1);
        palette9.setBrush(QPalette::Disabled, QPalette::WindowText, brush18);
        palette9.setBrush(QPalette::Disabled, QPalette::Button, brush15);
        palette9.setBrush(QPalette::Disabled, QPalette::Light, brush16);
        palette9.setBrush(QPalette::Disabled, QPalette::Midlight, brush17);
        palette9.setBrush(QPalette::Disabled, QPalette::Dark, brush18);
        palette9.setBrush(QPalette::Disabled, QPalette::Mid, brush19);
        palette9.setBrush(QPalette::Disabled, QPalette::Text, brush18);
        palette9.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette9.setBrush(QPalette::Disabled, QPalette::ButtonText, brush18);
        palette9.setBrush(QPalette::Disabled, QPalette::Base, brush15);
        palette9.setBrush(QPalette::Disabled, QPalette::Window, brush15);
        palette9.setBrush(QPalette::Disabled, QPalette::Shadow, brush1);
        palette9.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush15);
        palette9.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush2);
        palette9.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush1);
        btnECG2lead->setPalette(palette9);
        QFont font6;
        font6.setFamily(QString::fromUtf8("\346\226\207\346\263\211\351\251\233\347\255\211\345\257\254\345\276\256\347\261\263\351\273\221"));
        btnECG2lead->setFont(font6);
        btnECG2lead->setFocusPolicy(Qt::NoFocus);
        btnECG2lead->setStyleSheet(QStringLiteral("border-image: url(:/rsc/images/btnecg.png);"));
        btnECG2gain = new QPushButton(gpecgchannel2);
        btnECG2gain->setObjectName(QStringLiteral("btnECG2gain"));
        btnECG2gain->setGeometry(QRect(160, 130, 181, 41));
        QPalette palette10;
        palette10.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette10.setBrush(QPalette::Active, QPalette::Button, brush15);
        palette10.setBrush(QPalette::Active, QPalette::Light, brush16);
        palette10.setBrush(QPalette::Active, QPalette::Midlight, brush17);
        palette10.setBrush(QPalette::Active, QPalette::Dark, brush18);
        palette10.setBrush(QPalette::Active, QPalette::Mid, brush19);
        palette10.setBrush(QPalette::Active, QPalette::Text, brush);
        palette10.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette10.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette10.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette10.setBrush(QPalette::Active, QPalette::Window, brush15);
        palette10.setBrush(QPalette::Active, QPalette::Shadow, brush1);
        palette10.setBrush(QPalette::Active, QPalette::AlternateBase, brush18);
        palette10.setBrush(QPalette::Active, QPalette::ToolTipBase, brush2);
        palette10.setBrush(QPalette::Active, QPalette::ToolTipText, brush1);
        palette10.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette10.setBrush(QPalette::Inactive, QPalette::Button, brush15);
        palette10.setBrush(QPalette::Inactive, QPalette::Light, brush16);
        palette10.setBrush(QPalette::Inactive, QPalette::Midlight, brush17);
        palette10.setBrush(QPalette::Inactive, QPalette::Dark, brush18);
        palette10.setBrush(QPalette::Inactive, QPalette::Mid, brush19);
        palette10.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette10.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette10.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette10.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette10.setBrush(QPalette::Inactive, QPalette::Window, brush15);
        palette10.setBrush(QPalette::Inactive, QPalette::Shadow, brush1);
        palette10.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush18);
        palette10.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush2);
        palette10.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush1);
        palette10.setBrush(QPalette::Disabled, QPalette::WindowText, brush18);
        palette10.setBrush(QPalette::Disabled, QPalette::Button, brush15);
        palette10.setBrush(QPalette::Disabled, QPalette::Light, brush16);
        palette10.setBrush(QPalette::Disabled, QPalette::Midlight, brush17);
        palette10.setBrush(QPalette::Disabled, QPalette::Dark, brush18);
        palette10.setBrush(QPalette::Disabled, QPalette::Mid, brush19);
        palette10.setBrush(QPalette::Disabled, QPalette::Text, brush18);
        palette10.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette10.setBrush(QPalette::Disabled, QPalette::ButtonText, brush18);
        palette10.setBrush(QPalette::Disabled, QPalette::Base, brush15);
        palette10.setBrush(QPalette::Disabled, QPalette::Window, brush15);
        palette10.setBrush(QPalette::Disabled, QPalette::Shadow, brush1);
        palette10.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush15);
        palette10.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush2);
        palette10.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush1);
        btnECG2gain->setPalette(palette10);
        btnECG2gain->setFocusPolicy(Qt::NoFocus);
        btnECG2gain->setStyleSheet(QStringLiteral("border-image: url(:/rsc/images/btnecg.png);"));
        btnECGChanel2 = new QPushButton(gpecgchannel2);
        btnECGChanel2->setObjectName(QStringLiteral("btnECGChanel2"));
        btnECGChanel2->setGeometry(QRect(0, 0, 371, 50));
        QPalette palette11;
        palette11.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QLinearGradient gradient18(0.5, 1, 0.463636, 0);
        gradient18.setSpread(QGradient::PadSpread);
        gradient18.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient18.setColorAt(0.290909, QColor(25, 30, 46, 255));
        gradient18.setColorAt(0.540909, QColor(70, 72, 93, 255));
        QBrush brush29(gradient18);
        palette11.setBrush(QPalette::Active, QPalette::Button, brush29);
        palette11.setBrush(QPalette::Active, QPalette::Light, brush16);
        palette11.setBrush(QPalette::Active, QPalette::Midlight, brush17);
        palette11.setBrush(QPalette::Active, QPalette::Dark, brush18);
        palette11.setBrush(QPalette::Active, QPalette::Mid, brush19);
        palette11.setBrush(QPalette::Active, QPalette::Text, brush);
        palette11.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette11.setBrush(QPalette::Active, QPalette::ButtonText, brush4);
        QLinearGradient gradient19(0.5, 1, 0.463636, 0);
        gradient19.setSpread(QGradient::PadSpread);
        gradient19.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient19.setColorAt(0.290909, QColor(25, 30, 46, 255));
        gradient19.setColorAt(0.540909, QColor(70, 72, 93, 255));
        QBrush brush30(gradient19);
        palette11.setBrush(QPalette::Active, QPalette::Base, brush30);
        QLinearGradient gradient20(0.5, 1, 0.463636, 0);
        gradient20.setSpread(QGradient::PadSpread);
        gradient20.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient20.setColorAt(0.290909, QColor(25, 30, 46, 255));
        gradient20.setColorAt(0.540909, QColor(70, 72, 93, 255));
        QBrush brush31(gradient20);
        palette11.setBrush(QPalette::Active, QPalette::Window, brush31);
        palette11.setBrush(QPalette::Active, QPalette::Shadow, brush15);
        palette11.setBrush(QPalette::Active, QPalette::AlternateBase, brush18);
        palette11.setBrush(QPalette::Active, QPalette::ToolTipBase, brush2);
        palette11.setBrush(QPalette::Active, QPalette::ToolTipText, brush1);
        palette11.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        QLinearGradient gradient21(0.5, 1, 0.463636, 0);
        gradient21.setSpread(QGradient::PadSpread);
        gradient21.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient21.setColorAt(0.290909, QColor(25, 30, 46, 255));
        gradient21.setColorAt(0.540909, QColor(70, 72, 93, 255));
        QBrush brush32(gradient21);
        palette11.setBrush(QPalette::Inactive, QPalette::Button, brush32);
        palette11.setBrush(QPalette::Inactive, QPalette::Light, brush16);
        palette11.setBrush(QPalette::Inactive, QPalette::Midlight, brush17);
        palette11.setBrush(QPalette::Inactive, QPalette::Dark, brush18);
        palette11.setBrush(QPalette::Inactive, QPalette::Mid, brush19);
        palette11.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette11.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette11.setBrush(QPalette::Inactive, QPalette::ButtonText, brush4);
        QLinearGradient gradient22(0.5, 1, 0.463636, 0);
        gradient22.setSpread(QGradient::PadSpread);
        gradient22.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient22.setColorAt(0.290909, QColor(25, 30, 46, 255));
        gradient22.setColorAt(0.540909, QColor(70, 72, 93, 255));
        QBrush brush33(gradient22);
        palette11.setBrush(QPalette::Inactive, QPalette::Base, brush33);
        QLinearGradient gradient23(0.5, 1, 0.463636, 0);
        gradient23.setSpread(QGradient::PadSpread);
        gradient23.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient23.setColorAt(0.290909, QColor(25, 30, 46, 255));
        gradient23.setColorAt(0.540909, QColor(70, 72, 93, 255));
        QBrush brush34(gradient23);
        palette11.setBrush(QPalette::Inactive, QPalette::Window, brush34);
        palette11.setBrush(QPalette::Inactive, QPalette::Shadow, brush15);
        palette11.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush18);
        palette11.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush2);
        palette11.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush1);
        palette11.setBrush(QPalette::Disabled, QPalette::WindowText, brush18);
        QLinearGradient gradient24(0.5, 1, 0.463636, 0);
        gradient24.setSpread(QGradient::PadSpread);
        gradient24.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient24.setColorAt(0.290909, QColor(25, 30, 46, 255));
        gradient24.setColorAt(0.540909, QColor(70, 72, 93, 255));
        QBrush brush35(gradient24);
        palette11.setBrush(QPalette::Disabled, QPalette::Button, brush35);
        palette11.setBrush(QPalette::Disabled, QPalette::Light, brush16);
        palette11.setBrush(QPalette::Disabled, QPalette::Midlight, brush17);
        palette11.setBrush(QPalette::Disabled, QPalette::Dark, brush18);
        palette11.setBrush(QPalette::Disabled, QPalette::Mid, brush19);
        palette11.setBrush(QPalette::Disabled, QPalette::Text, brush18);
        palette11.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette11.setBrush(QPalette::Disabled, QPalette::ButtonText, brush18);
        QLinearGradient gradient25(0.5, 1, 0.463636, 0);
        gradient25.setSpread(QGradient::PadSpread);
        gradient25.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient25.setColorAt(0.290909, QColor(25, 30, 46, 255));
        gradient25.setColorAt(0.540909, QColor(70, 72, 93, 255));
        QBrush brush36(gradient25);
        palette11.setBrush(QPalette::Disabled, QPalette::Base, brush36);
        QLinearGradient gradient26(0.5, 1, 0.463636, 0);
        gradient26.setSpread(QGradient::PadSpread);
        gradient26.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient26.setColorAt(0.290909, QColor(25, 30, 46, 255));
        gradient26.setColorAt(0.540909, QColor(70, 72, 93, 255));
        QBrush brush37(gradient26);
        palette11.setBrush(QPalette::Disabled, QPalette::Window, brush37);
        palette11.setBrush(QPalette::Disabled, QPalette::Shadow, brush15);
        palette11.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush15);
        palette11.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush2);
        palette11.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush1);
        btnECGChanel2->setPalette(palette11);
        QFont font7;
        font7.setPointSize(26);
        btnECGChanel2->setFont(font7);
        btnECGChanel2->setFocusPolicy(Qt::NoFocus);
        btnECGChanel2->setStyleSheet(QStringLiteral("background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.463636, y2:0, stop:0.290909 rgba(25, 30, 46, 255), stop:0.540909 rgba(70, 72, 93, 255));"));
        gpother = new QGroupBox(groupBox);
        gpother->setObjectName(QStringLiteral("gpother"));
        gpother->setGeometry(QRect(860, 0, 501, 180));
        QPalette palette12;
        palette12.setBrush(QPalette::Active, QPalette::Light, brush);
        palette12.setBrush(QPalette::Active, QPalette::Midlight, brush);
        palette12.setBrush(QPalette::Inactive, QPalette::Light, brush);
        palette12.setBrush(QPalette::Inactive, QPalette::Midlight, brush);
        palette12.setBrush(QPalette::Disabled, QPalette::Light, brush);
        palette12.setBrush(QPalette::Disabled, QPalette::Midlight, brush);
        gpother->setPalette(palette12);
        gpother->setFont(font3);
        btnECGModel = new QPushButton(gpother);
        btnECGModel->setObjectName(QStringLiteral("btnECGModel"));
        btnECGModel->setGeometry(QRect(290, 65, 181, 51));
        QPalette palette13;
        palette13.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette13.setBrush(QPalette::Active, QPalette::Button, brush15);
        palette13.setBrush(QPalette::Active, QPalette::Light, brush16);
        palette13.setBrush(QPalette::Active, QPalette::Midlight, brush17);
        palette13.setBrush(QPalette::Active, QPalette::Dark, brush18);
        palette13.setBrush(QPalette::Active, QPalette::Mid, brush19);
        palette13.setBrush(QPalette::Active, QPalette::Text, brush);
        palette13.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette13.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette13.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette13.setBrush(QPalette::Active, QPalette::Window, brush15);
        palette13.setBrush(QPalette::Active, QPalette::Shadow, brush1);
        palette13.setBrush(QPalette::Active, QPalette::AlternateBase, brush18);
        palette13.setBrush(QPalette::Active, QPalette::ToolTipBase, brush2);
        palette13.setBrush(QPalette::Active, QPalette::ToolTipText, brush1);
        palette13.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette13.setBrush(QPalette::Inactive, QPalette::Button, brush15);
        palette13.setBrush(QPalette::Inactive, QPalette::Light, brush16);
        palette13.setBrush(QPalette::Inactive, QPalette::Midlight, brush17);
        palette13.setBrush(QPalette::Inactive, QPalette::Dark, brush18);
        palette13.setBrush(QPalette::Inactive, QPalette::Mid, brush19);
        palette13.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette13.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette13.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette13.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette13.setBrush(QPalette::Inactive, QPalette::Window, brush15);
        palette13.setBrush(QPalette::Inactive, QPalette::Shadow, brush1);
        palette13.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush18);
        palette13.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush2);
        palette13.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush1);
        palette13.setBrush(QPalette::Disabled, QPalette::WindowText, brush18);
        palette13.setBrush(QPalette::Disabled, QPalette::Button, brush15);
        palette13.setBrush(QPalette::Disabled, QPalette::Light, brush16);
        palette13.setBrush(QPalette::Disabled, QPalette::Midlight, brush17);
        palette13.setBrush(QPalette::Disabled, QPalette::Dark, brush18);
        palette13.setBrush(QPalette::Disabled, QPalette::Mid, brush19);
        palette13.setBrush(QPalette::Disabled, QPalette::Text, brush18);
        palette13.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette13.setBrush(QPalette::Disabled, QPalette::ButtonText, brush18);
        palette13.setBrush(QPalette::Disabled, QPalette::Base, brush15);
        palette13.setBrush(QPalette::Disabled, QPalette::Window, brush15);
        palette13.setBrush(QPalette::Disabled, QPalette::Shadow, brush1);
        palette13.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush15);
        palette13.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush2);
        palette13.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush1);
        btnECGModel->setPalette(palette13);
        btnECGModel->setFocusPolicy(Qt::NoFocus);
        btnECGModel->setStyleSheet(QStringLiteral("border-image: url(:/rsc/images/btnecg.png);"));
        btnDiagnoseModel = new QPushButton(gpother);
        btnDiagnoseModel->setObjectName(QStringLiteral("btnDiagnoseModel"));
        btnDiagnoseModel->setGeometry(QRect(290, 5, 181, 51));
        QPalette palette14;
        palette14.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette14.setBrush(QPalette::Active, QPalette::Button, brush15);
        palette14.setBrush(QPalette::Active, QPalette::Light, brush16);
        palette14.setBrush(QPalette::Active, QPalette::Midlight, brush17);
        palette14.setBrush(QPalette::Active, QPalette::Dark, brush18);
        palette14.setBrush(QPalette::Active, QPalette::Mid, brush19);
        palette14.setBrush(QPalette::Active, QPalette::Text, brush);
        palette14.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette14.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette14.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette14.setBrush(QPalette::Active, QPalette::Window, brush15);
        palette14.setBrush(QPalette::Active, QPalette::Shadow, brush1);
        palette14.setBrush(QPalette::Active, QPalette::AlternateBase, brush18);
        palette14.setBrush(QPalette::Active, QPalette::ToolTipBase, brush2);
        palette14.setBrush(QPalette::Active, QPalette::ToolTipText, brush1);
        palette14.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette14.setBrush(QPalette::Inactive, QPalette::Button, brush15);
        palette14.setBrush(QPalette::Inactive, QPalette::Light, brush16);
        palette14.setBrush(QPalette::Inactive, QPalette::Midlight, brush17);
        palette14.setBrush(QPalette::Inactive, QPalette::Dark, brush18);
        palette14.setBrush(QPalette::Inactive, QPalette::Mid, brush19);
        palette14.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette14.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette14.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette14.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette14.setBrush(QPalette::Inactive, QPalette::Window, brush15);
        palette14.setBrush(QPalette::Inactive, QPalette::Shadow, brush1);
        palette14.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush18);
        palette14.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush2);
        palette14.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush1);
        palette14.setBrush(QPalette::Disabled, QPalette::WindowText, brush18);
        palette14.setBrush(QPalette::Disabled, QPalette::Button, brush15);
        palette14.setBrush(QPalette::Disabled, QPalette::Light, brush16);
        palette14.setBrush(QPalette::Disabled, QPalette::Midlight, brush17);
        palette14.setBrush(QPalette::Disabled, QPalette::Dark, brush18);
        palette14.setBrush(QPalette::Disabled, QPalette::Mid, brush19);
        palette14.setBrush(QPalette::Disabled, QPalette::Text, brush18);
        palette14.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette14.setBrush(QPalette::Disabled, QPalette::ButtonText, brush18);
        palette14.setBrush(QPalette::Disabled, QPalette::Base, brush15);
        palette14.setBrush(QPalette::Disabled, QPalette::Window, brush15);
        palette14.setBrush(QPalette::Disabled, QPalette::Shadow, brush1);
        palette14.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush15);
        palette14.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush2);
        palette14.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush1);
        btnDiagnoseModel->setPalette(palette14);
        btnDiagnoseModel->setFocusPolicy(Qt::NoFocus);
        btnDiagnoseModel->setStyleSheet(QStringLiteral("border-image: url(:/rsc/images/btnecg.png);"));
        btnECGcall = new QPushButton(gpother);
        btnECGcall->setObjectName(QStringLiteral("btnECGcall"));
        btnECGcall->setGeometry(QRect(290, 125, 181, 51));
        QPalette palette15;
        palette15.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette15.setBrush(QPalette::Active, QPalette::Button, brush15);
        palette15.setBrush(QPalette::Active, QPalette::Light, brush16);
        palette15.setBrush(QPalette::Active, QPalette::Midlight, brush17);
        palette15.setBrush(QPalette::Active, QPalette::Dark, brush18);
        palette15.setBrush(QPalette::Active, QPalette::Mid, brush19);
        palette15.setBrush(QPalette::Active, QPalette::Text, brush);
        palette15.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette15.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette15.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette15.setBrush(QPalette::Active, QPalette::Window, brush15);
        palette15.setBrush(QPalette::Active, QPalette::Shadow, brush1);
        palette15.setBrush(QPalette::Active, QPalette::AlternateBase, brush18);
        palette15.setBrush(QPalette::Active, QPalette::ToolTipBase, brush2);
        palette15.setBrush(QPalette::Active, QPalette::ToolTipText, brush1);
        palette15.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette15.setBrush(QPalette::Inactive, QPalette::Button, brush15);
        palette15.setBrush(QPalette::Inactive, QPalette::Light, brush16);
        palette15.setBrush(QPalette::Inactive, QPalette::Midlight, brush17);
        palette15.setBrush(QPalette::Inactive, QPalette::Dark, brush18);
        palette15.setBrush(QPalette::Inactive, QPalette::Mid, brush19);
        palette15.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette15.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette15.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette15.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette15.setBrush(QPalette::Inactive, QPalette::Window, brush15);
        palette15.setBrush(QPalette::Inactive, QPalette::Shadow, brush1);
        palette15.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush18);
        palette15.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush2);
        palette15.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush1);
        palette15.setBrush(QPalette::Disabled, QPalette::WindowText, brush18);
        palette15.setBrush(QPalette::Disabled, QPalette::Button, brush15);
        palette15.setBrush(QPalette::Disabled, QPalette::Light, brush16);
        palette15.setBrush(QPalette::Disabled, QPalette::Midlight, brush17);
        palette15.setBrush(QPalette::Disabled, QPalette::Dark, brush18);
        palette15.setBrush(QPalette::Disabled, QPalette::Mid, brush19);
        palette15.setBrush(QPalette::Disabled, QPalette::Text, brush18);
        palette15.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette15.setBrush(QPalette::Disabled, QPalette::ButtonText, brush18);
        palette15.setBrush(QPalette::Disabled, QPalette::Base, brush15);
        palette15.setBrush(QPalette::Disabled, QPalette::Window, brush15);
        palette15.setBrush(QPalette::Disabled, QPalette::Shadow, brush1);
        palette15.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush15);
        palette15.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush2);
        palette15.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush1);
        btnECGcall->setPalette(palette15);
        btnECGcall->setFocusPolicy(Qt::NoFocus);
        btnECGcall->setStyleSheet(QStringLiteral("border-image: url(:/rsc/images/btnecg.png);"));
        btnOther = new QPushButton(gpother);
        btnOther->setObjectName(QStringLiteral("btnOther"));
        btnOther->setGeometry(QRect(0, 0, 251, 50));
        QPalette palette16;
        palette16.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QLinearGradient gradient27(0.5, 1, 0.463636, 0);
        gradient27.setSpread(QGradient::PadSpread);
        gradient27.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient27.setColorAt(0.290909, QColor(25, 30, 46, 255));
        gradient27.setColorAt(0.540909, QColor(70, 72, 93, 255));
        QBrush brush38(gradient27);
        palette16.setBrush(QPalette::Active, QPalette::Button, brush38);
        palette16.setBrush(QPalette::Active, QPalette::Light, brush16);
        palette16.setBrush(QPalette::Active, QPalette::Midlight, brush17);
        palette16.setBrush(QPalette::Active, QPalette::Dark, brush18);
        palette16.setBrush(QPalette::Active, QPalette::Mid, brush19);
        palette16.setBrush(QPalette::Active, QPalette::Text, brush);
        palette16.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette16.setBrush(QPalette::Active, QPalette::ButtonText, brush4);
        QLinearGradient gradient28(0.5, 1, 0.463636, 0);
        gradient28.setSpread(QGradient::PadSpread);
        gradient28.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient28.setColorAt(0.290909, QColor(25, 30, 46, 255));
        gradient28.setColorAt(0.540909, QColor(70, 72, 93, 255));
        QBrush brush39(gradient28);
        palette16.setBrush(QPalette::Active, QPalette::Base, brush39);
        QLinearGradient gradient29(0.5, 1, 0.463636, 0);
        gradient29.setSpread(QGradient::PadSpread);
        gradient29.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient29.setColorAt(0.290909, QColor(25, 30, 46, 255));
        gradient29.setColorAt(0.540909, QColor(70, 72, 93, 255));
        QBrush brush40(gradient29);
        palette16.setBrush(QPalette::Active, QPalette::Window, brush40);
        palette16.setBrush(QPalette::Active, QPalette::Shadow, brush15);
        palette16.setBrush(QPalette::Active, QPalette::AlternateBase, brush18);
        palette16.setBrush(QPalette::Active, QPalette::ToolTipBase, brush2);
        palette16.setBrush(QPalette::Active, QPalette::ToolTipText, brush1);
        palette16.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        QLinearGradient gradient30(0.5, 1, 0.463636, 0);
        gradient30.setSpread(QGradient::PadSpread);
        gradient30.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient30.setColorAt(0.290909, QColor(25, 30, 46, 255));
        gradient30.setColorAt(0.540909, QColor(70, 72, 93, 255));
        QBrush brush41(gradient30);
        palette16.setBrush(QPalette::Inactive, QPalette::Button, brush41);
        palette16.setBrush(QPalette::Inactive, QPalette::Light, brush16);
        palette16.setBrush(QPalette::Inactive, QPalette::Midlight, brush17);
        palette16.setBrush(QPalette::Inactive, QPalette::Dark, brush18);
        palette16.setBrush(QPalette::Inactive, QPalette::Mid, brush19);
        palette16.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette16.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette16.setBrush(QPalette::Inactive, QPalette::ButtonText, brush4);
        QLinearGradient gradient31(0.5, 1, 0.463636, 0);
        gradient31.setSpread(QGradient::PadSpread);
        gradient31.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient31.setColorAt(0.290909, QColor(25, 30, 46, 255));
        gradient31.setColorAt(0.540909, QColor(70, 72, 93, 255));
        QBrush brush42(gradient31);
        palette16.setBrush(QPalette::Inactive, QPalette::Base, brush42);
        QLinearGradient gradient32(0.5, 1, 0.463636, 0);
        gradient32.setSpread(QGradient::PadSpread);
        gradient32.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient32.setColorAt(0.290909, QColor(25, 30, 46, 255));
        gradient32.setColorAt(0.540909, QColor(70, 72, 93, 255));
        QBrush brush43(gradient32);
        palette16.setBrush(QPalette::Inactive, QPalette::Window, brush43);
        palette16.setBrush(QPalette::Inactive, QPalette::Shadow, brush15);
        palette16.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush18);
        palette16.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush2);
        palette16.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush1);
        palette16.setBrush(QPalette::Disabled, QPalette::WindowText, brush18);
        QLinearGradient gradient33(0.5, 1, 0.463636, 0);
        gradient33.setSpread(QGradient::PadSpread);
        gradient33.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient33.setColorAt(0.290909, QColor(25, 30, 46, 255));
        gradient33.setColorAt(0.540909, QColor(70, 72, 93, 255));
        QBrush brush44(gradient33);
        palette16.setBrush(QPalette::Disabled, QPalette::Button, brush44);
        palette16.setBrush(QPalette::Disabled, QPalette::Light, brush16);
        palette16.setBrush(QPalette::Disabled, QPalette::Midlight, brush17);
        palette16.setBrush(QPalette::Disabled, QPalette::Dark, brush18);
        palette16.setBrush(QPalette::Disabled, QPalette::Mid, brush19);
        palette16.setBrush(QPalette::Disabled, QPalette::Text, brush18);
        palette16.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette16.setBrush(QPalette::Disabled, QPalette::ButtonText, brush18);
        QLinearGradient gradient34(0.5, 1, 0.463636, 0);
        gradient34.setSpread(QGradient::PadSpread);
        gradient34.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient34.setColorAt(0.290909, QColor(25, 30, 46, 255));
        gradient34.setColorAt(0.540909, QColor(70, 72, 93, 255));
        QBrush brush45(gradient34);
        palette16.setBrush(QPalette::Disabled, QPalette::Base, brush45);
        QLinearGradient gradient35(0.5, 1, 0.463636, 0);
        gradient35.setSpread(QGradient::PadSpread);
        gradient35.setCoordinateMode(QGradient::ObjectBoundingMode);
        gradient35.setColorAt(0.290909, QColor(25, 30, 46, 255));
        gradient35.setColorAt(0.540909, QColor(70, 72, 93, 255));
        QBrush brush46(gradient35);
        palette16.setBrush(QPalette::Disabled, QPalette::Window, brush46);
        palette16.setBrush(QPalette::Disabled, QPalette::Shadow, brush15);
        palette16.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush15);
        palette16.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush2);
        palette16.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush1);
        btnOther->setPalette(palette16);
        btnOther->setFont(font5);
        btnOther->setFocusPolicy(Qt::NoFocus);
        btnOther->setStyleSheet(QStringLiteral("background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.463636, y2:0, stop:0.290909 rgba(25, 30, 46, 255), stop:0.540909 rgba(70, 72, 93, 255));"));
        btnLeadswitch = new QPushButton(gpother);
        btnLeadswitch->setObjectName(QStringLiteral("btnLeadswitch"));
        btnLeadswitch->setGeometry(QRect(70, 125, 181, 51));
        QPalette palette17;
        palette17.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette17.setBrush(QPalette::Active, QPalette::Button, brush15);
        palette17.setBrush(QPalette::Active, QPalette::Light, brush16);
        palette17.setBrush(QPalette::Active, QPalette::Midlight, brush17);
        palette17.setBrush(QPalette::Active, QPalette::Dark, brush18);
        palette17.setBrush(QPalette::Active, QPalette::Mid, brush19);
        palette17.setBrush(QPalette::Active, QPalette::Text, brush);
        palette17.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette17.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette17.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette17.setBrush(QPalette::Active, QPalette::Window, brush15);
        palette17.setBrush(QPalette::Active, QPalette::Shadow, brush1);
        palette17.setBrush(QPalette::Active, QPalette::AlternateBase, brush18);
        palette17.setBrush(QPalette::Active, QPalette::ToolTipBase, brush2);
        palette17.setBrush(QPalette::Active, QPalette::ToolTipText, brush1);
        palette17.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette17.setBrush(QPalette::Inactive, QPalette::Button, brush15);
        palette17.setBrush(QPalette::Inactive, QPalette::Light, brush16);
        palette17.setBrush(QPalette::Inactive, QPalette::Midlight, brush17);
        palette17.setBrush(QPalette::Inactive, QPalette::Dark, brush18);
        palette17.setBrush(QPalette::Inactive, QPalette::Mid, brush19);
        palette17.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette17.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette17.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette17.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette17.setBrush(QPalette::Inactive, QPalette::Window, brush15);
        palette17.setBrush(QPalette::Inactive, QPalette::Shadow, brush1);
        palette17.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush18);
        palette17.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush2);
        palette17.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush1);
        palette17.setBrush(QPalette::Disabled, QPalette::WindowText, brush18);
        palette17.setBrush(QPalette::Disabled, QPalette::Button, brush15);
        palette17.setBrush(QPalette::Disabled, QPalette::Light, brush16);
        palette17.setBrush(QPalette::Disabled, QPalette::Midlight, brush17);
        palette17.setBrush(QPalette::Disabled, QPalette::Dark, brush18);
        palette17.setBrush(QPalette::Disabled, QPalette::Mid, brush19);
        palette17.setBrush(QPalette::Disabled, QPalette::Text, brush18);
        palette17.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette17.setBrush(QPalette::Disabled, QPalette::ButtonText, brush18);
        palette17.setBrush(QPalette::Disabled, QPalette::Base, brush15);
        palette17.setBrush(QPalette::Disabled, QPalette::Window, brush15);
        palette17.setBrush(QPalette::Disabled, QPalette::Shadow, brush1);
        palette17.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush15);
        palette17.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush2);
        palette17.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush1);
        btnLeadswitch->setPalette(palette17);
        btnLeadswitch->setFocusPolicy(Qt::NoFocus);
        btnLeadswitch->setStyleSheet(QStringLiteral("border-image: url(:/rsc/images/btnecg.png);"));
        btnECGFreeze = new QPushButton(gpother);
        btnECGFreeze->setObjectName(QStringLiteral("btnECGFreeze"));
        btnECGFreeze->setGeometry(QRect(70, 65, 181, 51));
        QPalette palette18;
        palette18.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette18.setBrush(QPalette::Active, QPalette::Button, brush15);
        palette18.setBrush(QPalette::Active, QPalette::Light, brush16);
        palette18.setBrush(QPalette::Active, QPalette::Midlight, brush17);
        palette18.setBrush(QPalette::Active, QPalette::Dark, brush18);
        palette18.setBrush(QPalette::Active, QPalette::Mid, brush19);
        palette18.setBrush(QPalette::Active, QPalette::Text, brush);
        palette18.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette18.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette18.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette18.setBrush(QPalette::Active, QPalette::Window, brush15);
        palette18.setBrush(QPalette::Active, QPalette::Shadow, brush1);
        palette18.setBrush(QPalette::Active, QPalette::AlternateBase, brush18);
        palette18.setBrush(QPalette::Active, QPalette::ToolTipBase, brush2);
        palette18.setBrush(QPalette::Active, QPalette::ToolTipText, brush1);
        palette18.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette18.setBrush(QPalette::Inactive, QPalette::Button, brush15);
        palette18.setBrush(QPalette::Inactive, QPalette::Light, brush16);
        palette18.setBrush(QPalette::Inactive, QPalette::Midlight, brush17);
        palette18.setBrush(QPalette::Inactive, QPalette::Dark, brush18);
        palette18.setBrush(QPalette::Inactive, QPalette::Mid, brush19);
        palette18.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette18.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette18.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette18.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette18.setBrush(QPalette::Inactive, QPalette::Window, brush15);
        palette18.setBrush(QPalette::Inactive, QPalette::Shadow, brush1);
        palette18.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush18);
        palette18.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush2);
        palette18.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush1);
        palette18.setBrush(QPalette::Disabled, QPalette::WindowText, brush18);
        palette18.setBrush(QPalette::Disabled, QPalette::Button, brush15);
        palette18.setBrush(QPalette::Disabled, QPalette::Light, brush16);
        palette18.setBrush(QPalette::Disabled, QPalette::Midlight, brush17);
        palette18.setBrush(QPalette::Disabled, QPalette::Dark, brush18);
        palette18.setBrush(QPalette::Disabled, QPalette::Mid, brush19);
        palette18.setBrush(QPalette::Disabled, QPalette::Text, brush18);
        palette18.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette18.setBrush(QPalette::Disabled, QPalette::ButtonText, brush18);
        palette18.setBrush(QPalette::Disabled, QPalette::Base, brush15);
        palette18.setBrush(QPalette::Disabled, QPalette::Window, brush15);
        palette18.setBrush(QPalette::Disabled, QPalette::Shadow, brush1);
        palette18.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush15);
        palette18.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush2);
        palette18.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush1);
        btnECGFreeze->setPalette(palette18);
        btnECGFreeze->setFocusPolicy(Qt::NoFocus);
        btnECGFreeze->setStyleSheet(QStringLiteral("border-image: url(:/rsc/images/btnecg.png);"));
        qwtPlot_ECG = new QwtPlot(WaveForm);
        qwtPlot_ECG->setObjectName(QStringLiteral("qwtPlot_ECG"));
        qwtPlot_ECG->setGeometry(QRect(0, 65, 1361, 211));
        QPalette palette19;
        palette19.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette19.setBrush(QPalette::Active, QPalette::Window, brush3);
        palette19.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette19.setBrush(QPalette::Inactive, QPalette::Window, brush3);
        palette19.setBrush(QPalette::Disabled, QPalette::Base, brush3);
        palette19.setBrush(QPalette::Disabled, QPalette::Window, brush3);
        qwtPlot_ECG->setPalette(palette19);
        lab_HR = new QLabel(qwtPlot_ECG);
        lab_HR->setObjectName(QStringLiteral("lab_HR"));
        lab_HR->setGeometry(QRect(1270, 10, 71, 31));
        QPalette palette20;
        palette20.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette20.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette20.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        lab_HR->setPalette(palette20);
        QFont font8;
        font8.setPointSize(22);
        font8.setBold(true);
        font8.setWeight(75);
        lab_HR->setFont(font8);
        lab_ecg1gaintag = new QLabel(qwtPlot_ECG);
        lab_ecg1gaintag->setObjectName(QStringLiteral("lab_ecg1gaintag"));
        lab_ecg1gaintag->setGeometry(QRect(210, 10, 81, 31));
        lab_ecg1gaintag->setFont(font);
        lab_ecg1leadtag = new QLabel(qwtPlot_ECG);
        lab_ecg1leadtag->setObjectName(QStringLiteral("lab_ecg1leadtag"));
        lab_ecg1leadtag->setGeometry(QRect(10, 10, 81, 31));
        lab_ecg1leadtag->setFont(font);
        lab_hrtag = new QLabel(qwtPlot_ECG);
        lab_hrtag->setObjectName(QStringLiteral("lab_hrtag"));
        lab_hrtag->setGeometry(QRect(1200, 10, 91, 31));
        QPalette palette21;
        palette21.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette21.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette21.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        lab_hrtag->setPalette(palette21);
        lab_hrtag->setFont(font8);
        lab_ECG1lead = new QLabel(qwtPlot_ECG);
        lab_ECG1lead->setObjectName(QStringLiteral("lab_ECG1lead"));
        lab_ECG1lead->setGeometry(QRect(80, 10, 81, 31));
        lab_ECG1lead->setFont(font);
        lab_ECG1Gain = new QLabel(qwtPlot_ECG);
        lab_ECG1Gain->setObjectName(QStringLiteral("lab_ECG1Gain"));
        lab_ECG1Gain->setGeometry(QRect(290, 10, 131, 31));
        lab_ECG1Gain->setFont(font);
        groupBox->raise();
        qwtPlot_ECG2->raise();
        qwtPlot_ECG->raise();

        retranslateUi(WaveForm);

        QMetaObject::connectSlotsByName(WaveForm);
    } // setupUi

    void retranslateUi(QWidget *WaveForm)
    {
        WaveForm->setWindowTitle(QApplication::translate("WaveForm", "Form", 0));
        lab_ecg2leadtag->setText(QApplication::translate("WaveForm", "\345\257\274\350\201\224:", 0));
        lab_ecg2gaintag->setText(QApplication::translate("WaveForm", "\345\242\236\347\233\212:", 0));
        lab_ECG2lead->setText(QApplication::translate("WaveForm", "I", 0));
        lab_ECG2Gain->setText(QApplication::translate("WaveForm", " x1", 0));
        groupBox->setTitle(QString());
        lab_ECGSET->setText(QApplication::translate("WaveForm", "\345\277\203\n"
"\347\224\265\n"
"\350\256\276\n"
"\347\275\256", 0));
        gpecgchannel1->setTitle(QString());
        lab_lead1set->setText(QApplication::translate("WaveForm", "\345\257\274\350\201\224\350\256\276\347\275\256", 0));
        lab_gain1set->setText(QApplication::translate("WaveForm", "\345\242\236\347\233\212\350\256\276\347\275\256", 0));
        btnECG1lead->setText(QApplication::translate("WaveForm", "\345\257\274\350\201\224\345\210\207\346\215\242", 0));
        btnECG1gain->setText(QApplication::translate("WaveForm", "\345\242\236\347\233\212\345\210\207\346\215\242", 0));
        btnECGChanel1->setText(QApplication::translate("WaveForm", "\345\277\203\347\224\265 \351\200\232\351\201\2231 ", 0));
        gpecgchannel2->setTitle(QString());
        lab_lead2set->setText(QApplication::translate("WaveForm", "\345\257\274\350\201\224\350\256\276\347\275\256", 0));
        lab_gain2set->setText(QApplication::translate("WaveForm", "\345\242\236\347\233\212\350\256\276\347\275\256", 0));
        btnECG2lead->setText(QApplication::translate("WaveForm", "\345\257\274\350\201\224\345\210\207\346\215\242", 0));
        btnECG2gain->setText(QApplication::translate("WaveForm", "\345\242\236\347\233\212\345\210\207\346\215\242", 0));
        btnECGChanel2->setText(QApplication::translate("WaveForm", "\345\277\203\347\224\265 \351\200\232\351\201\2232", 0));
        gpother->setTitle(QString());
        btnECGModel->setText(QApplication::translate("WaveForm", "\345\277\203\347\224\265\345\233\276\346\250\241\345\274\217", 0));
        btnDiagnoseModel->setText(QApplication::translate("WaveForm", "\347\233\221\346\212\244\346\250\241\345\274\217", 0));
        btnECGcall->setText(QApplication::translate("WaveForm", "\345\256\232\346\240\207", 0));
        btnOther->setText(QApplication::translate("WaveForm", "\345\205\266\344\273\226", 0));
        btnLeadswitch->setText(QApplication::translate("WaveForm", "\345\257\274\350\201\224\345\210\207\346\215\242", 0));
        btnECGFreeze->setText(QApplication::translate("WaveForm", "\345\206\273\347\273\223", 0));
        lab_HR->setText(QApplication::translate("WaveForm", "--", 0));
        lab_ecg1gaintag->setText(QApplication::translate("WaveForm", "\345\242\236\347\233\212:", 0));
        lab_ecg1leadtag->setText(QApplication::translate("WaveForm", "\345\257\274\350\201\224:", 0));
        lab_hrtag->setText(QApplication::translate("WaveForm", "\345\277\203\347\216\207:   ", 0));
        lab_ECG1lead->setText(QApplication::translate("WaveForm", "II", 0));
        lab_ECG1Gain->setText(QApplication::translate("WaveForm", " x1", 0));
    } // retranslateUi

};

namespace Ui {
    class WaveForm: public Ui_WaveForm {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_WAVEFORM_H
